### ISSUE TITLE
Enhance install instructions to include dependencies

### ISSUE THREAD

**Issue by benjanderson** [HealthCatalyst/Fabric.Cashmere#101]
We are missing some instructions on setting up some of the needed dependencies. 

1. The popover and app switcher component depend on [popper js](https://popper.js.org/) and it has been added as a peer dependency, but we need to state both in the root readme.md and the popover/navbar demo that popper needs to be included in order for those components to function properly

1. According to the [style guide](https://spark.healthcatalyst.com/docs/DOC-3141) the font [Open Sans](https://fonts.google.com/specimen/Open+Sans) is a standard of all our styles. It is planned to be added as a peer dependency but we need to state in the root readme.md that it needs to be included for styles to function properly

**Comment by jtrujill** [comment]
Closing since these are no longer peer-dependencies
