### ISSUE TITLE
Angular pipes section

### ISSUE THREAD

**Issue by benjanderson** [HealthCatalyst/Fabric.Cashmere#103]
I needed a ellipsis pipe while creating the navbar, so I created [this](https://github.com/HealthCatalyst/Fabric.Cashmere/tree/master/lib/src/pipes). It is a part of the library but is largely unknown because it is not documented. I suggest creating a new section for pipes.

As it stands we have **Styles** and **Components** sections, I would suggest a third **Pipes**

**Comment by andrew-frueh** [comment]
I started this conversation on the Slack channel so I'll echo my comments here.  First of all, thanks for making that component @benjanderson, I think it's really useful.  And second, I think if we don't include stuff like this in the documentation, no one will know to take advantage of it (I just randomly came across it in the library).  So I strongly support adding a third section for stuff like this so it's easily findable.

**Comment by corykon** [comment]
Third section sounds cool to me. I'd call it maybe something a bit more generic, like "utilities", so it can include more than just pipes... like @jtrujill's anyToBoolean function that is already in a utils file somewhere. Bet's there's lots of other nifty reusable logic that'll come up..

**Comment by andrew-frueh** [comment]
I opened this discussion a long while back, and I don't think this is something that we've heard anyone  particularly asking for.  So I'm going to close this.
