### ISSUE TITLE
[routerLink] messes up the styles on hc-tabs

### ISSUE THREAD

**Issue by isaaclyman** [HealthCatalyst/Fabric.Cashmere#1030]
**Summary**

When you use tabs without `[routerLink]`, they look like this:

![image](https://user-images.githubusercontent.com/9139369/66783801-f1749d00-ee95-11e9-8ed8-1f28fdeeabe7.png)

When you add a `[routerLink]` attribute to each tab, they look like this:

![image](https://user-images.githubusercontent.com/9139369/66783875-28e34980-ee96-11e9-8e3a-a79a0c0bb07f.png)

Something is not right here. I may have introduced a bug with my SCSS mixins conversion.

**Reproduction**

Steps to reproduce:

1. Use `[routerLink]` on the tabs in an hc-tab-set.

**Comment by isaaclyman** [comment]
On second look, it's even weirder. My content is appearing twice: once beneath the tabs, and once where my `<router-outlet>` element is. Apparently the hc-tab-set automatically injects a router-outlet beneath the tabs when `routerLink` is used. This is probably a documentation issue rather than a bug.

**Comment by isaaclyman** [comment]
I think my expectation here would be that the tab component would _not_ decide where my `<router-outlet>` should go. It's fine if it performs navigation for me and listens to route changes, but I should be able to place my router-outlet wherever makes sense in my application.

**Comment by andrew-frueh** [comment]
@isaaclyman - I was thinking on a fix for this one.  Without introducing a breaking change, I wonder if the solution is to add an input to hc-tab-set called `addRouterOutlet`.  It can default to true, but if it's false, it won't try to add a router outlet or ng-container to hold the tab content, and assume the app will handle that.

Question for my own understanding though - will the Router object in the TabSet constructor still function properly if the router-outlet is outside of the component?  Angular may handle all the routing stuff above the component level so it doesn't matter, but I just want to make sure that if the TabSet tries to navigate to the first route it wouldn't blow up.

**Comment by andrew-frueh** [comment]
Actually, probably a better input name would be `addContentContainer` because if set to false it would not create either a router outlet or ng-container.  And basically then the tab set could just be used as a controller and set values based on listening to events it fires.

**Comment by andrew-frueh** [comment]
@isaaclyman have a look at #1134 and let me know if that would fix the problem for you

**Comment by isaaclyman** [comment]
Approved -- thanks @andrew-frueh.
