### ISSUE TITLE
Make the ActiveModal class generic so data can be strongly typed

### ISSUE THREAD

**Issue by isaaclyman** [HealthCatalyst/Fabric.Cashmere#1033]
**Describe your idea**

The ActiveModal class is commonly injected into modals through the constructor. Its `data` field allows data to be passed by the instantiator of the modal. However, there's no way to specify the type of that data without a cast.

It would be nice if the interface was a generic type, like so:

```typescript
export declare class ActiveModal<T> {
    data?: T;
    close(result?: any): void;
    dismiss(): void;
}
```

We could even have two types, one for `data` and one for `result` in the `close()` method.

```typescript
export declare class ActiveModal<T, U> {
    data?: T;
    close(result?: U): void;
    dismiss(): void;
}
```

**Comment by joeskeen** [comment]
I'm fine with this, as long as the generic types are defaulted to any. That way it shouldn't be a breaking change.
