### ISSUE TITLE
RFC: Cashmere documentation rewrite strategy

### ISSUE THREAD

**Issue by isaaclyman** [HealthCatalyst/Fabric.Cashmere#1034]
@andrew-frueh has asked me to spearhead improvements to the Cashmere documentation. Please read through this RFC and leave comments below, everything is open to change. I'll incorporate your suggestions as we go along.

-----

## Introduction

Cashmere will be eminently more accessible and easier to adopt if our documentation is good. I propose a few guiding principles for this project:

1. The quality of documentation can be measured by how quickly the reader finds what they need and leaves.
1. A code snippet is worth a thousand words.
1. Library code is not documentation. A component, public class, method, or attribute is "documented" if the user can easily find an example of it in action and confidently modify it for inclusion in their own project. Otherwise, it is undocumented.
1. If something is undocumented, it doesn't exist for our users.

## Structure: Components

We'll structure documentation for the Components pages by making sure the following questions are answered.

<sup>In the first few sections of a Components page, raw code snippets will be preferred over Stackblitz frames. Code snippets are easier to scan through quickly, require less interaction, and are easier to maintain.</sup>

_How do I use this component?_

Each page will begin with a code snippet (usually only HTML, but HTML and TypeScript in special cases) representing the most common usage of the component. Most users will copy and paste this code and then leave.

If there are multiple common ways to use the component (e.g. using the `hc-table` class on a standard HTML table, or using the `hc-table` attribute on a table element structured as a CdkTable) we may include more than one code sample in this section.

_How do I use this component's additional template features, like attributes, events, related components, and content projection?_

Here we'll address each potential modification that can be made to the component as part of the HTML template where it's used. Each Input `[attribute]` will have a type signature, an HTML code snippet, and a list of possible values that the user can provide. Each Output `(event)` will have a function signature and a TypeScript code snippet. Each related component (e.g. `hc-label` is a related component for `hc-form-field`; `hc-modal-body` is a related component for `hc-modal`) will have an HTML code snippet. Each component that allows content projection will have an HTML code snippet demonstrating this, if not already demonstrated by previous examples. A brief description of each of the above will also be present.

_How do I call methods or access fields on this component's public class?_

Here we'll demonstrate how to access each component's public class from your own code and use any public methods or fields it provides (e.g. HcPopComponent provides a `close()` method, among others). Each method and field will be represented in a TypeScript code snippet (multiple features can share a code snippet where appropriate, such as `isOpen()`, `close()`, `toggle()` and `open()`).

_Why isn't my component working the way I expect it to?_

We can take a dual approach here: First, providing several Stackblitz examples (maybe in a separate tab), ranging from simple to complex, which the user can fork and modify in order to isolate their problem. Second, providing an FAQ for more complex components, such as HcTable and HcBreadcrumbs.

### To do

We'll keep the Usage and Examples tabs, but change their order so Usage comes first. We'll rewrite the Usage page to match the structure above.

## Housekeeping

- Check every Stackblitz link to make sure they don't have any obvious bugs, either in-place in the documentation or on Stackblitz itself
- Make sure every Stackblitz example implements the component the way our documentation says to

**Comment by andrew-frueh** [comment]
Thank you so much for taking this on @isaaclyman.  Really appreciate all your thoughts above.  One follow-up question - is your recommendation that we change the structure of our components page to match the new approach?  Or does the "examples", "API", "Usage" tab structure still apply?  Just trying to think through how the best way to present that much example code would be.

**Comment by isaaclyman** [comment]
@andrew-frueh At the moment I'm thinking the tabs we have are mostly okay, although I'd like to put Usage first and Examples second. I don't know that the API tab will serve much purpose once we've got the Usage tab all filled out.

**Comment by isaaclyman** [comment]
If there are no other comments, I'll plan on proceeding with a PR to demonstrate how this could work with one of our components.

**Comment by andrew-frueh** [comment]
Hey @isaaclyman - thanks for the nudge.  I think a PR would be good to show what you have in mind.  My only concern with putting usage before examples is that examples is often the best visual indicator of what the component is/does.  It occurs to me that Angular Material sort of mixes the two together onto one long scrolling page:

https://material.angular.io/components/form-field/overview

So I don't know if something like that is actually the best of both worlds?  But I'm gonna rely on your expertise here and look to your recommendation.

**Comment by corykon** [comment]
@isaaclyman I like your overall structure and guiding principles. When I go to in an API, I almost always just want to be in and out with an appropriate code snippet as quickly as possible

I'd agree with @andrew-frueh's comment- it's helpful to me to see at least one example of the component front and center so I know immediately what it is I'm looking at.
