### ISSUE TITLE
No data shown on table when Pagination Component applied before data has loaded.

### ISSUE THREAD

**Issue by waldnercharles** [HealthCatalyst/Fabric.Cashmere#1037]
**Summary**
If the load more pagination component is applied to a table prior to data being populated, the first page is blank.

The rest of the component works as expected.

**Reproduction**
1. Create a table that uses HcTableDataSource.
2. Apply a pagination component to the data source.
3. Add data to the data source.

**Comment by andrew-frueh** [comment]
Investigated this issue with @waldnercharles and @corykon and we weren't able to reproduce it with the current build.
