### ISSUE TITLE
Two-digit year input to datepicker yields 1900-based in IE

### ISSUE THREAD

**Issue by njwhc** [HealthCatalyst/Fabric.Cashmere#1042]
**Summary**

If a date with a two-digit year is manually typed into a datepicker, IE will produce a date with the year in the 1900s. Chrome and Firefox produce dates with the year in the 2000s. My best guess is that this is the result of Cashmere using `new Date(inputString)` or similar to produce the date, which will always give a year in the 1900s in IE.

### IE, input 2/2/19 becomes 2/2/1919:
![IE-datepicker-with-two-digit-year](https://user-images.githubusercontent.com/30876456/67885518-5e7e6880-fb0d-11e9-90a7-ba69d3c6fdc7.gif)

### Chrome, input 2/2/19 becomes 2/2/2019:
![Chrome-datepicker-with-two-digit-year](https://user-images.githubusercontent.com/30876456/67885576-748c2900-fb0d-11e9-9cce-80b467ac6ea2.gif)

**Reproduction**

Steps to reproduce:

1. Type a date with a two-digit year, say `2/2/19` into a datepicker.
1. Tab or click out of the input

~~Stackblitz reproduction~~ Stackblitz does not support IE.

**Additional context**

A partial workaround is to use Angular Material's moment date adapter with Cashmere datepickers. However, this workaround appears to **not** work with Cashmere daterange components.

```js
import {
  MAT_MOMENT_DATE_FORMATS,
  MomentDateAdapter
} from '@angular/material-moment-adapter';
import {
  DateAdapter,
  HC_DATE_FORMATS,
  HC_DATE_LOCALE,
} from '@healthcatalyst/cashmere';

@NgModule({
  ...
  providers: [
    { provide: DateAdapter, useClass: MomentDateAdapter, deps: [HC_DATE_LOCALE] },
    { provide: HC_DATE_FORMATS, useValue: MAT_MOMENT_DATE_FORMATS },
  ]
```

**Comment by andrew-frueh** [comment]
Hey @njwhc - looks like this is an issue with javascript's Date object (it's full of issues):
https://stackoverflow.com/questions/8681534/why-does-javascript-evaluate-a-2-digit-year-of-00-as-1900-instead-of-2000

...but that doesn't mean we can't fix it.  We can add some logic to the onBlur function in the datepicker to make sure the year is being put in this century.  The trickiest part is going to be parsing all the different string formats that the Date object accepts.

I'll bump this up on the priority list, and maybe you and I can brainstorm the implementation before I make any changes.

**Comment by andrew-frueh** [comment]
Thanks for the discussion this morning @njwhc & @jacquie.  I found this description of how FileMaker converts two digit years.  I think it's a pretty solid conversion method for us to follow too, what do you think?

https://fmhelp.filemaker.com/help/12/fmp/en/html/add_view_data.4.21.html

**Comment by andrew-frueh** [comment]
Wow!  You were absolutely right @njwhc - it turns out the reason we couldn't reproduce this on the demo site is because just having the Sugar package installed affects all the Date objects.  It wasn't enough to remove the Sugar example, I had to totally uninstall the package in order to reproduce the issue.  But the good news is, I can see the same behavior you described in IE now - so I'll work on a fix now.
