### ISSUE TITLE
Daterange component is not compatible with moment date adapter

### ISSUE THREAD

**Issue by njwhc** [HealthCatalyst/Fabric.Cashmere#1043]
**Summary**

When trying to use the moment date adapter with datepickers, dateranges (which use datepickers) produce lots of console errors. daterange components still seem to work in that the dates shown look like what was entered / selected.

It appears that the daterange component expects to use `Date` objects and errors when the moment adapter gives it `moment` objects. Likewise, it appears the daterange gives `Date` objects back to the moment adapter, which also causes console errors.

Note, Cashmere datepicker components do work with the moment date adapter.

**Reproduction**

You will need to install `@angular/material-moment-adapter` and, if you don't already have it, `@angular/material`. Then add the following to the module where you import Cashmere / Angular Material packages:

```js
import {
  MAT_MOMENT_DATE_FORMATS,
  MomentDateAdapter
} from '@angular/material-moment-adapter';
import {
  DateAdapter,
  HC_DATE_FORMATS,
  HC_DATE_LOCALE,
} from '@healthcatalyst/cashmere';

@NgModule({
  ...
  providers: [
    { provide: DateAdapter, useClass: MomentDateAdapter, deps: [HC_DATE_LOCALE] },
    { provide: HC_DATE_FORMATS, useValue: MAT_MOMENT_DATE_FORMATS },
  ]
```

You can also add the above providers directly to an `@Component` definition instead of a module. Be careful that you import `DateAdapter` from Cashmere and not the Material provided one. 

**StackBlitz**

Here is a StackBlitz where the above providers are specified on the daterange component: https://stackblitz.com/edit/angular-xfw5gw?embed=1&file=src/app/date-range/date-range-example.component.ts

Change the date or use a preset and look for console errors. The daterange still functions alright.

**Additional context**

Here are a couple screenshots of errors I observed:

![image](https://user-images.githubusercontent.com/30876456/67949696-cbe1d600-fbad-11e9-996a-ed5e1139d441.png)

![image](https://user-images.githubusercontent.com/30876456/67949710-d00df380-fbad-11e9-8d6c-8b18f9f2404e.png)

**Comment by benjanderson** [comment]
There are no dependencies on angular material, so trying to use a material date provider will not work. The date picker is pretty much a copy of the material Date picker, so the confusion is understandable. It should work to just copy over their implementation and change "MAT_" to "HC_" https://github.com/angular/components/blob/master/src/material-moment-adapter/adapter/moment-date-adapter.ts
When I tried this it was failing because the date range component expects native js Dates, not Moment objects (This is a bug). So I had to take a simpler approach and just override parse like the example in docs with sugar https://cashmere.healthcatalyst.net/components/datepicker/examples. 

https://stackblitz.com/edit/cashmere-moment-date-adapter

**Comment by njwhc** [comment]
Thanks, @benjanderson !

> There are no dependencies on angular material, so trying to use a material date provider will not work.

I had a feeling that using the Material moment adapter was not correct, but the Cashmere datepicker usage documentation left me the impression that Cashmere included a moment adapter. When I couldn't find one, I just grabbed the Material one hoping it would work. That's what lead me to `@angular/material-moment-adapter`. That saying about when you have a hammer, everything looks like a nail seems appropriate here. 😆 

Your updated example with the different adapter should work for us. Thanks, again.

------

> When I tried this it was failing because the date range component expects native js Dates, not Moment objects (This is a bug).

Should we keep this issue open for this bit?

**Comment by benjanderson** [comment]
@njwhc No problem!

> Should we keep this issue open for this bit?

I would create a new issue
