### ISSUE TITLE
App Switcher Issues

### ISSUE THREAD

**Issue by corykon** [HealthCatalyst/Fabric.Cashmere#1044]
Few issues I ran into setting up the app switcher. Couple are nitpicky but figured they're thoughts worth capturing just in case. Feel free to triage and split these up as necessary.

- **Cleanup loading styles.** Just so the app switcher is more style compliant, would be nice to clean up the loading state by either using a cashmere loader, or a skeleton screen. Frankly it's unlikely for a user to see this screen, but it'd be nice to get it looking cleaner nonetheless. Some images of current and suggested styles are below.
- **Firmer guidance for sizing in the component** Default is 100px, but this feels a little big. Somewhere around 75px might be nice. I assumed we want webapp apps to use the default, but I wasn't sure. Probably want to make sure we're all aligned here, so I'd appreciate firmer guidance in the docs. 
- **Better support (or documentation) for runtime initialization** Common usage (or at least for both popbuilder and LW) is to get the DiscoveryServiceUrl at runtime from an API call. In order for this to work, you either have to avoid initializing the app switcher by not adding it to the DOM (with an *ngIf or something), or you have to override the AppSwitcherService in a way that prevents the component from breaking on initialization, since it tries to fire a service request immediately. I found it was more complicated to set up for my use case than is detailed in the usage guide. We should either shore up the docs some more, or provide a way to pass in the url after the app switcher is initialized.
- **Document the required sizing for app registration.** The icons in the app switcher have to be at a ratio of 177.7 x 100. I passed up an icon that was a square not knowing the image needed to have padding built in so it looked a little goofy at first. We should document this.

*Current styles*
![image](https://user-images.githubusercontent.com/12416432/67967349-16258000-fbcb-11e9-8828-6928e2f47ba5.png)

*Suggested (Placeholders would have a pulsing opacity animation going on)* 
![image](https://user-images.githubusercontent.com/12416432/67967380-22114200-fbcb-11e9-882c-8259f3af7f56.png)

**Comment by andrew-frueh** [comment]
**Regarding item #1 -** 
Steering committee agrees that the style on "loading applications" should be a spinner.  And if fails to load, should display that as a warning or message...not just spin forever.

**Comment by andrew-frueh** [comment]
**Regarding item #3 -** 
Have the app switcher load when the popover is accessed, not on page load.  Currently discoveryServiceURL most be known at module init, and cannot be loaded async; need a way to get that async at runtime.

**Comment by andrew-frueh** [comment]
Recommend doing this as an Open Space working session to put this together.  Target December OpenSpace - first Thursday

**Comment by andrew-frueh** [comment]
In the component, add disclaimer text under the applications header about apps only being available if you are on the organization's network.  Bonus points - would be doing this dynamically and checking which links are available or not.

**Comment by andrew-frueh** [comment]
Highlight or disable the app that you are currently in so that is doesn't cause confusion or force you to reload (lose your page)
