### ISSUE TITLE
Updated Trademark Language

### ISSUE THREAD

**Issue by aflanders** [HealthCatalyst/Fabric.Cashmere#1050]
On this page: https://cashmere.healthcatalyst.net/styles/trademarks
Change the language under usage guidelines to the follow (note that the second and third paragraphs changes, the first and last paragraph stay the same):

If any trademark (®/™) used above appears multiple times on a page or in a document, either using the “®/™” with the first mention of the mark or with the most prominent use of the mark is sufficient. The logo, if it appears, does not count as the first use.

Do not use trademarked terms as nouns—only use as an adjective. For example:
•	Yes: The HAS™ conference… or The CORUS™ Suite
•	No: HAS™ is an awesome conference. CORUS™ is more than some outdated cost system.

Further, use the mark as a proper adjective modifying a noun that identifies the kind of product offered. Use the trademark together with the generic name of the product/service.
•	Yes: Health systems that value a next-generation costing system rely on the CORUS™ software.
•	No: Health systems that value a next-generation costing system rely on CORUS™.

Never alter a trademark. Do not make it possessive. Do not add prefixes, hyphens, or otherwise modify.

Yes: The reliability of Health Catalyst® services means that health systems can count on…
No: Health Catalyst’s service and reliability means that health systems can count on...

**Comment by andrew-frueh** [comment]
Thanks for submitting this issue @aflanders - just put a pull request in with those changes:
https://github.com/HealthCatalyst/Fabric.Cashmere/pull/1055
