### ISSUE TITLE
Checkbox component causing scrolling to freeze

### ISSUE THREAD

**Issue by snicol21** [HealthCatalyst/Fabric.Cashmere#1053]
**Summary**

During some regression testing of Atlas, users started to experience some freezing up of their scrolling. In an effort to try and figure out why the page would freeze when scrolling, we narrowed the issue down to a component that leveraged the `hc-checkbox` component. After further investigation, we surprising learned that the `.hc-checkbox-overlay` class has a transform `transform: rotate(-45deg);` style that rotates a border to look like a check-mark. Simply commenting out this `transform` style fixed the page from freezing.

**Fix**

We implemented our own fix by adding a uni-code check-mark instead of using this transformation

```
.hc-checkbox-overlay {
    position: relative;
    width: 22px;
    height: 22px;
    background-color: $white;
    border: 2px solid $gray-300;
    border-radius: 3px;
    cursor: pointer;
    &:after {
        content: '\2714';
        color: $white;
        font-size: 15px;
        font-weight: bold;
        position: absolute;
        top: 2px;
        cursor: pointer;
    }
}
```

However, our check mark no longer looks as pretty as it used to, but this was the work around we implemented to fix the more pressing issue of the page freezing up occasionally while users were scrolling.

We're not quite sure why this is happening. We are using the scroll-nav component of cashmere on the same page that this issue is occurring on, which may have some unintended conflicts with this checkbox, however ... we're not really sure why this is happening.

**Comment by corykon** [comment]
@snicol21 Was this happening on a particular browser?

**Comment by snicol21** [comment]
@corykon Good question! You're right, I'm pretty sure we were only experiencing this on Chrome.

**Comment by snicol21** [comment]
Here's a link to the line of code we're talking about:

https://github.com/HealthCatalyst/Fabric.Cashmere/blob/1f242ca1fc474830515c204a0825ef6186a93dbd/projects/cashmere/src/lib/sass/checkbox.scss#L48
