### ISSUE TITLE
Navbar menu items cutoff when extra text added to the username

### ISSUE THREAD

**Issue by jacquie** [HealthCatalyst/Fabric.Cashmere#1066]
This may just be a Leading Wisely issue, but when we add extra text to the user name field the navbar doesn't detect the right size for it and the menu items get cut off instead of showing the `More` drop down. 
![navbarcutoff](https://user-images.githubusercontent.com/1377008/70365512-f5e28400-184e-11ea-8fb7-ce0bde97ba98.PNG)

**Comment by andrew-frueh** [comment]
Thanks for reporting this @jacquie - I don't think it's just Leading Wisely.  That "more" dropdown is pretty problematic and could definitely use a tune-up

**Comment by corykon** [comment]
Related: Sometimes links that are two words will wrap. They should never wrap, and stuff should pop into "more" a little sooner.

![image](https://user-images.githubusercontent.com/12416432/70649971-6bfa3880-1c0b-11ea-9c23-65d24d827b70.png)

**Comment by corykon** [comment]
Also, a related github issue #671
