### ISSUE TITLE
ToasterModule should export cdk overlay module

### ISSUE THREAD

**Issue by andrew-frueh** [HealthCatalyst/Fabric.Cashmere#1091]
**Summary**

Discovered when I was adding hcToast to Access Control that I had to import the cdk overlay module independently to keep unit tests from failing.  It looks like hcPop is already doing this correctly, so need to adjust hcToast as well.

**Comment by joeskeen** [comment]
This is the line that needs to be fixed:

https://github.com/HealthCatalyst/Fabric.Cashmere/blob/159b1ea165d705c4b719ed58826ad2c7ff429fef/projects/cashmere/src/lib/toaster/hc-toaster.module.ts#L9

It looks like the module doesn't import OverlayModule, but it does import PortalModule (which I think imports/exports OverlayModule) - so maybe we can just export PortalModule from ToasterModule?

**Comment by andrew-frueh** [comment]
I wonder if that's an oversight - _should_ that module be importing the `OverlayModule`?  I tried to find a reference to the CDK portal module to check, but I'm having a hard time finding it.

**Comment by andrew-frueh** [comment]
@joeskeen - over in Access Control, to test this out, I removed the `OverlayModule` import that we added (which fixed the unit test) and replaced it with an import of `PortalModule` and the unit test broke again.  So perhaps the solution here is to import `OverlayModule` in ToastModule and then also export it?

**Comment by joeskeen** [comment]
Interesting... I wonder what popmodule does?

**Comment by andrew-frueh** [comment]
Yeah I was curious about that too.  PopModule imports `OverlayModule`, `A11yModule`, and `BidiModule` from the CDK, but only exports `BidiModule`.

`@NgModule({
    imports: [CommonModule, OverlayModule, A11yModule, BidiModule],
    declarations: [
        HcPopComponent,
        HcPopoverAnchorDirective,
        MenuDirective,
        MenuItemDirective,
        MenuIconDirective,
        MenuTextDirective,
        MenuSubTextDirective,
        DividerDirective
    ],
    exports: [
        HcPopComponent,
        HcPopoverAnchorDirective,
        BidiModule,
        MenuDirective,
        MenuItemDirective,
        MenuIconDirective,
        MenuTextDirective,
        MenuSubTextDirective,
        DividerDirective
    ]
})
export class PopModule {}`
