### ISSUE TITLE
Navbar Username doesn't support multiple lines

### ISSUE THREAD

**Issue by andrew-frueh** [HealthCatalyst/Fabric.Cashmere#1105]
**Summary**

Teams need to be able to display two lines for a username.  Currently the navbar does not handle the styling on that correctly.  Also, developers would like the ability to turn off the username truncation (currently set to 150px)

<img width="286" alt="Screen Shot 2020-01-10 at 2 25 08 PM" src="https://user-images.githubusercontent.com/22795893/72187679-93ccef80-33b5-11ea-8bc7-193411e83116.png">

**Comment by robertjorg** [comment]
Shouldn't we add the ability to be a dynamic width? In PS we had to change the width so it will display like : 
![image](https://user-images.githubusercontent.com/16354995/72188998-f2e03380-33b8-11ea-9939-f107ecada6f3.png)
Alternatively, where would this break? Patient Safety is going to switch to display names this year, but still feel a dynamic width would be better then a second line. When you have a person with a long first and last name with a width of 150px only, where do you split the name to go to a second line?
![image](https://user-images.githubusercontent.com/16354995/72189172-6c782180-33b9-11ea-9082-b6b54dae42e0.png)

**Comment by andrew-frueh** [comment]
Great feedback @robertjorg.  Based on your point and something similar from @corykon, I'm gonna go ahead and remove the max width entirely from that username class.  It would be really easy for an app to add an additional class to cap the width and truncate if they wanted to.  But better to leave that up to the apps rather than forcing it on them.
