### ISSUE TITLE
Navbar + AppSwitcher Issues

### ISSUE THREAD

**Issue by corykon** [HealthCatalyst/Fabric.Cashmere#1110]
**1. More menu triggering too early and then getting stuck.** 
![navbarMoreBug](https://user-images.githubusercontent.com/12416432/72293866-9cb9fd00-3611-11ea-9a2a-d1e4f97feffd.gif)

Was going to create a stackblitz to repro but noticed the navbar stackblitzes don’t work:
- Doesn't load: https://stackblitz.com/run?file=src/app/navbar-app-switcher/navbar-app-switcher-example.component.html&hidedevtools=1
- Loads but the more menu isn't working, and the images don't load in: https://stackblitz.com/run?file=src/app/navbar-overview/navbar-overview-example.component.html&hidedevtools=1 

-------------------------------------------

**2. App switcher icons are squished**
Probably should be able to handle icons regardless of the size it is given. (Tricky but should be doable in css)
![image](https://user-images.githubusercontent.com/12416432/72293895-aba0af80-3611-11ea-9008-c88ee7a61fa6.png)

**Comment by andrew-frueh** [comment]
Might need your help troubleshooting this one @corykon - I can't reproduce the issues with the More menu on the demo site.  Is there anything about the way PopBuilder's navbar is set up that would make it different?

**Comment by corykon** [comment]
Have a hunch - I think the issue may be that `_collectNavLinkWidths()` is only called once right after init. The links in pop builder's navbar can be added and removed well after initialization based on feature flags, who you're logged in as, etc.

Fix would be to call collectNavLinkWidths whenever `_navResize()` is called. You'd want to debounce the window resize listener to be sure it doesn't tank performance.

**Comment by andrew-frueh** [comment]
Ah - yup, I bet that's what it is.  And @jacquie had it doing that before - but I switched it to only on init :-(

**Comment by andrew-frueh** [comment]
So here's the challenge we'll have to get around if we call `_collectNavLinkWidths()` on `_navResize()` - when navbar links are hidden in that function, subsequent calls to get their widths will return as 0 until they are visible again.  So we'll end up getting fluctuating results unless we add some logic.

Perhaps the function can check to see if the number of items in `linksWidths` has changed.  And if so, it shows all of them, updates the array and then won't recalculate again unless the number of links change.
