### ISSUE TITLE
More date range preset picker woes 

### ISSUE THREAD

**Issue by jacquie** [HealthCatalyst/Fabric.Cashmere#1111]
**Summary**

Although the chosen preset is being communicated back out of the date range picker there are still some odd things happening when the presets coincidentally happen to describe the same date range.

**Reproduction**
In this example the current date is Jan 13 and the last 3 presets are 'month to date', 'quarter to date' and 'year to date' which all happen to map onto Jan 1 - 13
When I select the 'month to date' button it actually selects the 'year to date' button instead
Interestingly if I then select the 'month to date' button again it does select it correctly.

![daterangepicker](https://user-images.githubusercontent.com/1377008/72294912-bf4d1580-3613-11ea-8482-aa9f4b9fc70a.gif)

Also if I select 'month to date' apply it, and then reopen the dialog the 'year to date' option is preselected as shown here:
![wrongpreset](https://user-images.githubusercontent.com/1377008/72295487-e9eb9e00-3614-11ea-9b83-1d10d42c9c19.PNG)

There is no way of passing in the preselected preset item and it is calculating it from the passed in dates and not always getting it right.  Would it be possible to add something like an optional 'currentlySelected' property to the `PresetItem` interface so it doesn't need to guess

**Comment by andrew-frueh** [comment]
Gotcha - thanks for the detailed write-up @jacquie.  As you correctly surmised, when the dialog opens - it's using the value of `selectedDate` to determine what preset radio to select.  I'm thinking that perhaps `selectedDate` could accept either a date range or a numerical index (which would indicate a specific preset to select).  Thoughts on that?

**Comment by jacquie** [comment]
Yes I think that approach would work and would mirror the outgoing dateRange or numerical index pattern :)
