### ISSUE TITLE
Provide Feedback Component

### ISSUE THREAD

**Issue by andrew-frueh** [HealthCatalyst/Fabric.Cashmere#112]
@corytak already has this underway on Measures Manager, but I wanted to make sure it was included in the project plan.  Catalyst is standardizing the way that it collects in-app feedback from users (leveraging a TypeForm survey).  The survey is triggered from a "Provide Feedback" option in the Help Menu popover.  We'll want this experience to be universal across our apps, so Cory has already started turning it into a component that can be shared.

<img width="743" alt="feedbacksurvey" src="https://user-images.githubusercontent.com/22795893/36067964-c36398da-0e86-11e8-84cc-bb208d93fc02.png">

**Comment by joeskeen** [comment]
I like the idea, IMHO the screenshot shows a survey that doesn't make very good use of vertical space.  Is this a third-party thing we don't have any control of?

**Comment by corytak** [comment]
@joeskeen exactly. This is from a company called Typeform. They provide an embed script that goes out and fetches the additional js/styles to make the survey look like this. They have different options on their site for how the survey can be formatted and those are configured on their site. The thought for the component is that an app would just need to include this component and provide the url:
```
<hc-typeform-survey href="typeFormUrl" #survey>
</hc-typeform-survey>
```

**Comment by corytak** [comment]
Additionally each app would be responsible for determining how often a user was surveyed (e.g. keep track of that in a usersurvey table and only ask the user to take a survey every 30 days).
