### ISSUE TITLE
Bug: 'Today' button on datepicker doesn't work with max date set to today

### ISSUE THREAD

**Issue by Techgeekster** [HealthCatalyst/Fabric.Cashmere#1125]
When you set a max date to 'today', the today button doesn't navigate back to today.  It'll either be greyed out, or it just won't do anything.

Here's a stack blitz:
https://angular-nne2ch.stackblitz.io

Thanks!

**Comment by andrew-frueh** [comment]
Thanks for the StackBlitz @Techgeekster - I'm on it.
