### ISSUE TITLE
Popover on Form-Field sub-element doesn't display when triggered

### ISSUE THREAD

**Issue by bvanfleet** [HealthCatalyst/Fabric.Cashmere#1147]
**Summary**

When a popover is added to a sub-element of `hc-form-field` it won't display when the user hovers over the sub-element.

**Reproduction**

Steps to Reproduce:
1. Create `hc-form-field` with a label (with or without an embedded `hc-icon`)
2. Add hcPop to the label (or icon if using) and run the application, all other settings are irrelevant.
3. Confirm that the popover doesn't show when triggered on the label or icon.

Stackblitz reproduction (click the "Edit on Stackblitz" link on a component example and fork the template):

https://stackblitz.com/edit/angular-3wzzug

**Comment by pheebner** [comment]
Do you guys know when this might be fixed? Not blocked or anything, just wondering. Ran into this today.

**Comment by corykon** [comment]
@bvanfleet submitted a PR fixing this, sorry for the delayed response 

In the meantime, if you happen to need to get this working, you could override some css that was setting `pointer-events: none;` Check out the PR for details.
