### ISSUE TITLE
Very minor App Switcher UI issue

### ISSUE THREAD

**Issue by corykon** [HealthCatalyst/Fabric.Cashmere#1155]
The app switcher has a max-width of 410px. Seems reasonable, but when you leave everything on the defaults, the spacing on chrome/windows on the right side is little awkward.

![image](https://user-images.githubusercontent.com/12416432/73703439-13946400-46ad-11ea-91b6-5174596926be.png)

For now I'm overriding the switcher's width to 360px in my app.

**Comment by andrew-frueh** [comment]
Good catch - and yes, 360px seems to be what it should be to allow rows with three columns.  I'll throw in a quick fix for this.
