### ISSUE TITLE
strange shape in background while loading

### ISSUE THREAD

**Issue by benjanderson** [HealthCatalyst/Fabric.Cashmere#116]
The loading screen that @jacquie recently added is amazing and very professional. However, I noticed there is a strange "Utah" shape in the background.. Can others confirm this, or is it just my environment?

**Windows 10
Chrome Version 61.0.3163.100 (Official Build) (64-bit)**

![image](https://user-images.githubusercontent.com/1934453/36102549-df0f21aa-0fc9-11e8-82fc-fc893ac10325.png)

**Comment by joeskeen** [comment]
It's the Utah watermark.  Don't you know about the Utah watermark?

**Comment by benjanderson** [comment]
This magically disappeared on my screen lately, and since no one else confirmed this, I am closing
