### ISSUE TITLE
Hc-Checkbox without width also alignment of checkbox

### ISSUE THREAD

**Issue by robertjorg** [HealthCatalyst/Fabric.Cashmere#1166]
**Summary**

When using hc-checkbox, the checkbox gets really small when the description/label for the checkbox is long. We had to add a max-length to the label with an important tag to make it look correct

.hc-checkbox-label {
  max-width: 90% !important
}

Could we also put an option to align the checkbox? We would like to align the check box to the topod the long label

Browser: Chrome
Cashmere version 6.2.0

![image](https://user-images.githubusercontent.com/16354995/74478167-08d68d80-4e6a-11ea-930b-c4e86fb566a1.png)

**Comment by andrew-frueh** [comment]
Ah interesting.  I don't know that I've really tested for that use-case, so thanks for the screenshot.  Seems like we need to make sure the checkbox isn't allowed to compress like that.  And good suggestion for an `align` parameter.

This is probably a pretty quick fix.  I'm angling for a release tomorrow.  So let me see if I can get this fix in this afternoon.  I'll keep ya posted.

Thanks @robertjorg !
