### ISSUE TITLE
Picklist apply button should be disabled when there are no changes.

### ISSUE THREAD

**Issue by waldnercharles** [HealthCatalyst/Fabric.Cashmere#1167]
The picklist's apply button should disable when the user hasn't made any changes to either pane.

If we already store the initial state of both panes, this should be fairly trivial to add by comparing the intial state of one pane to its current state whenever a change is made.

**Comment by andrew-frueh** [comment]
Hey @waldnercharles - @corykon and I were taking a look at this today, and were wondering about the apply button you're referring to.  The component itself doesn't actually have any apply button (see screenshot below).  Is that button something that's in your app's code?  If so, you should be able to apply the logic as you described it to enable/disable the button.  Let us know if we're misinterpreting the request.

<img width="1034" alt="Screen Shot 2020-04-08 at 1 09 35 PM" src="https://user-images.githubusercontent.com/22795893/78823649-45ba8e80-799a-11ea-98b4-2dda898c3a75.png">

**Comment by corykon** [comment]
@andrew-frueh should we close this guy too?

**Comment by andrew-frueh** [comment]
@corykon yes, closing this since it appears to not refer to functionality within the component
