### ISSUE TITLE
App Switcher doesn't indicate which app is the current app that you're in

### ISSUE THREAD

**Issue by braydengramse** [HealthCatalyst/Fabric.Cashmere#1183]
I wanted to update our app so that when you open the app switcher it either wouldn't show Population Builder at all or somehow indicate that you were already in that app. I added the `serviceName` and `serviceVersion` to the `hc-app-switcher` component in our HTML. When I inspect the element in Chrome's developer tools, it doesn't seem to be adding the class correctly.

![image](https://user-images.githubusercontent.com/14908294/75803278-6fe5b480-5d3b-11ea-9bf0-71007927da8e.png)

**Comment by andrew-frueh** [comment]
Thanks for reporting this @braydengramse.  As of version 6.3.0, the app switcher _should_ have code to distinguish the current app from the others.  It should be applying a style called `hc-app-switcher-link-highlighted` and disabling the link for the current app.  The logic in the component looks like this:
`return app.ServiceName === this.serviceName && app.Version === this.serviceVersion;`

So we probably need to do some troubleshooting to figure out why that's coming back false for you. @corykon - any thoughts?

**Comment by andrew-frueh** [comment]
Following up @braydengramse - @corykon and I took a look at this and there was definitely a bug in the logic of the app switcher.  We just got a fix PR in and I'll get a patch out by end of day.

**Comment by braydengramse** [comment]
Awesome! I was just going to say that I was playing around with it and I was able to get it to work if I did it this way: `<hc-app-switcher serviceName="MyService" [serviceVersion]="1">`. In the docs it looked like this: `<hc-app-switcher serviceName="MyService" serviceVersion="1">`.

**Comment by andrew-frueh** [comment]
Ah interesting - yeah the issue came down to a failing logic comparison between a string and a number...and so Angular was returning an object instead of a boolean.  You can take a look at the fix here if you're interested: #1184
