### ISSUE TITLE
hc-select doesn't support optgroup elements.

### ISSUE THREAD

**Issue by jayols** [HealthCatalyst/Fabric.Cashmere#1188]
**Summary**

Trying to use optgroup elements to group options within an hc-select and it doesn't appear to work - just renders an empty list.

**Reproduction**

https://stackblitz.com/edit/cashmere-optgroup-select?file=src/app/select-standard/select-standard-example.component.html

**Additional context**

Cashmere v6.7.1

**Comment by andrew-frueh** [comment]
Great suggestion, Jayson!  We hadn't heard of anyone using option groups up until now, but we should definitely support it.  I'll make this a high priority to get a fix in early next week.

**Comment by jayols** [comment]
Thanks Andrew!  This will definitely help because we have a couple features in our CM app that uses grouped selects and they are using a rather convoluted method to render the options in a similar manner (but involves more code and css).  Using an optgroup element would greatly simplify both of those implementations.

**Comment by jayols** [comment]
Some additional on this – if possible, it would be nice if a related bug ticket (setting value to object) could also be fixed as we currently have a need for that type of behavior as well.

Thanks,
Jayson

**Comment by andrew-frueh** [comment]
That one, unfortunately, is harder because we have to work around an Angular limitation:

https://github.com/angular/angular/issues/26273

In that thread you can see they propose extending SelectControlValueAccessor, but the tricky part is that Select already extends HcFormField so that it can function with hc-form-field.  But where there's a will there's a way.  I know @joeskeen took a look at this a little while back and hit the same wall I have - but maybe if you're interested, the three of us could put our heads together and see if we can brainstorm some clever way around this.

**Comment by joeskeen** [comment]
I have an idea that involves composition rather than inheritance. The hc-select could be hcFormField, but have a child that is SelectControlValueAccessor. I'd love to try it out sometime...

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by andrew-frueh** [comment]
I was experimenting last night with making Select extend SelectValueController instead and implement HCFormField...and it looks promising.  However I’m still struggling to get a change event to pass an object not a string.  Angular converts the object to a value of {1: object}, essentially object to string.

Anyway, I feel like this is doable, just requires some finesse.  I’ll schedule 30 mins for next week to brainstorm - and if you guys can help give me some direction I’m happy to do the grunt work.

**Comment by jayols** [comment]
Sounds good, thanks Andrew!

**Comment by andrew-frueh** [comment]
@jayols - I think we finally cracked the bug on objects in ngValue: #1197.  I'll let you know when it's released.
