### ISSUE TITLE
Create syntax highlighting standards

### ISSUE THREAD

**Issue by cedar-ave** [HealthCatalyst/Fabric.Cashmere#119]
It could be helpful to guide how to style code presented in documentation and apps.

One use case is documentation sites that need to style endpoints in prose. [Here is an example page of HC documentation](https://platformdocs.healthcatalyst.com/articles/etl/single-use-pipelines.html) with both inline and block.

Another use case is apps that have SQL blocks, like SAMD and EDW Console.

In blocks, the documentation generator we use automatically styles/colors the code based on the language identified in the markdown code (like the JSON in the link above) but the block background can still be standardized.

Guidance on a readable "code" font would also be helpful.

**Comment by andrew-frueh** [comment]
Great suggestion @cedar-ave!  We were just discussing today that it would probably be valuable on the Cashmere site to break out the component demos from the developer documentation #97.  @jtrujill and @corytak both mentioned the possibility of using markdown for the developer docs, and I suspect we could learn quite a bit from what you're already doing with your documentation.  Would be great to loop you in on that demo/documentation split if you're interested.  Could potentially become a standard we could follow elsewhere.

**Comment by cedar-ave** [comment]
Sure - can definitely help if I have anything useful to add. Markdown is definitely the way to go in my opinion and an easy win. Are any docs written yet?

**Comment by andrew-frueh** [comment]
Well right now [everything is rolled into one](http://cashmere.healthcatalyst.net/demo/button) - the component demo, the usage guidelines, the demo code, and the component parameters.  Which seemed fine at first, but is already becoming cumbersome.  @jtrujill pointed out that as a developer he would rather not have to scroll through a bunch of component demos just to get to the list of parameters for a given component.  What I think I'll do is get a few of us together to discuss what belongs on the "component" page and what belongs on the "documentation" page.  And then we could work on a markdown template for the documentation.

**Comment by andrew-frueh** [comment]
Hey @cedar-ave, I'm glad you brought up syntax highlighting standards and formatting for `<code>` blocks in general.  I was actually just talking this through with @snicol21 yesterday for some work he's doing on documentation for Shared Data Marts.  What we came up with was pretty similar to what you're doing on your HC Documentation page as far as the font, size, background, etc.  But maybe Spencer can provide some additional info and/or screenshots?  And I'd love to hear what you are using for your syntax highlighting, Marla.

**Comment by cedar-ave** [comment]
@andrew-frueh I believe the tool I'm using to generate the website (DocFX) uses [highlight.js in the Github gist theme](https://highlightjs.org/static/demo/)
Here are the DocFX [details](https://dotnet.github.io/docfx/spec/docfx_flavored_markdown.html?tabs=tabid-1%2Ctabid-a#code-snippet)

**Comment by andrew-frueh** [comment]
Thanks @cedar-ave - I like the "GitHub Gist" theme better than the normal "GitHub" theme.  @snicol21  - I'd recommend using that one as well for your Shared Data Marts docs page.

@benjanderson @jtrujill @corykon @corytak or anyone else have any experience integrating highlight.js with their Angular project?  We wouldn't build that dependency into the library, but maybe for the demo site?  Looks like there is an [npm package](https://www.npmjs.com/package/highlight.js/) for it.  Is that the right approach?  

And then to Marla's original question, this would become the defacto standard for syntax highlighting in any Catalyst docs.
