### ISSUE TITLE
Pagination styles are not correct

### ISSUE THREAD

**Issue by joeskeen** [HealthCatalyst/Fabric.Cashmere#1194]
**Summary**

Pagination should/used to look like this:
![image](https://user-images.githubusercontent.com/12286274/76232929-078c4c80-61ed-11ea-81c6-5ebcb1b98fff.png)
But now sometimes looks like this:
![image](https://user-images.githubusercontent.com/12286274/76232822-e3c90680-61ec-11ea-9c51-deb779fb1c73.png)

It seems that the styles for the paging buttons are not specific enough, and as a result the `.hc-button.hc-secondary` styles are taking over.

**Reproduction**

Steps to reproduce:
Simple Pagination example on StackBlitz without modification shows the problem:
https://stackblitz.com/edit/angular-tquq31?file=src/app/pagination-simple/pagination-simple-example.component.html

**Additional context**

Should be an easy fix.  In the dev tools I was able to fix it by changing these classes:
* `.hc-page-button[_ngcontent-trw-c12]` to `.hc-button.hc-secondary.hc-page-button[_ngcontent-trw-c12]` 
* `.hc-page-button.currentpage[_ngcontent-trw-c12]` to `.hc-button.hc-secondary.hc-page-button.currentpage[_ngcontent-trw-c12]`.
* `.hc-page-button[_ngcontent-trw-c12]:hover` to `.hc-button.hc-secondary.hc-page-button[_ngcontent-trw-c12]:hover`

**Comment by andrew-frueh** [comment]
Closed in #1217
