### ISSUE TITLE
navbar cuts off right hand item in IE

### ISSUE THREAD

**Issue by jacquie** [HealthCatalyst/Fabric.Cashmere#1196]
**Summary**

Just in IE the user name item doesn't get enough room allocated on the navbar.
![navbarname](https://user-images.githubusercontent.com/1377008/76433309-c5444600-6379-11ea-8221-93f564e9e8d4.jpg)

**Comment by corykon** [comment]
I ran into something like this recently too... Thought it was just something caused by my own overrides, but it may be the same issue. I'll look into it!

**Comment by corykon** [comment]
@jacquie which version are you guys currently on? Looks like my fix for this actually went into 6.7.0.

https://github.com/HealthCatalyst/Fabric.Cashmere/pull/1158

**Comment by jacquie** [comment]
We are only on 6.6.1 - I will update and report back - thanks!

**Comment by corykon** [comment]
You bet!

**Comment by jacquie** [comment]
It is perfect in 6.7.3 :)  Thanks - I'll close this bug!
