### ISSUE TITLE
Split buttons using popovers have odd item hover

### ISSUE THREAD

**Issue by njwhc** [HealthCatalyst/Fabric.Cashmere#1202]
**Summary**

This may be a rare use-case, but figured it's worth reporting anyway. The menu items with popovers inside a `hc-split-button` have strange highlighting when you hover over the menu buttons. A video explanation is probably easier. Watch the blue mouse-over bit as the mouse moves between the menu items:

![C8238C88-1157-4B7D-9E8B-8D95AC702AAB](https://user-images.githubusercontent.com/30876456/76968473-96385200-68ee-11ea-87b4-1348e7d70212.GIF)

It's just a visual mismatch with a little uncertainty about what item is actually going to get clicked. The button the mouse is over is the button that receives the click event. A simple workaround is to not use popovers.

**Reproduction**

Steps to reproduce:

1. Add a `hc-split-button`
1. Add at least three `hcButtonItem` buttons inside it
1. Add an `hcPop` to each button item
1. Try hovering over each button in the list

Notice how the item shown as being hovered over is not aligned with the item you are actually hovering over.

Stackblitz reproduction: https://stackblitz.com/edit/angular-rxw2g3?file=src%2Fapp%2Fbutton-split%2Fbutton-split-example.component.html

**Additional context**

Here is a GIF showing a split button without an popovers:
![AEAEB0BD-4802-4A68-BDAB-35798DAF5352](https://user-images.githubusercontent.com/30876456/76967472-22497a00-68ed-11ea-9767-7692a3fa7997.GIF)

Here is a GIF showing a split button with popovers:
![C8238C88-1157-4B7D-9E8B-8D95AC702AAB](https://user-images.githubusercontent.com/30876456/76967605-45742980-68ed-11ea-8aa6-358d967539bc.GIF)

**Comment by njwhc** [comment]
Aha! It seems that using `[restoreFocus]="false"` on the `hc-pop`s for each button makes everything behave nicely.

![BE3D82B8-C988-42B7-A26D-5F6DFE6D8533](https://user-images.githubusercontent.com/30876456/76975686-86257000-68f8-11ea-8db9-549ee701798d.GIF)

Template used for above gif is an adaptation of as the linked Stackblitz above:

```html
<hc-split-button>
    Plot Actions

    <button hcButtonItem [hcPop]="fertilizePopover" trigger="hover">
        <hc-icon hcMenuIcon fontSet="hc-icons" fontIcon="hci-active"></hc-icon>
        <span hcMenuText>Fertilize plot</span>
    </button>
    <hc-pop #fertilizePopover verticalAlign="below" [restoreFocus]="false">
      <p>Supercharge this plot for faster plant growth!</p>
      <p>Fertilizer available: 14</p>
    </hc-pop>

    <button hcButtonItem [hcPop]="carrotPopover" trigger="hover" (click)="plantCarrot()">
        <hc-icon hcMenuIcon fontSet="hc-icons" fontIcon="hci-plant"></hc-icon>
        <span hcMenuText>Plant Carrot</span>
    </button>
    <hc-pop #carrotPopover verticalAlign="below" [restoreFocus]="false">
      <p>Plant a carrot</p>
      <p>Seeds available: 5</p>
    </hc-pop>

    <button hcButtonItem [hcPop]="potatoPopover" trigger="hover" (click)="plantPotato()">
        <hc-icon hcMenuIcon fontSet="hc-icons" fontIcon="hci-plant"></hc-icon>
        <span hcMenuText>Plant Potato</span>
    </button>
    <hc-pop #potatoPopover verticalAlign="below" [restoreFocus]="false">
      <p>Plant a potato</p>
      <p>Spuds available: 2</p>
    </hc-pop>

    <div hcButtonItem hcDivider></div>
    <button hcButtonItem disabled>
        <hc-icon hcMenuIcon fontSet="hc-icons" fontIcon="hci-in-dev"></hc-icon>
        <span hcMenuText>Till plot</span>
        <span hcMenuSubText>Plot already tilled</span>
    </button>
    <button hcButtonItem disabled>
        <hc-icon hcMenuIcon fontSet="hc-icons" fontIcon="hci-vial"></hc-icon>
        <span hcMenuText>Water plot</span>
        <span hcMenuSubText>Plant something</span>
    </button>
</hc-split-button>
```

**Comment by andrew-frueh** [comment]
Great troubleshooting @njwhc and thanks for reporting back on the fix that worked for you!
