### ISSUE TITLE
Sticky headers should not overlap table 

### ISSUE THREAD

**Issue by corinnen** [HealthCatalyst/Fabric.Cashmere#1207]
When using the `sticky` property on the `hc-header-row`, table data is still scrolling underneath the header.
![image](https://user-images.githubusercontent.com/42940112/77342575-a173ef00-6ced-11ea-9a5e-67b3f7c602af.png)
The fix I have come up with includes adding a background color of white to `.hc-table th` (or pink).
![image](https://user-images.githubusercontent.com/42940112/77343028-4abae500-6cee-11ea-95a8-5f721b3d0a4a.png)
And to remove the still visible top pixel and edge borders use `border-collapse: separate;` on the `.hc-table`.
![image](https://user-images.githubusercontent.com/42940112/77343255-a4bbaa80-6cee-11ea-9681-ed140d8e325c.png)

**Comment by andrew-frueh** [comment]
Thanks for reporting this @corinnen! We've got a few issues related to sticky table headers, so we'll look into this soon.  Glad you found a workaround though.
