### ISSUE TITLE
Navbar app switcher Stackblitz is broken

### ISSUE THREAD

**Issue by isaaclyman** [HealthCatalyst/Fabric.Cashmere#1209]
Must be some error in our stackblitz generation, since the element in question definitely exists.

> Error in /turbo_modules/@angular/compiler@6.1.7/bundles/compiler.umd.js (1098:21)
Template parse errors:
'hc-navbar-app-switcher-example' is not a known element:
> 1. If 'hc-navbar-app-switcher-example' is an Angular component, then verify that it is part of this module.
> 2. If 'hc-navbar-app-switcher-example' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("[ERROR ->]<hc-navbar-app-switcher-example></hc-navbar-app-switcher-example>"): ng:///AppModule/ExampleContainerComponent.html@0:0

**Comment by andrew-frueh** [comment]
Fixed in #1274
