### ISSUE TITLE
Buggy styles for input borders (Firefox on windows)

### ISSUE THREAD

**Issue by corykon** [HealthCatalyst/Fabric.Cashmere#1211]
Firefox on windows isn't handling the .5 inset shadow hack to create 1.5px borders:
![image](https://user-images.githubusercontent.com/12416432/77682410-822ec900-6f5c-11ea-8293-dfeb23aa585a.png)

**Comment by andrew-frueh** [comment]
Alright @corykon I think I'm finally ready to pull the trigger on this one.  I've tried it a number of different ways, and I'm thinking of going with 1px `$gray-400` for all our form field borders.

I was research [accessibility standards for input boxes](https://www.w3.org/WAI/GL/low-vision-a11y-tf/wiki/Contrast_(Minimum)), and if we were going to be fully WCAG compliant - we would need our 1px borders to have a contrast ratio of 4.5 : 1.  `#a1a1a1 is 2.6 : 1.  But to my eye, if we go darker than that, it actually decreases the readability of the page because the labels and the borders all run together.

So here's a screenshot of what I'm thinking.  Any thoughts/concerns/suggestions?

![Screen Shot 2020-06-25 at 3 43 08 PM](https://user-images.githubusercontent.com/22795893/85800052-86a28380-b6fd-11ea-9874-3dc00961f1fc.png)

**Comment by andrew-frueh** [comment]
Screenshot updated in the above post in case the wrong one came through in the email

**Comment by andrew-frueh** [comment]
For comparison, this is 1px `$slate-grey-300` which is what we use for the border on tabs and tables.  It's a 1.73 : 1 ratio, so way below the target - but maybe better for readability?  What is your preference?

<img width="1033" alt="Screen Shot 2020-06-25 at 4 14 52 PM" src="https://user-images.githubusercontent.com/22795893/85801048-4fcd6d00-b6ff-11ea-8dab-2e935e0eb87e.png">

**Comment by andrew-frueh** [comment]
I often forget that I'm on a high contrast MacBook monitor - but I wonder if less ideal displays would really struggle with `$slate-grey-300` and it would totally fade into the background?

**Comment by corykon** [comment]
It is nice to have a standard to backup a decision... but $slate-gray-300 is for sure more to my taste than $gray-400. I have a hard seeing either be a being a problem. Esp since there is typically placeholder text inside of it.

Also, for the record, GitHub inputs use #dfe2e5, which is even lighter than slate-gray-300's #c0c5cc. GitHub seems to be doing fine right? :)

Do you have thoughts on focus/hover/error states as well?

**Comment by corykon** [comment]
I'd love to understand a little better where the 4.5 exactly came from. What data backs that ratio up? If you read the meeting minutes from that [standards page](https://www.w3.org/WAI/GL/low-vision-a11y-tf/wiki/Contrast_(Minimum)) you referenced, seems like even some members of the committee felt that 4.5 to 1 was too much.

**Comment by andrew-frueh** [comment]
Okay I buy that.  PR submitted for you to take a look at.  One possible way to resolve my concerns on the checks and radios would be to put a really light fill on the empty state:

<img width="1031" alt="Screen Shot 2020-06-25 at 5 36 38 PM" src="https://user-images.githubusercontent.com/22795893/85805832-a42a1a00-b70a-11ea-9067-1ac7dbcaa94d.png">

I'm not sure if that's worth it for the inconsistency with other form field elements, and the possible confusion with disabled states.  Would be curious your feeling whether its better or worse...

**Comment by andrew-frueh** [comment]
On second though, I think adding the fill is worse.  But still curious your opinion.

**Comment by corykon** [comment]
I don't hate the fill, but it's gotta be oh-so-light to avoid looking disabled. Something like #f8fafc. If we went that route on checkbox & radios, I'd probably feel the need to have it on all our controls. 

If you look at Github's search input up top on the [issues page](https://github.com/HealthCatalyst/Fabric.Cashmere/issues), it has a light gray background, and then on focus it goes totally white with a lit up border. (I kind of feel like their gray is looking too dark on my screen, though...)

Overall I think I lean against adding the fill. Might help a bit in some cases, but it depends very much on context. If the controls are sitting on one of our fairly standard gray backgrounds like #f0f3f6, then white probably actually offers you more contrast.
