### ISSUE TITLE
Popovers introduce extreme lag on keyboard input

### ISSUE THREAD

**Issue by isaaclyman** [HealthCatalyst/Fabric.Cashmere#1213]
Stackblitz link: https://stackblitz.com/edit/angular-a37cc3

The above app is a simple hc-table with 200 rows and a popover button in each row. Under normal usage it performs very well. But observe the following:

- hover the mouse across several rows to see the "row hover" effect
- while doing this, type a few keys on the keyboard
- observe that the whole process grinds to a halt for a second or longer

This is probably because of the very hefty `'window:keydown'` HostListener on HcPopoverAnchorDirective.

![image](https://user-images.githubusercontent.com/9139369/77801886-5b958e80-703f-11ea-9654-5c88e1540020.png)

On a single isolated popover, it's no big deal. But on a page full of popovers (even simple tooltips), it slows down all typing everywhere, making the app almost unusable in some circumstances.

If the code in question is non-negotiable and can't be sped up, perhaps we should include a parameter on hcPop to prevent this listener from being registered when performance is a concern.

**Comment by joeskeen** [comment]
Would it be possible to listen to keydown on the focused element, rather than the whole window?  I know that makes the code more complicated (I just finished writing a component that was very focus-centric and it was a beast), but I think it would lead to much better performance.

**Comment by isaaclyman** [comment]
If you don't use the `window:` prefix, I know the default behavior is to only listen to events on the current component. We might have to mess around a bit to figure out what works though.

**Comment by joeskeen** [comment]
Or even doing something like this 
```js
[...menuItems /* including submenu items */, elementRef].map(e => fromEvent(e, 'keydown'))
  .subscribe(...)
```

**Comment by joeskeen** [comment]
That way none of the non-focused components will be listening to the keydown and thus it won't matter whether you have 1 or 1 million of them, should result in the same number of listeners.

**Comment by isaaclyman** [comment]
`merge` and `fromEvent` are new to me, but assuming it works it seems like a really great solution. 👍
