### ISSUE TITLE
Dropdown Label

### ISSUE THREAD

**Issue by andrew-frueh** [HealthCatalyst/Fabric.Cashmere#122]
We currently have `<hc-select>` for dropdowns that use the native browser select (typically used on settings or configuration pages).  We also have the ability to tie a popover to `<hc-button>` for things like options menus.  But somewhere in between the two, there is a component that is used in a number of our apps, usually up in `<hc-subheader>`.  I'm suggesting we call it `<hc-dropdown-label>`, but only because I can't think of anything better - I'm completely open to ideas.

This component functions like a button in that it triggers a popover, but when a selection is made from the popover, it changes the label accordingly.  The text is regular for the label name, and semibold for the label selection.  And there is a font awesome down chevron indicating the dropdown as seen elsewhere in Cashmere.

<img width="369" alt="dropdownlabel" src="https://user-images.githubusercontent.com/22795893/36181302-7f4a6dd8-10e1-11e8-9f8d-cdaaf5e45073.png">

**Comment by andrew-frueh** [comment]
@jtrujill @corykon @jacquie @benjanderson - I'm interested in giving this one a go.  Any issues with this being a new component?  Thinking it would be called `hc-dropdown-label` and would take four inputs:
1. Label
2. Value
3. Value Description (optional - the text that would appear in parens after the value)
4. Popover (link to the popover that it would trigger)

**Comment by jtrujill** [comment]
What's the difference between this component you're wanting and hc-select? This looks like it's only a style change. Hc-select is using the native select but we need to move that to our own component for multiple reasons. One reason I can think of is that you can only use text in the option element. 

Creating our own element will take some work since we'll need to be able to highlight elements in the list that match what the user types. This can be done later since I don't feel it's the most pressing

**Comment by jtrujill** [comment]
I'm against having two select like components and if the only thing different is styling than it should only be a style change

**Comment by andrew-frueh** [comment]
I agree with you in principle @jtrujill about having two components that serve the same purpose.  But in this case, this element is distinct from how `hc-select` is used.  This is more general purpose - it can can trigger a list of options, or it can trigger a date picker, or a set of input boxes for a value range, etc.  Basically anything that can go into a popover (see attached for an example).

It actually has more in common with `hc-button` in that respect than `hc-select`.  And it really could be just another style on `hc-button` if that's the route we wanted to go.  I was just a little concerned that `hc-button` was getting kind of overloaded.

<img width="425" alt="screen shot 2018-08-14 at 10 22 47 pm" src="https://user-images.githubusercontent.com/22795893/44131589-4761a07a-a011-11e8-8a48-aa7ae5ae4745.png">

**Comment by jtrujill** [comment]
I'll be tackling the select element this week and could move on to implementing a datepicker. @andrew-frueh I'll be in the office tomorrow and we could go over this in-person

**Comment by andrew-frueh** [comment]
`hc-form-field` could be a possibility.  The way we've seen this element used most though hasn't been as a part of "forms" - that's usually more the domain of the `hc-select`, `hc-input`, etc as you said.  This one gets used most often up in a subnav when it performs quick filtering either in a case where a complete filter drawer isn't needed, or there are one or more elements that make sense to segment from the filters.  It also tends not to have validation and error states the way that other form-field elements would.  So I'm not sure it's a perfect fit for form-field - that's why I was thinking it might be closer to a button.

**Comment by andrew-frueh** [comment]
Sounds good on the date-picker.  Let's definitely discuss.  @twaldron already has one built that he's using in Patient Safety following the look in the style guide, and we were thinking that would be a good starting point for a component.  So maybe we can get his code and you could work on componentizing it?

**Comment by jtrujill** [comment]
It might be easier to just do things from the ground-up. There will most likely need to be a lot of modifications but I could definitely use the css as a reference. Also I'd like to have a discussion about the general look and what features are necessary for this datepicker. I'll revitalize that issue and see if I can get some consensus

**Comment by andrew-frueh** [comment]
Probably true about building from the ground up, but yes, let's try and see what we can borrow from the styling.  And I'll be interested in that discussion about features needed in the date picker.  I'm not sure how many build have built them - I think only Leading Wisely and Patient Safety, but there may be others.  It's in the style guide, but I've never really spec'd it out - so yes, let's move the conversation over to that issue, and I'll try and solicit so input on the Slack channel too.

**Comment by andrew-frueh** [comment]
Well I'm all for compromise @jtrujill - and in this case I realized I didn't need a whole new button style; I could actually piggyback off of our "link" style.  By adding two classes to that style, it gets me everything I needed.  And now when folks see this component in their prototypes, I can point them to the example I added so these "dropdown labels" look consistent across our apps.
