### ISSUE TITLE
Echarts Theme

### ISSUE THREAD

**Issue by corykon** [HealthCatalyst/Fabric.Cashmere#1236]
Since so many teams are using echarts, might be nice to have a shared theme.

This might be a good place to start: https://www.echartsjs.com/theme-builder/
(In Chinese, but Chrome does a decent job of translating.)

**Comment by sheaivey** [comment]
Just adding a note here to remind my self to look into adding some docs once I consolidate some info on Apache ECharts.

New theme Builder: https://echarts.apache.org/en/theme-builder.html

**Comment by sheaivey** [comment]
Just to follow up the "new theme builder" linked in the previous comment is not new and only works for v4.x Apache eCharts. Unfortunately there was not one for the latest version.

I have created HealthCatalyst light/dark themes for 4.x and 5.x. I'm going to attempt to attach them here for reference along with some screen grabs for a example report dashboard. 

<img src="https://user-images.githubusercontent.com/3945263/217679214-5e7c6401-53e0-4d9a-a665-f3b1d7f6a302.png" width="250" /> <img src="https://user-images.githubusercontent.com/3945263/217679216-a4c7f9cc-afc3-4b0a-b7db-de0cf0cd7b0e.png" width="250" />

**v5.x HealthCatalyst Apache eChart Themes**
[HealthCatalyst-light-echart-v5.x.project.txt](https://github.com/HealthCatalyst/Fabric.Cashmere/files/10690926/HealthCatalyst-light-echart-v5.x.project.txt)
[HealthCatalyst-dark-echart-v5.x.project.txt](https://github.com/HealthCatalyst/Fabric.Cashmere/files/10690924/HealthCatalyst-dark-echart-v5.x.project.txt)

**v4.x HealthCatalyst Apache eChart Themes**
[HealthCatalyst-light-echart-v4.x.project.txt](https://github.com/HealthCatalyst/Fabric.Cashmere/files/10690925/HealthCatalyst-light-echart-v4.x.project.txt)
[HealthCatalyst-dark-echart-v4.x.project.txt](https://github.com/HealthCatalyst/Fabric.Cashmere/files/10690923/HealthCatalyst-dark-echart-v4.x.project.txt)

_The above text files are json safe._

**Comment by andrew-frueh** [comment]
@sheaivey the themes look absolutely incredible!  Amazing work.  Excited to review all this on Monday and get it all added to the site/library formally.
