### ISSUE TITLE
Calendar Date Picker locks me from picking the next month of data

### ISSUE THREAD

**Issue by mikebuck** [HealthCatalyst/Fabric.Cashmere#1244]
I ran a report for March then wanted to switch it to April but the controls blocked me. This needs to throw in an error in red at Apply time rather than locking the calendar browsing arrows.

![image](https://user-images.githubusercontent.com/29393477/80844065-0a8b3400-8bc3-11ea-9ba7-5887967175a1.png)

**Comment by andrew-frueh** [comment]
Thanks @mikebuck - as per our discussion, my recommendation is that we adjust the datepicker so it doesn't block the user from selecting any dates (even if the start date is after the end date), and then we make that a validation step for when apply is selected.
