### ISSUE TITLE
enhance breadcrumbs to support dynamic creation

### ISSUE THREAD

**Issue by benjanderson** [HealthCatalyst/Fabric.Cashmere#125]
Currently the bread crumbs component reads the routes to build itself. This works for a simple site, but most sites including Atlas will need the ability to have the breadcrumbs built dynamically. 

As an example, atlas uses metadata to build its routes/breadcrumbs. This is something we need supported
![image](https://user-images.githubusercontent.com/1934453/36222908-03eb7a20-1180-11e8-8c8c-41def6c2d06a.png)

**Comment by andrew-frueh** [comment]
Thanks for adding this @benjanderson - looking forward to seeing what the solution for this looks like.

**Comment by andrew-frueh** [comment]
@joeskeen and @nickrflynn - Ben sort of volunteered you for this one today :-)  So I'm putting you down as assignees because the Atlas team already experience with this.  Let me know if you don't think you'll have time to work on it in the next couple weeks.
