### ISSUE TITLE
Angular 9/10 Upgrade

### ISSUE THREAD

**Issue by andrew-frueh** [HealthCatalyst/Fabric.Cashmere#1255]
Upgrade Cashmere to Angular 9.

Long-term support of Angular 8 [ends on Nov 28, 2020](https://angular.io/guide/releases#versioning).  So we should have Cashmere upgraded to version 9 by then.

We want to make sure and give app teams plenty of time to plan for this change.  So well in advance lets be sure and broadcast the coming change.

**Comment by joeskeen** [comment]
A Cashmere release targeting Angular 9 is scheduled to be released November 1, 2020.  The cadence for future Angular version updates is documented here: https://cashmere.healthcatalyst.net/guides/supported-angular-versions

**Comment by corykon** [comment]
I jumped the gun and did a trial run on upgrading to angular 9. See this PR for details on how to resolve some of the compatibility issues:
https://github.com/HealthCatalyst/Fabric.Cashmere/pull/1333
