### ISSUE TITLE
multi-select dropdown doesn't float above container when opened

### ISSUE THREAD

**Issue by Techgeekster** [HealthCatalyst/Fabric.Cashmere#1257]
**Summary**

If the multiselect is contained inside a div that has a set height and vertical scroll, it will force you to scroll down inside the container when the dropdown is opened instead of opening the dropdown on top of everything.

**Reproduction**

I couldn't make a stackblitz reproduction because it seems to be broken on the cashmere example site:

![image](https://user-images.githubusercontent.com/16390046/81874848-10c2ce00-953c-11ea-914b-37212c4ac2f4.png)

This is the dropdown while it's closed:
![image](https://user-images.githubusercontent.com/16390046/81874878-289a5200-953c-11ea-89fb-38486a106a53.png)

This is the dropdown once you open it
![image](https://user-images.githubusercontent.com/16390046/81874895-35b74100-953c-11ea-90f8-ef47ccb3eaa4.png)

You have to scroll down the main window to see the rest of the items:
![image](https://user-images.githubusercontent.com/16390046/81874922-48317a80-953c-11ea-983f-2d258476d40d.png)

This is is what we'd like to see (without the extra styling and checkboxes, that's leftover from when we created our own version)
![image](https://user-images.githubusercontent.com/16390046/81874972-6dbe8400-953c-11ea-92a5-f2cf5f39147d.png)

Their documentation states that it should appear above everything, so I'm thinking this is probably caused by a style:
https://ng-select.github.io/ng-select#/dropdown-position

**Comment by joeskeen** [comment]
Looking at the referenced documentation, it seems that when they say 'above', they mean 'a Y position less than the Y position of the drop-down', not 'the z-index is 100000000000000000000000'

**Comment by Techgeekster** [comment]
You are right, I inferred that incorrectly.  Still, this seems really clunky.  I'm working in our app to see if I can fix it, and I'll post here if I figure something out.

**Comment by corykon** [comment]
I ran into the same thing, @Techgeekster, and just ended up making sure that if I HAD to stick it in a scrollable container and couldn't use `overflow: visible`, I would place it somewhere where I knew it wouldn't be towards the bottom of a scrollable area.

The issue is that the dropdown is added to the DOM inside whatever context you stick the component, rather than being appended to the body and globally positioned. I'm not sure that is configurable, and if it's got to change we'd either need to fork their repo or get a PR into their repo.

**Comment by Techgeekster** [comment]
We are using several of these inside our modal, so it's not an option to place it at the top.
I wonder if it's something we can submit an issue to them about.  I don't know if they respond to those.

**Comment by corykon** [comment]
@Techgeekster 

ah look: https://ng-select.github.io/ng-select#/append-to-element
That's how you could solve the issue. I didn't see that before!

**Comment by Techgeekster** [comment]
Ooooh!  Good find!  I'll play with that!

**Comment by Techgeekster** [comment]
This is actually perfect. I think we should change this 'bug' into a task to update the documentation describing this fix since there are probably more than just me that are running into this issue.

**Comment by corykon** [comment]
I'd say maybe we include it in our example and add a comment. I can submit a PR for that.

I agree it seems like a pretty common case. Seem like it should be the default to append to the body IMO.

**Comment by Techgeekster** [comment]
I agree.
One thing we found, in our modal, the z-index on the ng-select isn't high enough, so we'll need to update that.  We see it appear behind the modal so the append is working, but we need to pull it forward.

**Comment by Techgeekster** [comment]
We used the following to override the style.

`.ng-dropdown-panel {
     z-index: 3000 !important
}`
