### ISSUE TITLE
"Report an Issue" in the standard help menu

### ISSUE THREAD

**Issue by cedar-ave** [HealthCatalyst/Fabric.Cashmere#1263]
Suggestion to add “Report an Issue” to the standard help menu. Based on internal discussion among PMs and users.

**Comment by corykon** [comment]
+1 on this from me! 

Curious where this new link would take you though. Maybe we could create a new area on HC Community that functions like Feature Requests page but for bugs. Either that, or just have users pile bugs into that same bucket.

**Comment by andrew-frueh** [comment]
@corykon - @cedar-ave actually reached out to me earlier on this, and the report an issue would actually link to HEAT, which is where we are currently collecting bug reports.  I'll call that out in the update to the docs.

**Comment by corykon** [comment]
ahh I had no idea. Are other NPI products currently using HEAT to collect bug reports from customers?
