### ISSUE TITLE
Checkbox hit area

### ISSUE THREAD

**Issue by andrew-frueh** [HealthCatalyst/Fabric.Cashmere#1264]
**Summary**

The same area that highlights a checkbox and changes the cursor to a pointer doesn't respond to clicks.

**Reproduction**

On the "Checkbox Align" example: https://cashmere.healthcatalyst.net/components/checkbox/examples

Hover above or below the actual checkbox.  The box will highlight, but if you click, it won't check.  However, if you click on the box itself, or within the text - the box will check.

**Additional context**

Likely just need to change which div is receiving the click event.

**Comment by corykon** [comment]
Looks like there's some dead area off to the right of the component where the checkbox lights up but clicking doesn't work.
![image](https://user-images.githubusercontent.com/12416432/86875408-a93e8000-c09f-11ea-9ade-e36a633b3534.png)
