### ISSUE TITLE
multiselect with hcCheckbox component doesn't always check/uncheck checkbox

### ISSUE THREAD

**Issue by Techgeekster** [HealthCatalyst/Fabric.Cashmere#1267]
**Summary**

I created a multi-select and customized the dropdown area with hc-checkboxes. However, sometimes when you click on the checkbox the checkbox doesn't 'check/uncheck' even though the data is being 'selected/unselected'.
I double checked with a normal input checkbox and it works as expected.

**Reproduction**

Steps to reproduce:

This is the code I'm using for our ng-select with hc-checkboxes:
```
<ng-select class="checkbox-dropdown"
        [items]="careTeamRoles$ | async"
        [multiple]="true"
        [closeOnSelect]="false"
        [searchable]="true"
        bindLabel="name"
        appendTo="body"
        placeholder="Select to add"
        [(ngModel)]="selectedCareTeamRoles"
        [ngModelOptions]="{ standalone: true }">
        <ng-template ng-option-tmp let-item="item" let-item$="item$" let-index="index">
          <hc-checkbox [ngModel]="item$.selected" [ngModelOptions]="{ standalone: true }">
            <span>{{ item.name }}</span>
          </hc-checkbox>
        </ng-template>
</ng-select>
```

![ng-select with hc-checkboxes](https://user-images.githubusercontent.com/16390046/82709733-7bf85880-9c3e-11ea-8c7c-8cb32d2b2fb8.gif)

You can replace the hc-checkbox with
`<input type="checkbox" [ngModel]="item$.selected" [ngModelOptions]="{ standalone: true }"/> {{item.name}}` 
to see how the checkbox should behave

![ng-select with normal checkboxes](https://user-images.githubusercontent.com/16390046/82709878-d42f5a80-9c3e-11ea-9622-0f631cd895c4.gif)

Also, if you check/uncheck and the checkbox doesn't update, then you close the dropdown and reopen it, the checkboxes will show correctly:

![reopening select](https://user-images.githubusercontent.com/16390046/82710232-a39bf080-9c3f-11ea-9468-b66975b65360.gif)

Here's the documentation for checkbox dropdown:
https://ng-select.github.io/ng-select#/multiselect-checkbox

**Comment by corykon** [comment]
@Techgeekster PR on the way, but here's a workaround:
```
.ng-dropdown-panel-items .hc-checkbox-content label {
    pointer-events: none;
}
```
