### ISSUE TITLE
DateRange component makes you click a Start date twice when you first open the control

### ISSUE THREAD

**Issue by mhollier** [HealthCatalyst/Fabric.Cashmere#1271]
The DateRange component makes you click a Start date twice when you first open the control. This can be observed in the examples [https://cashmere.healthcatalyst.net/components/date-range/examples](https://cashmere.healthcatalyst.net/components/date-range/examples).

**Comment by andrew-frueh** [comment]
Yup, good catch @mhollier - I've noticed this one too and a fix didn't immediately jump out at me.  Wasn't sure if it was just on my computer or if others were getting it too.  Definitely an annoyance that should be fixed.
