### ISSUE TITLE
Unable to select same date on date range component when the dates are already populated

### ISSUE THREAD

**Issue by jonest** [HealthCatalyst/Fabric.Cashmere#1288]
If the start and end date on the date range picker are already populated, you're unable to select the same date. Just look at the stack blitz here: https://stackblitz.com/run?file=src/app/date-range/date-range-example.component.html&hidedevtools=1

Try selecting the same date from the past e.g. if I try selecting June 2 for the start date, June 2 is disabled on the end date. If I instead leave them blank, I can select the same date.

Blank by default:
![date-range-same-date-bug](https://user-images.githubusercontent.com/3075414/84815522-63c2f180-afd0-11ea-9327-44af04f64ab7.gif)

Pre-populated by default:
![date-range-same-date-bug-pre-populated](https://user-images.githubusercontent.com/3075414/84815674-9a990780-afd0-11ea-9b24-b065099c9432.gif)

**Comment by corykon** [comment]
Fixed by PR #1286
