### ISSUE TITLE
Navbar Styles Update

### ISSUE THREAD

**Issue by andrew-frueh** [HealthCatalyst/Fabric.Cashmere#1314]
Need some updates to the navbar styles to handle the usage in the screenshot below.  Need the following updates

- Less padding if no navbar logo is included
- An expandable icon container if it's wider than the usual 55px
- Navbar links that can display a dropdown indicator

![Main](https://user-images.githubusercontent.com/22795893/86407418-3df54800-bc72-11ea-9552-c9b9552e69f6.png)

**Comment by isaaclyman** [comment]
Related: https://github.com/HealthCatalyst/Fabric.Cashmere/issues/1298
