### ISSUE TITLE
"disabled" coding inconsistent in button section

### ISSUE THREAD

**Issue by cedar-ave** [HealthCatalyst/Fabric.Cashmere#133]
Not a programmer here but noticed disabled="false" or "true" is treated three different ways in each of these three snippets under "Buttons" - for less adept people like me, things like this can be confusing
![2018-02-17 10_43_13-cashmere](https://user-images.githubusercontent.com/15255009/36343922-fa77890a-13cf-11e8-9e8e-41e76026ab5b.png)
Unless it is supposed to be this way, then never mind.

**Comment by andrew-frueh** [comment]
This is why I'm so happy you're getting involved in this project, @cedar-ave!  Very glad to have your eyes on stuff like this.  The correct syntax includes quotes, so `disabled="false"`.

Have you worked with GitHub projects before?  I know this is a super small thing, but this would be a perfect opportunity to create a fork for yourself, get familiar with how the project is structured, and submit a pull request.  @corytak pointed me to [this awesome guide](https://gist.github.com/Chaser324/ce0505fbed06b947d962) about contributing to GitHub projects if you're looking for a primer - I found it incredibly helpful.  Don't hesitate to ping me if you have any questions.

**Comment by cedar-ave** [comment]
Thanks for the link @andrew-frueh @corytak - very clear and helpful. Does a PR need to be tied to an issue or project card? For example if I see something like this in the future do I just fix it and say what I changed in the PR or should I create an issue and then connect it to the PR?

**Comment by andrew-frueh** [comment]
You can just go ahead and submit the PR and mention what you did in there - no requirement to create an issue.  But if you notice bigger things that you don't think you'll have the time to work on, that's where you can create an issue so we can discuss it and someone else can pick it up.

**Comment by jtrujill** [comment]
This has been fixed
