### ISSUE TITLE
AM/PM does not automatically switch when changing time

### ISSUE THREAD

**Issue by jonest** [HealthCatalyst/Fabric.Cashmere#1338]
Not so much a bug as some behavior that some users are finding to be unexpected:

> Wanted to report a bug in scheduling within Ops Console. When you click the down arrow on the time it should automatically change from PM to AM, it does not do this though. In my example if I have it set to 12:30 PM and want it to run an hour earlier, I should be able to just click the down arrow on the hour and it would resolve to 11:30 AM. Current functionality is that it would resolve to 11:30 PM (11 hours later)... [Version DOS 20.2]

![image](https://user-images.githubusercontent.com/3075414/88210288-2e35a780-cc11-11ea-8ab8-fa407f423f59.png)

**Comment by andrew-frueh** [comment]
Nice suggestion @jonest - definitely better UX to have the buttons work as you described.

**Comment by jonest** [comment]
I'll pass the kind words onto the person that suggested it ;) I'm merely the messenger :)
