### ISSUE TITLE
DateRange throws ExpressionChangedAfterItHasBeenCheckedError

### ISSUE THREAD

**Issue by mhollier** [HealthCatalyst/Fabric.Cashmere#1354]
**Summary**

The DateRange component is throwing an ExpressionChangedAfterItHasBeenCheckedError.

**Reproduction**

Steps to reproduce:

1. Navigate to https://cashmere.healthcatalyst.net/components/date-range/examples
2. Hit F12 to display the Console
3. Click the caret to display the date range drop-down. 

**Additional context**

![image](https://user-images.githubusercontent.com/12176013/88947300-fb656200-d255-11ea-96fd-9459756e4631.png)

**Comment by andrew-frueh** [comment]
Ugh - thought we found all of these.  Good catch @mhollier - I'll see if someone from the Neumont team can check this out today.
