### ISSUE TITLE
Tooltip stays open on scroll

### ISSUE THREAD

**Issue by corykon** [HealthCatalyst/Fabric.Cashmere#1371]
Within a scrollable div, tooltips stay open when you scroll away.

![cashmere-tooltip-bug](https://user-images.githubusercontent.com/12416432/90271799-9c891680-de19-11ea-9a8e-e57dc2540e52.gif)

**Comment by andrew-frueh** [comment]
@corykon - lets discuss this for a minute in our 1:1 on Thursday.  I noticed when I was doing those recent popover fixes that our scroll strategy on popovers might not be working exactly as expected.  Or maybe it is.  Want to take a look at that together and decide what we think the intended behavior should be.

**Comment by andrew-frueh** [comment]
@corykon - I think this issue might be resolved now?  Probably something that came along for the ride in one of our Angular upgrades or another fix.  Check the Stackblitz below, but I think it accurately recreates the parameters for the issue, and the tooltip disappears as expected:
https://stackblitz.com/edit/angular-fucaxv

**Comment by corykon** [comment]
I'm still seeing it. Does go away when you move the mouse again.
![repro](https://user-images.githubusercontent.com/12416432/228655192-02c206a4-bd7c-4ab6-85b3-d7b4ef31235f.gif)

**Comment by andrew-frueh** [comment]
Interesting!  That's a Chrome/Firefox difference.  It works as expected in Firefox, but I just tested Chrome and I'm seeing the same thing you are.
