### ISSUE TITLE
Timeout - Style page

### ISSUE THREAD

**Issue by andrew-frueh** [HealthCatalyst/Fabric.Cashmere#1421]
**Describe your idea**

As reported by Keith on the Slack channel, several apps include timeout pages that are being styled differently. The Cashmere spec should define a standard that apps can follow.  Much like the login spec, this would live in the Styles section under "user interface"

**Additional context**

Examples of different timeout page styling below:
![image (20)](https://user-images.githubusercontent.com/22795893/96921491-d86cd780-146b-11eb-9afe-787259e7ff8f.png)
![image (19)](https://user-images.githubusercontent.com/22795893/96921493-d9056e00-146b-11eb-8ee9-ad753ba30745.png)

**Comment by corykon** [comment]
Pop Analyzer and Pop Insights are mostly consistent, but I'm seeing some other stuff in the wild

![image](https://user-images.githubusercontent.com/12416432/154545080-f301586e-d95c-4479-b21f-f9629a9d30c8.png)
