### ISSUE TITLE
Brand logo doesn't have cursor: pointer when homeUri exists

### ISSUE THREAD

**Issue by Techgeekster** [HealthCatalyst/Fabric.Cashmere#1430]
**Summary**

When the navbar brand logo has a homeUri, the cursor isn't set to pointer.

**Reproduction**

Steps to reproduce:

![cursor bug](https://user-images.githubusercontent.com/16390046/97757902-60359000-1ac3-11eb-9138-f1662b3d79a7.gif)

**Comment by andrew-frueh** [comment]
Thanks for assigning yourself to this one @Techgeekster - appreciate it!
