### ISSUE TITLE
Add bullets to typography guidelines

### ISSUE THREAD

**Issue by cedar-ave** [HealthCatalyst/Fabric.Cashmere#144]
This would be helpful for web documentation. This is an example of a use case for three levels of bullets. In current state it doesn't look great.

![2018-02-22 16_31_25-set up the workspace _ articles](https://user-images.githubusercontent.com/15255009/36570264-7cdf03d8-17ee-11e8-8ba5-e3591b387ace.png)

**Comment by andrew-frueh** [comment]
Great suggestion @cedar-ave, I hadn't even thought of this before.  For something like this, I'd trust your recommendation more than I would my own.  Do you have a suggestion for the best way to present nested bullets?  Particularly in a way that would work best for the documentation you're doing.  And if so, maybe add it as an additional tile on [this page](https://github.com/HealthCatalyst/Fabric.Cashmere/blob/master/docs/app/styles/typography/typography-demo.component.html). 

Then point me to the branch of your fork with the change.  Once I see what you've got, I can help you out translating your recommendation into matching styles for our _typography.scss file.  And then we submit all that as one pull request.  Sound good?

**Comment by cedar-ave** [comment]
Sounds good, thanks. I'll give it a shot. After looking around briefly, not many living style guides have typographical list components, especially with nested lists. But this one seems like a potential one for us  to model after: [http://carbondesignsystem.com/components/list/code](http://carbondesignsystem.com/components/list/code). I'll pursue something like that unless anyone feels differently.
Ultimately I like this look (with potentially another `–` or a `>` for third level)
![2018-02-28 09_51_38-cap install guide pdf](https://user-images.githubusercontent.com/15255009/36800629-3320c5fa-1c6d-11e8-8f37-494ebe666f7d.png)
(this is from my PDF documentation)
Also, like you did on the help modal thread, I'm going to tip off Knowledge Dev on this discussion - their two cents on decisions like this that affect web documentation would be valuable.

**Comment by cedar-ave** [comment]
FYI @aflanders

**Comment by aflanders** [comment]
@cedar-ave The HC Word template uses a smaller dash for the third level of bullet.
<img width="171" alt="bullets" src="https://user-images.githubusercontent.com/36929945/36802889-5a5aa676-1c73-11e8-8d68-2f4bf15ca1b1.PNG">
https://spark.healthcatalyst.com/docs/DOC-4201

**Comment by SherriVance** [comment]
I believe the first level of secondary bullet is em dash, second is en dash

**Comment by cedar-ave** [comment]
Can we live with this? If so I will finish the work on the fork
![2018-03-06 10_17_43-microsoft edge](https://user-images.githubusercontent.com/15255009/37047333-cd8f9724-2127-11e8-8688-19eb4e81c6fd.png)

**Comment by aflanders** [comment]
Looks good to me.

**Comment by cedar-ave** [comment]
@andrew-frueh Here is my fork https://github.com/cedar-ave/Fabric.Cashmere/tree/lists
I put the HTML in an "article" div because I'm wondering if documentation should have its own styles in some cases. It seems like there may be other contexts for lists that this may not be ideal for. 
It certainly needs review/improvement and I would be interested to pair program with you on this sometime if you get a free minute. Thank you!
