### ISSUE TITLE
Sort icons disappear if using [innerHTML] instead of {{ data.label }}

### ISSUE THREAD

**Issue by pslyman** [HealthCatalyst/Fabric.Cashmere#1441]
**Summary**

Sorting icons do not appear or become usable if the header relies on [innerHTML] instead of {{ data.header }}.
This is needed when a header requires `<em>`, `<strong>`, or `<br />` (for a double lined text). [innerHTML] will accept those tags, while {{ data.header }} will display the tags as strings (example: "`first row header<br />second row header`")

**Reproduction**

Steps to reproduce:

When using sorting headers, this works: 
`<th hc-header-cell *hcHeaderCellDef hc-sort-header>{{ data[key].label}}</th>`

But not this:
` <th hc-header-cell *hcHeaderCellDef hc-sort-header [innerHTML]="data[key].label"></th>`

**Comment by isaaclyman** [comment]
`[innerHTML]` literally replaces the HTML contents of the element with whatever you pass in, which would overwrite the sort icon. I kind of doubt it's even possible to fix that behavior.

**Comment by isaaclyman** [comment]
Here's a workaround I just thought of:
    
    <th hc-header-cell *hcHeaderCellDef hc-sort-header> 
      <div [innerHTML]="data[key].label"></div>
    </th>

**Comment by pslyman** [comment]
I was just going to suggest the same thing. I'll test that real quick and let you know if it works.

**Comment by pslyman** [comment]
Alright, good call. I jumped the gun on this one. Works great with a `<span>` in there. This can be closed.
Thanks!
