### ISSUE TITLE
Migrate from Travis to Azure Pipelines

### ISSUE THREAD

**Issue by andrew-frueh** [HealthCatalyst/Fabric.Cashmere#1458]
**Summary**

Travis is switching to a pay model, apparently crypto miners have been abusing their service and so they're no longer able to support open source projects for free.  We've been grandfathered in a plan on a super low service tier, and as a result it's taking hours and hours for every build to get into the queue.  And I'm pretty sure we'll hit a point where we've used up all our free hours and service will stop entirely.

So we need to figure out what to do with our pipeline.  Either we find a way to get funds approved for Travis, or we switch to Azure Pipelines.  @Techgeekster was able to dig this up:

https://docs.microsoft.com/en-us/azure/devops/pipelines/get-started/?view=azure-devops

...and since Catalyst is already paying for Azure, I wonder if we might just need to make the switch.

For discussion at our next steering committee meeting.

**Comment by andrew-frueh** [comment]
@corykon found this to help us migrate our repo and buy some more time before a move to Azure:
https://docs.travis-ci.com/user/migrate/open-source-repository-migration

**Comment by corykon** [comment]
@joeskeen close this guy? Anything leftover?

**Comment by andrew-frueh** [comment]
Completed by @joeskeen
