### ISSUE TITLE
Update Getting Started for new dependencies

### ISSUE THREAD

**Issue by andrew-frueh** [HealthCatalyst/Fabric.Cashmere#1461]
**Where does our documentation fall short?**

The getting started doc needs to call out the current versions of the CDK and other dependencies for Cashmere 9.

**Comment by corykon** [comment]
Another note here - just got off a call with Matt where they needed to install hc-icons from https://cashmere.healthcatalyst.net/styles/icons to get the logo in the navbar working. 

Might be nice to mention installing that font as an optional step.

**Comment by andrew-frueh** [comment]
closed in #1490
