### ISSUE TITLE
Cashmere site doesn't load in IE

### ISSUE THREAD

**Issue by corykon** [HealthCatalyst/Fabric.Cashmere#1463]
Looks like it's choking on a syntax error on startup.

![image](https://user-images.githubusercontent.com/12416432/101816632-7da44380-3ade-11eb-9e68-8cfcae4c0717.png)

**Comment by corykon** [comment]
Spent a day on this and haven't found a good solution yet. Some notes below on what I've looked at so far.

--------------------------------
**Didn't work:**
- Updated polyfills.ts to include all of corejs, and added polyfills for web animations
- Changed target in every tsconfig file to "es5". We have 8 different tsconfig files that set a target version.
- Looked at setting up another ng serve configuration to specifically support older browsers [as suggested in the angular docs,](https://angular.io/guide/deployment#local-development-in-older-browsers) but we already are directly targeting es5 in our tsconfig files, so this wouldn't help us.
- Made sure browserslist files include IE 11. We have two browserslist files.
- Tried downgrading a few 3rd party packages to see if they happened to be using es2015 syntax, but haven't had any luck there.

**Did work:**
- Downgraded to angular 9.
But downgrading isn't really a viable option. Not sure what is about angular 9 that made things work better…

**References:**
- https://dev.to/coly010/angular-how-to-support-ie11-4924
- https://medium.com/better-programming/how-to-fix-your-angular-app-when-its-not-working-in-ie11-eb24cb6d9920
- https://angular.io/guide/browser-support
- https://angular.io/guide/deployment#local-development-in-older-browsers

**Comment by hassankhan986** [comment]
Also a few years back, @benjanderson , you checked in a fix for Cashmere demo to work on IE11, maybe you can give me some tips to solve the current issue - https://github.com/HealthCatalyst/Fabric.Cashmere/pull/610

Thanks

**Comment by benjanderson** [comment]
@hassankhan986 I dont have any insights.  I have not been active in Cashmere for over a year and half. I will have to defer to the others for the fix

**Comment by andrew-frueh** [comment]
closed in #1567
