### ISSUE TITLE
utils.parseBooleanAttribute causes error if null is passed to it.

### ISSUE THREAD

**Issue by jacquie** [HealthCatalyst/Fabric.Cashmere#1474]
**Summary**
utils.parseBooleanAttribute() does not take care of a null value being passed to it and will throw an error because it's trying to call `toLowerCase` on the null value.

**Comment by andrew-frueh** [comment]
Thanks for getting this reported @jacquie.  Since this is a pretty annoying issue, let's see if we can get this fixed when we release the Picklist update.  Do you think you could get a PR in for this by the end of next week (1/15)?
