### ISSUE TITLE
Button component ts error

### ISSUE THREAD

**Issue by jacquie** [HealthCatalyst/Fabric.Cashmere#148]
For me Typescript is complaining about line 36 in button/button.component.ts `[ts] Property '_color' has no initializer and is not definitely assigned in the constructor.`

I am still learning the nitty gritty of Typescript - get and set being one of the more nitty :)
I can see that the `@input` color set and get` manipulate _.color, but it doesn't look like typescript is happy with  `this.color = 'primary` in the constructor.

Would it work just as well if it said `this._color = 'primary'` in the constructor?  Typescript is certainly happier with that :)

**Comment by jtrujill** [comment]
There's a major difference between what the implementation does and what you're asking. 

`this._color = 'primary'` will only assign to the variable while `this.color = 'primary'` will call the setter which will set the appropriate class based on the color being passed in.

This sounds like an issue with maybe your environment. From what I've been able to read the thing that would cause this is a new feature introduced in typescript 2.7 called strictPropertyInitialization

We aren't using typescript 2.7 so this shouldn't effect us. Make sure that your IDE is picking up the correct typescript version. If this was an actual issue it shouldn't even build the project.

**Comment by jtrujill** [comment]
I'm going to close this since this is old and nothing new has been reported back. However, [this](http://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-7.html) under 'strict class initialization'  you'll see that this can be fixed when you have strict init enabled by using the following
```
class C {
    foo!: number;
    // ^
    // Notice this '!' modifier.
    // This is the "definite assignment assertion"

    constructor() {
        this.initialize();
    }

    initialize() {
        this.foo = 0;
    }
}
```
The exclamation point tells the compiler that it does get assigned to
