### ISSUE TITLE
App Switcher - fire output events when an application is selected

### ISSUE THREAD

**Issue by mhollier** [HealthCatalyst/Fabric.Cashmere#1535]
**Describe your idea**

It would be helpful to know what application a user has selected from the App Switcher. For example, in Operations Console, we would like to send an event to Application Insights for tracking.

**Comment by andrew-frueh** [comment]
Great suggestion @mhollier - and shouldn't be too hard to implement.  Could probably package this with another fix to app switcher that was on the list #1393
