### ISSUE TITLE
Safari Browser - Scrollbar for Drawer Appears Even Though Drawer is Closed 

### ISSUE THREAD

**Issue by JDavidStevens** [HealthCatalyst/Fabric.Cashmere#1559]
**Summary**

If `hc-drawer` has a scroll bar, the scroll bar appears on the page even when the drawer is closed. 
This only occurs with the Safari browser when 'Always' is selected as the 'Show scroll bars' preference' in the 'System Preferences' on a Mac.   

**Reproduction**
Using a Mac:
1. Select the apple icon in the upper-left of the home screen and choose 'System Preferences.' 
2. From the 'System Preferences' window select 'General.'
3. Under the 'Show scroll bars' section choose 'Always.'

Using Safari, navigate to a webpage that uses `hc-drawer.` Depending on the amount of content in the drawer it may be necessary to adjust the screen size so that a scroll bar appears. 

When the drawer is closed, the scrollbar will persist on the page. 

**Additional context**
Here is a redacted screenshot of the scroll bar appearing over the top of the second column in the table while the drawer to which the scroll bar belongs is closed:
![scroll-bar-issue-safari](https://user-images.githubusercontent.com/27790008/112219135-399b0180-8bea-11eb-928d-df0ce4fe8f0f.png)

**Comment by andrew-frueh** [comment]
@JDavidStevens - thanks for the live troubleshooting w/ James yesterday.  I've got a PR in if you want to validate that's the right fix from our discussion #1607 .  Also - I realized I couldn't add you as a reviewer b/c you aren't a collaborator on Cashmere - just sent you an invite, so keep an eye out for that.
