### ISSUE TITLE
Fix hanging indent for unordered list items in docs styling

### ISSUE THREAD

**Issue by heathkat** [HealthCatalyst/Fabric.Cashmere#1571]
In Cashmere docs, unordered list items do not have a hanging indent like ordered list items do. This should be fixed in the style settings. 

![image](https://user-images.githubusercontent.com/3497714/113619552-5d147200-9616-11eb-97e1-c13a2f003a65.png)

**Comment by corykon** [comment]
...\Fabric.Cashmere\src\styles.scss has some styles for lists that should be tweaked.

The `<ul>` element should have its list-style set to "disc" instead of "disc inside", and the `<li>` elements should probably have about 20 px margin on the left.

**Comment by corykon** [comment]
... Didn't realize you were on this @heathkat, ignore my comment. Looks like Andrew already asked for a specific approach.
