### ISSUE TITLE
Disable responsive full screen modals

### ISSUE THREAD

**Issue by corinnen** [HealthCatalyst/Fabric.Cashmere#1578]
**Allow users to disable responsive full screen modals**

Include an optional parameter on ModalOptions (defaults to true) that will remove responsive classes from a modal if using auto, medium or larger modals.

Currently, responsive modals are designed 'mobile first.' If adding a responsive class to all modal classes, refactoring may be necessary to reverse the media queries.
Add usage docs in the Developer Guides.

**Comment by andrew-frueh** [comment]
Closed in #1629
