### ISSUE TITLE
Navbar Mobile Redesign

### ISSUE THREAD

**Issue by WistyDagel** [HealthCatalyst/Fabric.Cashmere#1581]
We should align the hamburger icon to the left-hand side of the navbar, center / left-lean the logo, and have additional options on the right-hand side of the navbar. 

Hopefully, this will improve the user experience for Cashmere mobile and align the library with more current mobile web-based trends. 

For better context, 

Our current mobile navbar: 
![image](https://user-images.githubusercontent.com/8591906/114089013-e4f6b800-9872-11eb-9bd4-4e78e3bd1f81.png)

Potential mobile navbar:
![image](https://user-images.githubusercontent.com/8591906/114209620-11b2da00-991c-11eb-903f-64160e49039f.png)
![image](https://user-images.githubusercontent.com/8591906/114089318-3bfc8d00-9873-11eb-94a8-3ded7dec0ebc.png)

**Comment by andrew-frueh** [comment]
@WistyDagel - thought a bit more on this one, and I think let's go with the left aligned logo, similar to the Material layout above.  I like that it gives more potential space to icons on the right, and also, if there's nothing on the right, I think it doesn't make the layout feel like something is missing (as it would if it was centered and nothing was on the right).  I think 25px padding-left between the logo and hamburger (as it is with the tri-flame) will work.  Let's start with that and see how it looks.
