### ISSUE TITLE
Table content is cut off on small screens 

### ISSUE THREAD

**Issue by WistyDagel** [HealthCatalyst/Fabric.Cashmere#1588]
Whenever viewing a table on mobile, the content will be cut off and will then need to be scrolled or turned horizontally in order to view the entirety of the table.

Steps to reproduce:

1. On mobile, click on the Components section on Cashmere.
2. Make your way to either the "Table" Component
3. You will then see the issue with the component being cut off.

For a picture reference: 
![image](https://user-images.githubusercontent.com/8591906/114239089-d37ce100-9942-11eb-8621-2726baf67ab6.png)

A potential fix could be shrinking down the width of the table content. 
Like this: 
![image](https://user-images.githubusercontent.com/8591906/114239172-f60efa00-9942-11eb-9c5c-be738b07f658.png)

**Comment by andrew-frueh** [comment]
closing for duplicate request in #1880
