### ISSUE TITLE
Application Switcher

### ISSUE THREAD

**Issue by andrew-frueh** [HealthCatalyst/Fabric.Cashmere#16]
Something that we've always envisioned since the earliest days of the standard header was an easy way to switch between Catalyst apps.

https://xd.adobe.com/view/44c796df-448a-4c78-8b03-d65bd8f39fa9/screen/6f63b4b6-c06f-4b62-afcf-4b961d0ba425/Home-App-Switcher

@benjanderson and the Atlas team have developed a solid version of this in their new release - but for this to really work, it's something that needs to be included in _every_ app.  So I'd like to make a strong recommendation for the Atlas team to turn their switcher into a Cashmere component.  Having this in the library will be a huge incentive for all the dev teams to download the package and incorporate this component into their project.

**Comment by benjanderson** [comment]
I am currently working on this, I will update this thread with progress and requests for feedback

**Comment by andrew-frueh** [comment]
@benjanderson as per our discussion today - feel free to close this issue and replace it with all the sub tasks you identify related to the navbar, and then we'll just label them as "navbar"

**Comment by jtrujill** [comment]
I missed the discussion on this. Is there a link on what was decided. I don't know the specifics but it might make more sense to give this it's own repo
