### ISSUE TITLE
Mobile Zooming on Inputs

### ISSUE THREAD

**Issue by cikeddy** [HealthCatalyst/Fabric.Cashmere#1602]
**Summary**

Currently our input form fields have a text size that is less than 16 px, which causes phones on iOS to zoom into the field when focused/clicked. We should probably set the text size to at least 16 px on mobile to fix this, but there are other possible solutions (see article in additional context section).

**Reproduction**

Steps to reproduce:

1. Navigate to Cashmere on an iPhone
2. Click any input field

Stackblitz reproduction (click the "Edit on Stackblitz" link on a component example and fork the template):

**Additional context**

Here's an article explaining this issue: https://www.warrenchandler.com/2019/04/02/stop-iphones-from-zooming-in-on-form-fields/

**Comment by corykon** [comment]
@cikeddy really good find - I’d always noticed the zoom thing on some form fields and not ever understood why, never looked into it. Avoiding that would be an awesome/easy win for mobile UX

**Comment by cikeddy** [comment]
@corykon totally! Picked this up in a UI course I've been doing...would've never thought about looking into it otherwise.

**Comment by andrew-frueh** [comment]
It's pretty tricky to get the component to only jump to the larger font size on mobile devices automatically.  We decided the best bet is to leave that to the developer.  However, to make that easier, I'd propose the following solution:

Add a new param called `fieldStyle` with values of either `normal`(default), `tight`, or `mobile`. We would keep the separate `tight` param as something deprecated for a few releases and just have it set the `style` param.  The `mobile` style will increase the font size of the component to 16px and adjust padding accordingly.
