### ISSUE TITLE
Should we introduce a localization/translation framework?

### ISSUE THREAD

**Issue by rustyswayne** [HealthCatalyst/Fabric.Cashmere#161]
Assuming Health Catalyst products will eventually be used outside the US it may be prudent to discuss integrating a ***very basic*** localization and translation framework sooner rather than later.

## Why now? ##

> The process retrofitting a solution after the fact can be really painful.
> -- <cite>Me</cite>

Essentially you wind up going through every bit of textual content, in every component and replace the explicit text with some sort of token/argument that is the key for some language specific dictionary value.

	 // cashmere-en-US.json
     {
 		"hello" : "Hello",
        "save" : "Save",
        "Username": "Username"
     }

     // cashmere-ex-MX.json
     {
	    "hello" : "Hola",
        "save" : "Salvar",
        "Username": "Nombre de usuario"
     }

Going back replacing the values for every title, label, button, error message is time consuming and it's almost a certainty that bits will be missed (like you forget a label text changes based on some state change).  There are also quite a few factors that seem insignificant on the surface but can get rather tricky like -

something is conditionally singular or plural -

    if (person.Count == 1) ? "Person" : "People";

or something needs to in the middle of a sentence -

    // You have 4 new notifications.
    "You have " + notification.Count  + " new notifications";

Certain components may eventually need to format numeric values.  

    // English => French
    100.00 == 100,00 

    // Money
    // $100.00  <- symbol first 
    // 100.00 kr.  <- symbol last

And then there are dates - not even going to start.

Having a framework in Cashmere will give teams working on dependent apps the *option* to utilize an existing (underlying) pattern rather than being potentially faced with the situation of having to address the problem individually. The former encourages contributions while the later could result in a version fragmentation/incompatibilities. 

I like the saying "Go ugly early" ... it's much easier to get a few people (at this point all contributors) used to the little nuances in the beginning than it is to convince a bunch of people it's in their benefit to change a lot later.

### Limited scope

**All text in shipped templates should be localized**

- Button text
- Labels
- Headlines and titles
- Generic error messages
- Notes
- Help text
- Tool tips

**It should be super easy to do simple textual translations.**  Even if we assume that foreseeable future implementations would be limited to English speaking countries like US, Canada and UK little nuisances like **color vs colour** can leave a user feeling like their sitting in a room with every hanging picture slightly crooked. 

**The solution should be able to provide for contextual translations**

- Pluralization 
- String concatenations (You have 3 new notifications) 
- Conditional (It's Monday have a great week **vs.** It's Friday have a great weekend).
- Date formats

**There needs to be a falls back to "in template" defaults** - If a translation is not found in the language file text content from the template is used.  This may prove to be the most common usage by individual apps. 

#### Language files

Consistent naming standard.  Generally file name provides some sort of context followed by a suffix which indicates language specifics:

     // Example maybe the Cashmere "generic" file for US English would be
     cashmere-en-US.json

     // Whereas the same file for UK english would be 
     cashmere-en-GB.json

Contents of language files can get pretty length and eventually become difficult to sift through.  Having sections within the language file is helpful.
      
      // cashmere-en-US.json
      {
		"actions" : {
			"save" : "Save",
			"add" : "Add",
			"delete" : "Delete",
			"open" : "Open"
		},
        "exceptions" : {
			"loginFailed" : "The username and password combination entered could not be validated."
		}
      }

Applications built on top of Cashmere should have the option of introducing their own language file(s) that can both extend and potentially override the Cashmere defaults.

     // Conceptual directory structure

     /locale
     /locale/cashmere-en-US.json
     /locale/cashmere-fr-FR.json
     /locale/app/cashmere-en-US.json (population builder cashmere overides)
     /locale/app/pb-en-US.json (population builder specific definitions)

Conceptual Population Builder file contents
  
    // contents of /locale/app/cashmere-en-US.json 
    {
       "actions" : {
         "delete" : "Remove"
       }
    }

    // contents of /locale/app/pb-en-US.json
    {
       "actions" : {
          "disable" : "Disable"
       },
       "registry" : {
         "createSam" : "Create HC SAM"
      }
    } 

Having individual files and a known (predictable) directory structure allows for building a specific language dictionary during the boot strap process where keys can be generated based on file name prefix (which could be omitted if it's 'cashmere').

Example:
      
	  // bootstrapper -> load common -> /locale/cashmere-en-US.json

      // dictionary contains 
      {
		"actions.save" : "Save",
		"actions.add" : "Add",
        "actions.delete" : "Delete",
	    "actions.open" : "Open",
        "exceptions.loginFailed" : "...."
      }

      // load overrides -> /locale/app/cashmere-en-US.json
     
      // dictionary contains 
      {
		"actions.save" : "Save",
		"actions.add" : "Add",
        "actions.delete" : "Remove",        <- overriden
	    "actions.open" : "Open",
        "exceptions.loginFailed" : "...."
      }
 
      // load app specific -> /locale/app/pb-en-US.json
     
      // dictionary contains 
      {
		"actions.save" : "Save",
		"actions.add" : "Add",
        "actions.delete" : "Remove",
	    "actions.open" : "Open",
        "exceptions.loginFailed" : "...."
        "pb.actions.disable": "Disable",
        "pb.registry.createSam": "Create HC SAM"
      }

This also allows for Cashmere to ship with standardize language files (in the project repo) which is great for maintaining consistency of multiple translations.  It allows for individual apps to quickly adjust and fill in where there are omissions.
 
### Punt (suggest excluding)  

- Non Latin character sets
- Regional specific formatting - e.g. currency symbol right vs. left, commas vs decimal points
- Ability to change localization configuration (change languages, formats).   

## Resources

There are a couple of videos on Pluralsight (but the one I saw in Angular was a bit old).

This project might be worth checking out:
[https://github.com/ngx-translate/core#installation](https://github.com/ngx-translate/core#installation)

**Comment by corytak** [comment]
It looks like the angular team has quite a toolbox to help with this effort:
https://angular.io/guide/i18n

You can even use the cli to generate a translation source file:
```
ng xi18n
```

**Comment by jtrujill** [comment]
This sounds out of scope of Cashmere and as corytak had pointed out there are many available solutions for this issue.
