### ISSUE TITLE
DATEPICKER - Cannot set MINUTES time to exactly '00' using the up/down arrows

### ISSUE THREAD

**Issue by Nnahrup** [HealthCatalyst/Fabric.Cashmere#1628]
**Summary**

On the DatePicker control, cannot set the MINUTES time to exactly '00' using the up/down arrows.  For example '3:00 PM'

**Reproduction**

![image](https://user-images.githubusercontent.com/32752184/119048213-2acb9380-b97c-11eb-8f6c-ad6523e31443.png)

**Comment by andrew-frueh** [comment]
Great catch @Nnahrup - should be an easy fix on this one.  We'll get it in the pipeline for early next week.
