### ISSUE TITLE
Tooltip Positioning gets stuck

### ISSUE THREAD

**Issue by corykon** [HealthCatalyst/Fabric.Cashmere#1647]
Tooltip positioning won't change from what it's initially set to unless you also change something else - like the popover trigger.

Repro video:
![tooltipIssue](https://user-images.githubusercontent.com/12416432/126221797-16f9b6f4-e9d3-482b-a68b-bec0a47c891e.gif)

**Comment by andrew-frueh** [comment]
I'll take this one @corykon while you're finishing up the build stuff
