### ISSUE TITLE
Guide for awesome favicons

### ISSUE THREAD

**Issue by corykon** [HealthCatalyst/Fabric.Cashmere#1657]
Working w/ PopInsights team, found this awesome generator that helps you set up some rock solid favicons. You give it a 260x260 .png and it spits out the markup and files you need.

This setup should give sharp looking icons on all kinds of platforms, including for mobile use cases where someone creates a shortcut icon on their home screen. The generator is here: https://realfavicongenerator.net/

![favicon-magic](https://user-images.githubusercontent.com/12416432/129412635-7011a8fd-15ae-41fc-9317-03db9cb3f6e7.gif)

-----------

**Comment by andrew-frueh** [comment]
This is the one I use every time I make favicons @corykon!  I agree, it's great
