### ISSUE TITLE
What up with the Noto Sans errors?

### ISSUE THREAD

**Issue by corykon** [HealthCatalyst/Fabric.Cashmere#1672]
Can these be avoided?
![image](https://user-images.githubusercontent.com/12416432/131155040-01b59cf4-d430-40c3-9f0a-8acc71fb2286.png)

**Comment by andrew-frueh** [comment]
Fix submitted to the `notosans-fontface` project:
https://github.com/GreatWizard/notosans-fontface/pull/14

Will update our version dependency when the NPM package is updated.
