### ISSUE TITLE
Responsive modals not working as expected

### ISSUE THREAD

**Issue by corinnen** [HealthCatalyst/Fabric.Cashmere#1678]
**Summary**
Responsive modals are not extending to full screen width as expected. This bug appears when upgrading from version 10.3.0 to 11.0.2.
![image](https://user-images.githubusercontent.com/42940112/135175992-165a7d4d-f018-4e5a-a48e-7c5568607dcb.png)

**Reproduction**

Steps to reproduce:

1. Go to the modal examples on cashmere and edit on stackblitz (or use link below). Remove most of the body content from one of the modals and then shrink your browser to less than 768px. The footer will be 100% width but the modal is not. 

https://stackblitz.com/edit/angular-kurc3o?file=src/app/modal-overview/modal-overview-example-modal.component.html

**Additional context**
Prior versions of cashmere have the modal size on the `div` outside of the modal component which is where the `width: 100%` should be but is now on the `hc-modal` element.
![image](https://user-images.githubusercontent.com/42940112/135177226-0b5f9f90-4a8f-465f-a856-3b80261f31c1.png)

I also noticed an extra margin if two buttons are not present in the footer. (I was able to remove margin but then have to remove the `position: fixed` on the footer)
![image](https://user-images.githubusercontent.com/42940112/135176388-c3397fa6-cdbe-43c4-ad5b-6cd780427bda.png)

_You can share screenshots, library versions, your web browser and version, or anything else that might be relevant._

**Comment by andrew-frueh** [comment]
Good call out @corinnen - I ran into this same issue with modals in the HAS app and @cikeddy and I ended up writing overrides to get around it.  So it needs to get fixed in the app.  I should have some time to check this out early next week.
