### ISSUE TITLE
Forms.scss

### ISSUE THREAD

**Issue by corykon** [HealthCatalyst/Fabric.Cashmere#168]
We should create a sass file with general styles for form elements, including things like:
- Borders (width, color, etc)
- Error/focus states
- Font sizes
- padding/spacing
- etc

Two reasons for this:
1. Some styles are shared across many form controls, and as such should be variablized for easier changes in the future
2. It would be nice to have styles available so that someone could have their forms look style guide approved even if they cannot use the official angular components.

**Comment by benjanderson** [comment]
This is big one, as there are many form styles within the demos themselves. Here are some of the examples I found:
Operations Console
![image](https://user-images.githubusercontent.com/1934453/37161217-50006f2a-22af-11e8-8494-210d25222987.png)

Care Administrator
![image](https://user-images.githubusercontent.com/1934453/37161257-67a4d60c-22af-11e8-929e-b5ba9754e2b3.png)

Atlas
![image](https://user-images.githubusercontent.com/1934453/37161284-75c94e34-22af-11e8-88f2-ca52779e5b41.png)

Some things I would like to add that should be included in a forms stylesheet
- vertical form (label above input)
- horizontal form (label left of the input)
- button placement (left or right)
- how to deal with checkbox/radio button (single and multiple)
- multi column forms (see operations console)
- validation summary
- responsive forms (support for multiple resolutions)
