### ISSUE TITLE
Disabled Ng-select looks enabled if you hover over it

### ISSUE THREAD

**Issue by corykon** [HealthCatalyst/Fabric.Cashmere#1699]
This ng-select is disabled, but doesn't look like it if you hover over it.
![ngSelectDisabledHover](https://user-images.githubusercontent.com/12416432/139930777-cf25a0e8-5367-4cbd-a4d1-e65e382d882a.gif)

Just need to add something like this to the ng-select theme:
```
ng-select.ng-select-disabled > .ng-select-container:hover {
    border-color: $slate-gray-300;
    background-color: $gray-200;
    cursor: not-allowed;
}
```

**Comment by andrew-frueh** [comment]
...and how about I take this one too @corykon.  I wasn't having any luck reproducing the error on #1673 so maybe you can take a look at that instead?
