### ISSUE TITLE
Convert all component documentation to markdown

### ISSUE THREAD

**Issue by andrew-frueh** [HealthCatalyst/Fabric.Cashmere#170]
For consistency - update the documentation tab on all of our existing components to use @benjanderson's markdown library.

**Comment by benjanderson** [comment]
How are we going to deal with tabbed documentation? We could either remove tabs, or I could attempt to make another cashmere flavored markdown addition to make tabs

**Comment by andrew-frueh** [comment]
Good question @benjanderson - I took a look at the documentation we currently have, and for the moment I think it's okay to just move the tabs into their own tiles.  We don't have enough pages with tabs that it's a big deal.  But most of our documentation pages only show HTML and don't include a typescript section, which would be really good to have tabs for.

So I'm thinking I'll submit a PR today that just converts the existing content to markdown without tabs.  And then I'll add an issue to add the markdown addition for tabs as you mentioned.  But it's not something urgent you need to worry about.
