### ISSUE TITLE
New component: Confirmation Modal

### ISSUE THREAD

**Issue by corykon** [HealthCatalyst/Fabric.Cashmere#1706]
Confirmation modals are super common in our apps. We already have generic modals, but we should set up a standard component specifically for this use case to make sure the confirmation experience is aligned.

Leading Wisely just made a nice confirmation modal component that we could port over:
![image](https://user-images.githubusercontent.com/12416432/140190806-c1f89ab0-cf3a-4099-a05e-cb32e6137c80.png)

![image](https://user-images.githubusercontent.com/12416432/140190961-9f225f42-413a-42f7-a003-69d0f0c1509e.png)

![image](https://user-images.githubusercontent.com/12416432/140190239-89a32bf1-d52b-47f8-8e0f-7d7135df3dde.png)

![image](https://user-images.githubusercontent.com/12416432/140190182-03c7fc7e-cded-4543-934e-61ddbd893038.png)

**Comment by corykon** [comment]
@andrew-frueh thoughts on the styles? Wondering if the spacing/sizing could be dialed in. Some cashmere and non-cashmere variations

![image](https://user-images.githubusercontent.com/12416432/140191981-2188fd87-be53-4aed-9c14-f9bc3e4fac08.png)
![image](https://user-images.githubusercontent.com/12416432/140191522-f9a73f7a-6ec8-49a4-88f8-6db8beef3022.png)
![image](https://user-images.githubusercontent.com/12416432/140191550-68a55ece-cc52-4b4e-8259-899c832af871.png)

On this one - don't like that the buttons are both blue, but love how minimalist it is. Rather than header and a message, sometimes just a one liner and the action buttons are enough.
![image](https://user-images.githubusercontent.com/12416432/140191731-79e0e01f-f8bd-4f69-b60c-01295b69fa49.png)

**Comment by corykon** [comment]
Note: 
- Option to have no header
- Double check styles work well for small screens

**Comment by andrew-frueh** [comment]
@corykon - if you end up building this one, make sure to include the FocusTrap enhancements/options just added to modal in #1747

**Comment by corykon** [comment]
Pick this up to work on now, for a CDP use case.
