### ISSUE TITLE
Cleanup documentation

### ISSUE THREAD

**Issue by benjanderson** [HealthCatalyst/Fabric.Cashmere#174]
The readme and contribution guide are out of date and have quite a few errors and need some general cleanup. Also, there are some topics that need their own guide like 
- Packaging the library
- Supported browsers

I have assigned myself but would love you to review my changes @cedar-ave

**Comment by cedar-ave** [comment]
Happy to do that @benjanderson

**Comment by benjanderson** [comment]
closed by #181
