### ISSUE TITLE
Make UI Colors the default page when clicking foundations?

### ISSUE THREAD

**Issue by corykon** [HealthCatalyst/Fabric.Cashmere#1748]
This is possibly a silly one... 

The number one thing I do when coming to cashmere is to look at the list of color variables. I do it several times a day. I go to cashmere home, click on "Foundations", then click on "UI Colors". Every time I do it I think "man we should default to UI colors instead of brand colors".

Could we make it so UI Colors is the default, save a click? I'm not sure what determines the order of those links... but if it's alphabetical sort, we could change to "Application UI Colors".

Maybe its just me, and maybe I should just bookmark the ui colors page. But we might be able to tweak this even faster that it took me to write this issue...

**Comment by andrew-frueh** [comment]
Hahaha - sure this makes sense to me.  I think most of our viewers on the Cashmere site are developers, so makes sense to prioritize that page.  I'll make that update in the PR I just submitted.
