### ISSUE TITLE
Toasts

### ISSUE THREAD

**Issue by corykon** [HealthCatalyst/Fabric.Cashmere#175]
We should standardize our toasts!

Lots of us are using something like https://www.npmjs.com/package/ng2-toastr, but I've run into some frustrating limitations. We could make something a little more flexible, and make sure it's styles are better aligned with catalyst colors/icons/etc.

Here's a screenshot of ng2-toastr along side what an hc-toast component might look like
![image](https://user-images.githubusercontent.com/12416432/37303442-14395ee6-25f4-11e8-90d4-44b126b22143.png)

Let me know what feedback you have!

**Comment by jtrujill** [comment]
@angular/cdk has been added to the library so we should use that to implement toasts. If you have any questions reach out to me
