### ISSUE TITLE
Constrained width tooltip looks busted

### ISSUE THREAD

**Issue by corykon** [HealthCatalyst/Fabric.Cashmere#1753]
Supposed to be limited to 400px.
![image](https://user-images.githubusercontent.com/12416432/144897837-fbc122ab-6daf-4587-b27e-4a546aa7163c.png)

**Comment by andrew-frueh** [comment]
Yep, confirmed, I'm seeing that in the popover overview example as well.  I can fix that this afternoon if you don't get to it first.
