### ISSUE TITLE
StackBlitz Broken in v12

### ISSUE THREAD

**Issue by andrew-frueh** [HealthCatalyst/Fabric.Cashmere#1757]
StackBlitz is saying `math.div` is an undefined function:

![Screen Shot 2021-12-07 at 7 50 00 PM](https://user-images.githubusercontent.com/22795893/145139773-ff8d7cb4-4980-4579-b67a-1ffca3883acf.png)

...also see this related error in the build process:

![Screen Shot 2021-12-07 at 7 49 28 PM](https://user-images.githubusercontent.com/22795893/145139797-c7cf881e-c4a2-4099-b35c-5c87d9dadf76.png)

**Comment by corykon** [comment]
That's crazy frustrating. Spent a couple hours trying different things.

The related warning you show is the reason I switched over to math.div(). You can see more on that here: https://sass-lang.com/documentation/breaking-changes/slash-div

I'm just switching back to using the division sign for now. It'll through warnings, but nothing that will break. We'll have to try again to migrate over to math.div with the angular 13 upgrade.

Another interesting read if curious, I believe we have a similar issue to this one :https://github.com/stackblitz/core/issues/1559.

My best hunch is that the ng-packager we use is an old version of sass, and we can't upgrade ng-packager to v13 until we're ready for angular v13.
