### ISSUE TITLE
404 & Other Error Pages

### ISSUE THREAD

**Issue by andrew-frueh** [HealthCatalyst/Fabric.Cashmere#176]
We've had a lot of requests from our various app teams on how to handle 404 or other error pages.  I'm thinking this would probably be a component because it has some specific formatting and would simplify displaying the error for developers.  But if a guide makes more sense that's fine too.  The image below shows the basic structure that can be extended to whatever the particular error is.

![404](https://user-images.githubusercontent.com/22795893/37305600-9b434284-25fa-11e8-96f9-f6bd1f57b7b6.png)

**Comment by benjanderson** [comment]
I would prefer a guide/css style as the most recent use case I had was when angular failed to initialize

**Comment by andrew-frueh** [comment]
Good point @benjanderson - that makes sense.  Will plan on making this as a guide with associated styles.
