### ISSUE TITLE
Style suggestion for "click to dismiss" toasts

### ISSUE THREAD

**Issue by corykon** [HealthCatalyst/Fabric.Cashmere#1761]
This came up in a convo with PopInsights team. They felt like the default icon on toasts clashes with message of the toast a bit. In this example here there's some dissonance - you might first think the "x" represents an error, because its white like the check icon and almost as prominent:
![image](https://user-images.githubusercontent.com/12416432/145620401-2703e088-67cf-4d9d-9d85-c04a5de83746.png)

Making it a darker color, and a little thinner helps.
![image](https://user-images.githubusercontent.com/12416432/145620118-c34502f4-266c-46ea-bcb5-4368a22c8a18.png)

And the PI team liked it top right instead of centered. Feels like a more familiar place for a close icon.
![image](https://user-images.githubusercontent.com/12416432/145620175-c9c041e3-bbc9-445c-921e-ede13d50823c.png)

**Comment by corykon** [comment]
@andrew-frueh thoughts on this?

**Comment by andrew-frueh** [comment]
@corykon could you spin up a quick usertesting.com test on this?  I'd be fine to back whatever design direction the data from that points us.

**Comment by corykon** [comment]
@andrew-frueh definitely. will report back :+1:

**Comment by corykon** [comment]
Fired up a couple A/B tests. Long story short is the results point to a dark icon that is centered.
![image](https://user-images.githubusercontent.com/12416432/145860962-26943cc8-a062-4881-b3a9-c6286753f51f.png)




----------------

Test 1: https://app.usertesting.com/workspaces/795220#!/study/3843207/metrics
_Here's the screen shown at the end of the test when asked to pick their fav (after being shown them individually)._
![toast-test-both](https://user-images.githubusercontent.com/12416432/145860129-207aaf7a-3d7f-400b-ad75-3d3fb11d6cb7.png)
![image](https://user-images.githubusercontent.com/12416432/145860211-e2f6c30c-c965-4128-9a9f-a4e078e75d93.png)
![image](https://user-images.githubusercontent.com/12416432/145860271-826e6230-fec8-4268-b225-beb5abe659c3.png)

-----------------
Test 2: https://app.usertesting.com/workspaces/795220#!/study/3843342/metrics
![toast-test2-both](https://user-images.githubusercontent.com/12416432/145860677-641846e6-df2d-4797-a69c-b18589e2e1a2.png)
![image](https://user-images.githubusercontent.com/12416432/145860449-5ab4a1fd-a605-4df1-8a90-9ab2ab50ed64.png)
![image](https://user-images.githubusercontent.com/12416432/145860771-c7e4a272-3569-4698-b936-98737213b7ff.png)

**Comment by andrew-frueh** [comment]
Thanks for doing this Cory - it looks like the dark/light versions are kind of a toss up.  But if we connect that to similar sentiments coming from you and the DOS app teams, it sounds like centered dark is the way to go. :+1:
