### ISSUE TITLE
Can feel a little lost in the new mobile dev guide 

### ISSUE THREAD

**Issue by corykon** [HealthCatalyst/Fabric.Cashmere#1764]
Noticed that its kind of hard to tell what this page is about when you land here.

If you look around real hard, like at the URL, some of the subtabs or in the block of text you'll eventually figure it out. It would be nice though if the header said Mobile Guidelines Overview or something. Maybe add a icon or an image somewhere that makes it clearer.
![image](https://user-images.githubusercontent.com/12416432/146085619-81ab1566-766a-4d41-a6b5-ae5f7a425fb3.png)

Thinking further... the suggestion above may not be enough. As I click around to other mobile guideline pages you have the same issue. No context (other then the url) that you are in the Mobile Guidelines section of Cashmere.

You could potentially have the same problem in the components/additional styles/guides sections... maybe we need some breadcrumbs somewhere?

**Comment by andrew-frueh** [comment]
Yup this is a great point - I think your concern is well founded here.  Any ideas on what/where to add to the UI to improve this?

**Comment by corykon** [comment]
I'll have to think on it more... first ideas that jump to mind:


Stick some kind of little header/breadcrumb thingy above the accordion nav:
![image](https://user-images.githubusercontent.com/12416432/146099098-9e21b09e-af14-42b3-b794-6a9f67c6a441.png)


Or follow lead of angular docs, have a multilevel accordion nav.
In this image below I'm on the Docs > Developer Guides > Routing and Navigation > Overview
![image](https://user-images.githubusercontent.com/12416432/146099229-1c8c3584-db5d-4b6f-a722-85ace98d050c.png)


The first option seems pretty simple, and we already _kinda_ do it on the Bits page.

**Comment by aaronbrethorst** [comment]
Option 1 definitely sounds like the easiest path forward to me, too.

**Comment by andrew-frueh** [comment]
Nice - agree w/ @aaronbrethorst that Option 1 is the way to go.  Just need to nail down the styling.  If either of you want to take a stab at it, please go for it.  Otherwise I can play around with it in January.

**Comment by corykon** [comment]
I was thinking something pretty dead simple. Just reuse the link name and icon from the dropdown. Thoughts on this?

![image](https://user-images.githubusercontent.com/12416432/146274655-32b12fa0-4a24-4031-aa2d-a72632ca37d6.png)
![image](https://user-images.githubusercontent.com/12416432/146274912-3c2818e9-d3df-4c8e-ad91-3c92f2ed639e.png)

**Comment by andrew-frueh** [comment]
Ah brilliant - love it.  Yes that's perfect because it doesn't take the emphasis off of the `h1` page title which is what I was most worried about.  So :+1: from me - let's go with your suggestion.

**Comment by aaronbrethorst** [comment]
@corykon 👏 👍
