### ISSUE TITLE
Date Range: emit event on cancel

### ISSUE THREAD

**Issue by jacquie** [HealthCatalyst/Fabric.Cashmere#1776]
On Pop Insights dashboards for performance reasons we want to suspend loading the dashboard data when the date range picker is opened.
Currently there is no way to know if the date range picker gets closed with the cancel button with no new date range picked and so in our case no way to let the component know to continue loading the dashboard data with the current date range.

It would be good if Cashmere could emit an event when the date range picker is canceled.

**Comment by andrew-frueh** [comment]
Hey @jacquie - how about a `closed` emitter that returns null on cancel or a `DateRange` on apply?  Would that work?
