### ISSUE TITLE
Tab Component - DefaultToFirstRoute not working with child routes

### ISSUE THREAD

**Issue by AdamGMiller** [HealthCatalyst/Fabric.Cashmere#178]
LeadingWisely had to remove the '/' after ${routerLink} in order to disable the routing to the first tab:
`return currentRoute === routerLink || currentRoute.indexOf(`${routerLink}/`) > -1;`

The tab component was in a module that was also a child route:
```
const routes: Routes = [
  {
    path: 'admin',
    loadChildren: 'app/admin/admin.module#AdminModule',
    /* TODO: Add AuthGuard */
    // canLoad: [AuthGuard]
  },
```

```
const adminRoutes: Routes = [
  {
    path: 'admin',
    component: AdminComponent,
    children: [
      // Config routing
      {
        path: 'config', component: ConfigListComponent
        , children: [{ path: 'admin/config/', component: ConfigEditComponent, outlet: 'modal' }]
      },
```
We may want to revisit how this method determines which route it's on and if it should route to the first tab.

**Comment by jtrujill** [comment]
@AdamGMiller Can you provide a demo of this issue so I have a better understanding of the issue exactly
