### ISSUE TITLE
Add banner for upcoming browser support change

### ISSUE THREAD

**Issue by corykon** [HealthCatalyst/Fabric.Cashmere#1786]
Decision has been made to drop support for Internet Explorer. This will happen in cashmere when we move to Angular v13 (#1714) in May, and then become official for Health Catalyst as a whole on June 15th, 2022. There is a blog post in the works where this will be formally announced, as well as some documentation/guidance for engineers on how to make the change.

![image](https://user-images.githubusercontent.com/12416432/149238248-e8268d8b-3028-4c7e-85ec-3b58b8656680.png)

Might be good to place a banner of some kind referring to this announcement ahead of time so that devs see it coming.
Could place that warning on the homepage and then possibly also something here: https://cashmere.healthcatalyst.net/web/guides/supported-browsers.

**Comment by aaronbrethorst** [comment]
🎉

**Comment by corykon** [comment]
After talking w/ @andrew-frueh, leaning against the banner. Feels like overkill. We'll just put something on the browser support page.
