### ISSUE TITLE
Create component(s) for browser support messaging

### ISSUE THREAD

**Issue by corykon** [HealthCatalyst/Fabric.Cashmere#1787]
In the next major release of Cashmere in May, we'll be dropping IE support. #1714 
We expect our apps to follow suit and drop support on June 15th 2022 (Microsoft's end-of-life date for IE).

**From ASAP until June 15th**
We need to make sure users of our applications are warned about this ahead of time. We should provide a component (or other package of code, doesn't have to be an angular component) that detects browser usage and warns the user to upgrade as needed. Just a dismissible banner or toast would probably be sufficient.

**After June 15th**
We'll need this component (or another) to detect IE and than display a message explaining that the browser is not compatible. Note - angular will not be able to load at this point, so the code needs to be able to run before angular initializes.

**Comment by corykon** [comment]
Here's what I've got mocked up for messaging before June 15th:
![image](https://user-images.githubusercontent.com/12416432/151055380-eaa9a619-ab94-45ac-8434-545ae7289dc2.png)


And for after June 15th, IE users will get this full page message:
![image](https://user-images.githubusercontent.com/12416432/151055347-4106e70b-df2c-43c2-bae5-7548c307952a.png)

Any feedback?

@andrew-frueh

**Comment by andrew-frueh** [comment]
Messaging and approach looks good @corykon.  For the error message, I wonder if it would look better if you get rid of the white padding at the top and just have the blue bar go right to the top of the container.
