### ISSUE TITLE
CoreJS versioning issue on cashmere 12 upgrade

### ISSUE THREAD

**Issue by corykon** [HealthCatalyst/Fabric.Cashmere#1798]
![image](https://user-images.githubusercontent.com/12416432/151271554-0a522fed-8944-466e-b77c-8155c3fc70fc.png)

**Comment by andrew-frueh** [comment]
@corykon - okay if I assign you to this one?

**Comment by jacquie** [comment]
What about the sass '/' deprecation part? I can create a separate issue for it if that works better.

**Comment by corykon** [comment]
> What about the sass '/' deprecation part? I can create a separate issue for it if that works better.

@jacquie, Yes! Haven't forgotten that. It's actually listed as an item over in #1714 
Forgot to note that here.

**Comment by jacquie** [comment]
@corykon Ah! Sounds good.
