### ISSUE TITLE
Date Range Component: Should be able to completely clear out date

### ISSUE THREAD

**Issue by corykon** [HealthCatalyst/Fabric.Cashmere#1833]
When start and end date are optional, it should be possible to clear both dates out and hit apply.

From Guillermo Gomez on Slack

> I got excited about the news of the new cashmere release so I was trying to test it in the docs...
> playing with it in Stackblitz it seems that even when I have both the start and end dates required option marked as false, when I clear the default dates, I get an error when trying to apply my changes (click on the Apply button).

![image](https://user-images.githubusercontent.com/12416432/158219821-f7b74c30-bcac-4a2e-82a9-c1639fcc416d.png)

@aaronbrethorst any interest in hopping into that code once more?

**Comment by aaronbrethorst** [comment]
@corykon sure! Happy to take this on. I’m traveling today, but can look at it tomorrow for sure.
