### ISSUE TITLE
Pagination Input/Output bindings

### ISSUE THREAD

**Issue by g33krock** [HealthCatalyst/Fabric.Cashmere#1867]
In the pagination documentation examples, the pageNumber property has input and output bindings.  It seems that this is no longer supported and tries treating the property like an event instead of a number (`Type 'Event' is not assignable to type 'number'`)
![image](https://user-images.githubusercontent.com/56360847/168163222-dd816e14-3200-439b-a77d-98ce8753848b.png)

**Comment by andrew-frueh** [comment]
Hey @g33krock - thanks for submitting the issue.  It should still be supported.  If you take a look at that "Pagination Simple" example you referenced on:

https://cashmere.healthcatalyst.net/web/components/pagination/examples

that `pageNumber` is a getter/setter that's updating a formControl when the output fires.  And looking at line 60 in [base-pagination.ts](https://github.com/HealthCatalyst/Fabric.Cashmere/blob/dev/projects/cashmere/src/lib/pagination/base-pagination.ts) the output type is `number`.

Can you take a look at the version of Cashmere you're on?  I'd have to go back and look if/when anything changed on this property.
