### ISSUE TITLE
Add instructions on what to import in documentation

### ISSUE THREAD

**Issue by benjanderson** [HealthCatalyst/Fabric.Cashmere#188]
Using Cashmere I have to look to the source code to know what to import to get full functionality. It should be documented what modules to import. This can easily be added at the bottom of each components documentation

For example if I want to use the `hc-input` directive from the [input demo](http://cashmere.healthcatalyst.net/components/input)
``` html
<form (ngSubmit)="onSubmit()">
    <label hc-label required="true">Validate an email address:</label>
    <div hcInputIcon>
        <input hc-input name="inputEmail" id="inputEmail" ngModel #inputEmail="ngModel" placeholder="search" width="250px" />
        <hc-icon fontSet="fa" fontIcon="fa-search" class="search-icon"></hc-icon>
    </div>
    <div class="form-errors" *ngIf="submitted && inputEmail.invalid">
        <div *ngIf="inputEmail.errors.required">
            Email address is required
        </div>
        <div *ngIf="!inputEmail.errors.required">
            Please enter a valid email address
        </div>
    </div>
    <br><br>
    <button hc-button title="Validate Input Text" color="primary" type="submit">Validate Input</button>
</form>
```

I would have to import the `hc-input` module like so
```
@NgModule({
  ...
  imports: [InputModule, ...],
  bootstrap: [AppComponent]
})
export class AppModule {}
```

I would also have to import the `LabelModule`, `IconModule`, and the `ButtonModule`. If we give an example of how a component works, we should give instructions on what modules are needed

**Comment by jtrujill** [comment]
This issue was solved with PR #331
