### ISSUE TITLE
Removable Tabs

### ISSUE THREAD

**Issue by HaydenDalley35** [HealthCatalyst/Fabric.Cashmere#1881]
**Describe your idea**
Update the tabs/tabset so that they can be removable. This would be optional Input for the tabset component. The removable tab would add the x icon to the tab and when the x icon is clicked it would emit a event with the index of the tab to remove.

**What problem are you trying to solve?**
Adding removable tabs.

**Additional context**

**Comment by andrew-frueh** [comment]
Similar use case to instance switcher - will hold for now to do see if this usage pattern for tabs surfaces in more places to implement it in the library (since it can be done with current functionality if needed)
