### ISSUE TITLE
hc-icon doesn't allow multiple classes

### ISSUE THREAD

**Issue by benjanderson** [HealthCatalyst/Fabric.Cashmere#189]
Font awesome has many examples on their site of how to combine classes to flip, combine, rotate, and stack icons by including multiple classes.
https://fontawesome.com/v4.7.0/examples/

This code will flip the icon 90 degrees
`<i class="fa fa-shield fa-rotate-90"></i> fa-rotate-90<br>`

I created a search textbox that I wanted a spinner on the right side
```
<div hcInputIcon>
  <input hc-input class="hc-input" [(ngModel)]="searchInput" (change)="change()">
  <hc-icon fontSet="fa" fontIcon="fa-spinner fa-pulse fa-fw"></hc-icon>
</div>
```

but alas, it did not spin

but there exists these lines of code that cleans up the class to only include the first class thus disabling the neat styling capabilities. 
##### icon.component.ts
```
// make sure that there are no spaces and that if they sent multiple space separated values grab the first
private cleanupFontValue(fontValue: string): string {
   return (fontValue || '').trim().split(' ')[0];
}
```

**Comment by jtrujill** [comment]
If you want to add the fontawesome transformations just add those to the class attribute

`<hc-icon fontSet="fa" fontIcon="fa-spinner" class=" fa-pulse fa-fw"></hc-icon>`
