### ISSUE TITLE
Change to hc-tab-set markup breaks styling for iframes and other contents of unknown height

### ISSUE THREAD

**Issue by isaaclyman** [HealthCatalyst/Fabric.Cashmere#1903]
**Summary**

A recent change to the hc-tab-set markup added an internal `<div>` without a class, making it difficult to style. This broke some of our pages that use an iframe, since `height: auto` can't detect the size of an iframe.

**Additional context**

See my comment here: https://github.com/HealthCatalyst/Fabric.Cashmere/commit/ea3dcb7488afc93cb6d32a2beda5057c8acbc332#r76535655

**Comment by andrew-frueh** [comment]
Thanks for this @isaaclyman , I should have time to get a patch out tomorrow.  Are you all on the latest version of Cashmere so you can pull the patch in easily enough?

**Comment by isaaclyman** [comment]
@andrew-frueh Yep! thanks.
