### ISSUE TITLE
Cashmere is using deprecated highlightblock from highlight.js

### ISSUE THREAD

**Issue by j2jensen** [HealthCatalyst/Fabric.Cashmere#1923]
**Summary**

The highlighting component uses the highlightBlock function from highlight.js, [which is deprecated](https://highlightjs.readthedocs.io/en/latest/api.html#highlightblock). This causes warnings in the console and could cause bugs if the library is updated in the future.

**Reproduction**

Steps to reproduce:

1. Go to https://cashmere.healthcatalyst.net/web/components/
2. Open dev tools
3. See the following warnings in the console:
    > Deprecated as of 10.7.0. highlightBlock will be removed entirely in v12.0 main.  
    > Deprecated as of 10.7.0. Please use highlightElement now.

**Comment by andrew-frueh** [comment]
Nice catch on this on @j2jensen - I see the console warning you're referring to.  Will get an update prioritized.
