### ISSUE TITLE
Overflow Setting on Cashmere Examples 

### ISSUE THREAD

**Issue by cikeddy** [HealthCatalyst/Fabric.Cashmere#1998]
**Summary**

The tabs being used for Cashmere examples don't have an overflow state set. We should think about which one would be best and update the component properties.  

**Reproduction**

Steps to reproduce:

1. Add many files to a Cashmere example.
2. See that the tabs don't get set to the more menu or the arrows overflow.

**Additional context**

![image](https://user-images.githubusercontent.com/46426253/204305521-f6c7df4a-b9e9-442a-86f5-87d42a75f895.png)

**Comment by cikeddy** [comment]
Might be a more menu bug

**Comment by andrew-frueh** [comment]
Definitely a `More` menu bug.  And most annoyingly it's intermittent.  If you visit a page with lots of tabs on an example (https://cashmere.healthcatalyst.net/web/components/toaster/examples) and reload the page, or flip to another component and come back - sometimes you get a more menu and sometimes you don't.  Need to get more robust width checking for the more menu :-(
