### ISSUE TITLE
Separate documentation site from library code

### ISSUE THREAD

**Issue by joeskeen** [HealthCatalyst/Fabric.Cashmere#20]
As per discussion on #17, separating out the documentation site from the library code has advantages including, but not limited to:

* dependencies can be added to the documentation site without bloating the library
* it's easier to understand when making changes what impact those changes will have
* more approachable for new contributers

Making changes to this will require care to preserve the NPM packaging process and the documentation site publishing process.  Changes to these may be necessary.

**Comment by jtrujill** [comment]
I like this idea. We should move all the demo components out of the lib directory and into the demo directory. It makes no sense to have those components in the lib only to have them imported into the demo.module. I can get a PR out for moving those elements

**Comment by corytak** [comment]
@jtrujill I believe @joeskeen has already started on this so you may want to double check with him to see how far he is in the process.

**Comment by joeskeen** [comment]
I'm almost done with this, I'm just having issues with running the tests once the library components are removed from the CLI project (the demo site).  If anyone has some time to poke around with this, I'd appreciate the help: https://github.com/joeskeen/Fabric.Cashmere
(I know this branch is a bit out of date as this project has been really active lately; I will resolve the merge conflicts when I get the testing working.)

**Comment by jtrujill** [comment]
@joeskeen Yeah I'll totally take a look. I need to get some actual work done today but I'll definitely see if I can help you get that resolved

**Comment by jtrujill** [comment]
@joeskeen is it the update-angular-cli branch that you need me to look at?

**Comment by joeskeen** [comment]
Fixed by #88.
