### ISSUE TITLE
Many components do not render when navigating between tabs in Microsoft Edge

### ISSUE THREAD

**Issue by benjanderson** [HealthCatalyst/Fabric.Cashmere#200]
Reproduced on Edge 41.16299.15.0
![image](https://user-images.githubusercontent.com/1934453/38686199-08446798-3e31-11e8-89de-5031a1f825ab.png)

The following error was in the console, I am not sure if its related
`HTML1500: Tag cannot be self-closing. Use an explicit closing tag.`

**Comment by benjanderson** [comment]
I think this is a tabs issue, as many components are not fully rendered unless you do a full refresh of the page. I cannot get this to reproduce outside of tabs in microsoft edge. I am renaming this issue

**Comment by jtrujill** [comment]
@benjanderson do you know if this is still an issue

**Comment by benjanderson** [comment]
Yes, about half of them do not work with the following error

![image](https://user-images.githubusercontent.com/1934453/44874452-71bb4d00-ac58-11e8-8459-a1c2b6976e4e.png)
