### ISSUE TITLE
Drawer gets stuck open if a user calls `toggleOpen()` twice

### ISSUE THREAD

**Issue by jonest** [HealthCatalyst/Fabric.Cashmere#2005]
**Summary**

Calling `toggleOpen()` while drawer is open causes drawer to stay stuck open.

**Reproduction**

When the drawer is open, call `toggleOpen()` again, then try to call `toggleClose()` and it won't close.

**Additional context**

It seems to be related to the animation promise not resolving when calling `toggleOpen()` the second time. I believe if we just add a check internally for whether the drawer is open, we can just return a promise right away with the expected result (or maybe just ignore it since the drawer wasn't actually opened?)

**Comment by aaronbrethorst** [comment]
As described by Ty, I was able to repro this by calling `toggleOpen` twice, and then calling `toggleClose`. The Cashmere example can be changed thusly to make this trivial to repro:

```
--- a/projects/cashmere-examples/src/lib/drawer-basic/drawer-basic-example.component.html
+++ b/projects/cashmere-examples/src/lib/drawer-basic/drawer-basic-example.component.html
@@ -13,6 +13,12 @@
         <button hc-button buttonStyle="primary" (click)="rightDrawer.toggle()" class="demo-button">
             Toggle Right Drawer
         </button>
+        <button hc-button buttonStyle="primary" (click)="rightDrawer.toggleOpen()" class="demo-button">
+            Toggle Open Right Drawer
+        </button>
+        <button hc-button buttonStyle="primary" (click)="rightDrawer.toggleClose()" class="demo-button">
+            Toggle Close Right Drawer
+        </button>
     </hc-drawer-container>
     <p>Left Drawer State: <strong>{{leftState?"Opened":"Closed"}}</strong></p>
     <p>Right Drawer State: <strong>{{rightState?"Opened":"Closed"}}</strong></p>
```
