### ISSUE TITLE
remove borders on table headers

### ISSUE THREAD

**Issue by benjanderson** [HealthCatalyst/Fabric.Cashmere#201]
On the table styles it gives an option for a table with borders

http://cashmere.healthcatalyst.net/styles/table
![image](https://user-images.githubusercontent.com/1934453/38686664-14caef54-3e32-11e8-8c4f-acce08fb3b4c.png)

but on a xd ui mockup there exists a table with borders that doesn't have borders on the table headers. 
![image](https://user-images.githubusercontent.com/1934453/38686796-6f5208a4-3e32-11e8-8e62-06a9b2c20d26.png)

I think it looks better without the borders on the top

**Comment by corykon** [comment]
@andrew-frueh have an opinion on this one? I'm happy to peel those borders off the table headers real quick.

**Comment by andrew-frueh** [comment]
Yeah, good catch @benjanderson.  In all my prototypes I've displayed tables without borders on the header.  So @corykon if we can make that the default that would be great.  But there might could be a situation where header row borders are needed.  So maybe leave the style in there as an option to include if there is a reason for it.  That work?

**Comment by corykon** [comment]
@andrew-frueh: sounds good
