### ISSUE TITLE
Allow HTML Formatting in Tooltip

### ISSUE THREAD

**Issue by cikeddy** [HealthCatalyst/Fabric.Cashmere#2020]
**Describe your idea**

Allow tooltips to accept html instead of just strings, so we can put formatting (paragraph spacing, bolding, etc.) into tooltips.

**What problem are you trying to solve?**

Right now we can't bold tooltip text to add emphasis to certain words.

**Comment by corykon** [comment]
I think this can be done today. Us a regular popover and the hc-tooltip class. Here's an example from popanalyzer:

```
<span [hcPop]="rowCounterTooltip" trigger="hover">Row numbers</span>

<hc-pop  #rowCounterTooltip [disableStyle]="true">
  <div class="hc-tooltip">
    <h4>Show row numbers</h4>
    <p>When enabled, row numbers will be shown on the left side of the data grid.</p>
    <p>Note: This column will not be included in data exports.</p>
  </div>
</hc-pop>
```

![image](https://user-images.githubusercontent.com/12416432/210856996-18895861-2178-43ce-88b5-ae599838956b.png)

**Comment by cikeddy** [comment]
Ohhh, well that's much easier! Thanks :) 

Let's resolve this issue @corykon
