### ISSUE TITLE
Basic input with icon doesn't work

### ISSUE THREAD

**Issue by isaaclyman** [HealthCatalyst/Fabric.Cashmere#204]
It's unclear what FontAwesome icon sets and what version of FA are supported, and if FontAwesome comes bundled or has to be installed separately. The following shows an input with no icon:

```html
<div class="filter" hcInputIcon>
  <input hc-input name="inputFilter" placeholder="Filter">
  <hc-icon icon-sm fontSet="fas" fontIcon="fa-filter"></hc-icon>
</div>
```

![image](https://user-images.githubusercontent.com/9139369/38827010-c7a5d528-416e-11e8-9ed5-02d75011b65d.png)

**Comment by joeskeen** [comment]
I was able to get this to work in Fabric.Authorization.AccessControl: 

```html
<div hcInputIcon>

      <input hc-input name="filter" placeholder="filter" [(ngModel)]="filter" (keyup)="keyUp.next($event)" />

      <hc-icon fontSet="fa" fontIcon="fa-filter"></hc-icon>

</div>
```

See source at https://github.com/HealthCatalyst/Fabric.Authorization/blob/master/Fabric.Authorization.AccessControl/src/app/modules/access-control/member-list/member-list.component.html#L29

You may want to check out that project and see if your project configuration matches what we have... something may be missing.

**Comment by joeskeen** [comment]
@isaaclyman do you need to change `"fas"` to `"fa"`?

**Comment by isaaclyman** [comment]
That works. For clarification, the FontAwesome documentation indicates that the fontset is "fas": https://fontawesome.com/icons/filter?style=solid

Any thoughts on why the `fontSet` attribute exists if it only accepts `"fa"`?

**Comment by benjanderson** [comment]
We use font awesome 4 which uses "fa" https://fontawesome.com/v4.7.0/ "fas" was introduced in version 5 as many classes had breaking changes.
