### ISSUE TITLE
Tab Component tabClick event

### ISSUE THREAD

**Issue by juanslinger** [HealthCatalyst/Fabric.Cashmere#2044]
**TabClick event without data emitted**

Looking into the documentation for the TabComponent, it says that the `tabClick` event is emitting the `Event` interface from the DOM. This is not correct and in the tab component file, we can confirm that nothing is being emitted.
`projects\cashmere\src\lib\tabs\tab\tab.component.ts`

So, I don't know if the correct solution is to expose the `Event` from the DOM or just define the `tabClick` to be an `EventEmitter<void>`.

**Comment by andrew-frueh** [comment]
@juanslinger - perfect timing on this one.  You might have seen my invite come across for a Tabs workgroup that will meetup this Thursday.  I've got a PR in for review overhauling the More menu width calculation algorithm (#2045).  Would be great to make sure this fix gets taken care while we're working on that.  Make sure and call this out when we're chatting on Thurs if someone doesn't get a fix in before that.
