### ISSUE TITLE
Tabs component strips query params from URL

### ISSUE THREAD

**Issue by isaaclyman** [HealthCatalyst/Fabric.Cashmere#2061]
**Summary**

I've been noticing that query parameters are getting stripped from URLs in the app in two situations:

1. Reloading the page
2. Clicking from one tab to another

This only happens on pages where we use hc-tab-set and hc-tab with `[routerLink]` parameters. I believe these components to be the root cause after a couple of hours of debugging in our app. (We are using the `[queryParams]` parameter on every tab to preserve whatever query params are currently in the URL, so this is especially troubling.)

I'll work on an MCVE today.

**Reproduction**

1. Use hc-tab-set and hc-tab components with `[routerLink]` paths.
2. Manually set some query parameters when the user clicks a button.
3. Reload the page or click to another tab. The query parameters disappear.

Stackblitz reproduction: (WIP)

**Additional context**

Cashmere v13.7.0 and v13.7.1 both have this behavior.

**Comment by andrew-frueh** [comment]
Thanks @isaaclyman - is this something that just got introduced in 13.7, or was it happening in previous versions too?

**Comment by isaaclyman** [comment]
I wish I could say for sure. I only started noticing it recently, but it's possible we had code on our end that was handling it and refactored it out without immediately noticing.

If I had to guess, I'd say yes, this is new to 13.7 or possibly 13.6.

**Comment by andrew-frueh** [comment]
No prob - I'll put this up at the top of the todo list for early next week.  If you have any time for troubleshooting or creating a Stackblitz, send my way.

**Comment by isaaclyman** [comment]
Stackblitz isn't working for me, so here's an example repo:

https://github.com/isaaclyman/Cashmere-tabs-queryparams-bug

In the process of making the MCVE, I noticed a few things.

1 - The "query params disappear on refresh" bug takes very little setup to reproduce. See commit 363e92d on the example repo.

2 - The "query params disappear when switching tabs" bug happens only when the `[selectedTab]` parameter is used.

3 - If you use the `[selectedTab]` parameter without the `defaultTab` parameter, a brand new bug occurs. To see it, click the "Child 2" tab, then refresh the page. On reload, the "Child 1" tab will be selected, and the URL will have changed from `http://localhost:4200/child-2` to `http://localhost:4200/child-1;0=child-1`. Very odd.

**Comment by isaaclyman** [comment]
I'm looking at the Cashmere component now. It looks like `router.navigate()` is often called without `queryParamsHandling: 'preserve'` in the extras. The default Angular Router behavior is to discard query parameters. This is probably desirable behavior in general (since query params typically aren't valid across multiple pages) but seems problematic in the following case:

1. The app sets query parameters in the URL.
2. The user clicks a tab, which navigates to a new route via the anchor link in the hc-tab template.
3. Since the route has been updated, app code returns a different index to the `[selectedTab]` parameter of hc-tab-set.
4. The `selectedTab` setter is triggered in TabSetComponent, which causes `_selectedTabSubject` to emit.
5. The `selectedChanged$` observable in `ngAfterContentInit` emits. The subscriber calls `selectTab()`.
6. As long as a valid tab index has been passed, `selectTab()` calls `router.navigate()` without any queryParamsHandling, so query params are discarded.

This makes it so we can't use `[queryParams]` on hc-tab and `[selectedTab]` on hc-tab-set at the same time; they cancel each other out.

Ideally, we wouldn't need `[selectedTab]`, but it seems to be the only way to maintain the selected tab when the page refreshes.

As for #3 above, with the URL getting garbled, I haven't yet pinned down what's causing that.

**Comment by isaaclyman** [comment]
Discovery: the URL garbling only happens when you pass an array into `[routerLink]` on hc-tab. Does not happen when you pass a string.

**Comment by isaaclyman** [comment]
Ah, there it is.

```ts
selectTab(tab: number | TabComponent, shouldEmit = true, scrollIntoView = true): void {
    this._selectedTab = tab;
    const activeTab = typeof tab === 'number' ? this._tabs.toArray()[tab] : tab;
    if ( tab === -1 || activeTab._hideOverride ) {
        // ...
    } else {
        if ( this._routerEnabled ) {
            // At this point, activeTab.routerLink may be a string or an array. Either way, it's getting wrapped in array.
            //  Angular Router must not like being passed a nested array.
            this.router.navigate([activeTab.routerLink], {relativeTo: this.route});
        }
        // ...
    }
}
```

**Comment by isaaclyman** [comment]
Okay, it seems like the solution to the URL garbling is to use `mapRouterLinkToString` in `selectTab` to make sure we're always putting a string in that navigation array.

As for navigation happening unnecessarily when `[selectedTab]` changes, maybe the right move there is to make `selectedChanged$` less trigger-happy. I'm not sure if the root problem is that it's trying to compare a number to a TabComponent instance or if it's just failing to update `_selectedTab` when the user clicks the tab.
