### ISSUE TITLE
The checkbox doesn't check

### ISSUE THREAD

**Issue by isaaclyman** [HealthCatalyst/Fabric.Cashmere#207]
Using this markup:

```html
<div class="check">
  <hc-checkbox>
    Check Box
  </hc-checkbox>
</div>
```

I get something that looks like a checkbox:

![image](https://user-images.githubusercontent.com/9139369/38828639-ea8a92fe-4173-11e8-83c1-c876182e8636.png)

But doesn't change to a checked state when I click on the box or on the label.

**Comment by corykon** [comment]
@isaaclyman Thanks for submitting this! There's a bug with the way this component sets up ids when one isn't explicitly provided.

I'll submit a PR to fix, but in the meantime, a workaround would be to add an id to your checkbox component.
