### ISSUE TITLE
File Uploader - Unable to reset file selection

### ISSUE THREAD

**Issue by KatiuscaH** [HealthCatalyst/Fabric.Cashmere#2078]
**Summary**
You cannot remove a file selected from the File Uploader component using the `reset() `method.
I'm using a viewChild to get the element, because there's no service to inject in the component.

**Reproduction**

Steps to reproduce:
PLEASE: Use the stackblitz's link to reproduce it.

1. Add a file (any type)
2. Click on the Remove button.
3. See the error: ERROR Error: Illegal constructor

Stackblitz link: https://stackblitz.com/edit/angular-3mkd8h?file=src%2Fapp%2Ffile-uploader-overview%2Ffile-uploader-overview-example.component.html

**Additional context**
<img width="455" alt="image" src="https://user-images.githubusercontent.com/23409262/224150411-b31caf7b-87c1-4c6b-a670-3d3038cd3f9c.png">

![image](https://user-images.githubusercontent.com/23409262/224149861-2f01fb1d-3222-4ffb-834f-0aeedb9cc716.png)

**Comment by isaaclyman** [comment]
I've been reading up on `FileList`, the "illegal constructor" mentioned in the error message. It looks like, for (mostly obsolete) security reasons, creation of a FileList is not possible in user-side JavaScript. A FileList always has to come from a file input. But we may be able to clear the FileList by setting the value of the associated input: https://stackoverflow.com/a/3162319/4347245

**Comment by andrew-frueh** [comment]
Thanks @KatiuscaH and @isaaclyman - I'm on it, will try to get a fix in today
