### ISSUE TITLE
Make hcTooltip support conditional expressions

### ISSUE THREAD

**Issue by isaaclyman** [HealthCatalyst/Fabric.Cashmere#2079]
**Describe your idea**

It would be cool if `[hcTooltip]` could be conditionally rendered.

**What problem are you trying to solve?**

We have situations where a tooltip is needed in some states but not others. It's natural to try to do:

`[hcTooltip]="shouldShowTooltip ? 'You can't do that right now.' : null"`

Or 

`[hcTooltip]="shouldShowTooltip ? 'You can't do that right now.' : undefined"`

But in both cases, an empty tooltip is still shown (see below). It would be great if the tooltip only showed when there was content in it.

**Additional context**

![image](https://user-images.githubusercontent.com/9139369/224425289-524cf76f-5d3e-43c1-9c44-f91ddc5fe899.png)

**Comment by bskeen** [comment]
Note: This is possible currently by binding to the `[trigger]` property on the HcPopoverAnchorDirective (that is how it is handled in the Instance Switcher in Cashmere, see https://github.com/HealthCatalyst/Fabric.Cashmere/blob/f0c1ddd85fa5a9f7ca359fc0bf0ac36f3933a6c7/projects/cashmere/src/lib/instance-switcher/instance-switcher.component.html#L64-L65)

**Comment by isaaclyman** [comment]
Oh, brilliant. I'll use that as a workaround for now.
