### ISSUE TITLE
Show placeholder in hc-select for any falsy value

### ISSUE THREAD

**Issue by isaaclyman** [HealthCatalyst/Fabric.Cashmere#2092]
**Describe your idea**

`hc-select` should show its placeholder text when its value is _any_ falsy value (null, undefined, false, 0, or empty string), not just the empty string.

**What problem are you trying to solve?**

I created an hc-select with a placeholder, then added an `[(ngModel)]` to it with the initial value set to `null`. I was surprised when the placeholder didn't show up. I then tried setting the value to `undefined`, but the placeholder again didn't show. I had to dig into the Cashmere component template to learn that the only situation where the placeholder shows is if the value of the hc-select is the empty string `''`.

**Additional context**

I'm not completely sold on this, just putting it out there for discussion. Maybe there are situations where an `<option>` has a value of `null` or `undefined`, in which case that option should be selected instead of showing a placeholder. But it's a little counterintuitive to have to set an empty string instead of `null` on a `<select>` with no value.

**Comment by andrew-frueh** [comment]
That's some good troubleshooting already there @isaaclyman - I'm not sure I realized that it was _only_ displaying on an empty string.  I'd tend to agree with you that it seems pretty odd someone would want to set an option value to `null`.  Just as (un)likely someone would want to set to an empty string.  So for the sake of consistency I think that you're right - any falsey value should show the placeholder.  I'll give this a look this afternoon.

Btw - isn't `ngModel` deprecated? 😉

**Comment by isaaclyman** [comment]
> Btw - isn't ngModel deprecated? 😉

No, [thankfully not](https://docs.angular.lat/guide/deprecations#ngmodel-with-reactive-forms). Using `ngModel` _and_ `formControl` on the same form element is deprecated. But `ngModel` by itself lives on, which I'm very glad for. So much less boilerplate than a form control!
