### ISSUE TITLE
Cashmere restructure

### ISSUE THREAD

**Issue by jtrujill** [HealthCatalyst/Fabric.Cashmere#210]
## File Structure
The file structure is a bit confusing. Right now we have things in docs/app which refer to the demo app and we have things for the library under lib/src. It's common to keep all of your source code under the same root directory. So for example we would have the following structure:
```
/docs(guide)
/src
    demo/
    lib/
        accordion/
        ...
```

#### Package.json
It's also confusing to have two package.json files and the only real difference I'm seeing comes from the way we handle markdown files. If we move to generating documentation at runtime, we could move those dependencies to dev-dependencies and merge the two package.json files.

#### Font Dependencies
It would also be best to remove the dependency on font-awesome and npm-font-open-sans. It's odd to have those dependencies and they're used in the lib where you could easily use css hacks to achieve the same thing. For the demo page we could have a direct reference to the fonts on the index page
`<link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">`
This should be the preferred way to include fonts and will avoid conflicts. It'd be best to mention in the style guide which font to use as the base font.

## Styles Page
It might be better to create a separate repo which dependents on Cashmere and serves more as a web style guide. It could give examples for how a page should look and interact. The benefit of extracting this out is that initially this would add another project to the set of projects currently testing Cashmere. There's also a logical separation between it and Cashmere and would keep the Cashmere project more lean.

### Markdown
Currently we have markdown files but the way that we convert markdown to html is done at runtime. The problem with this is that it requires that we setup a demo component for each component we are testing. If instead we generated our documentation(markdown->html, Api docs) at build so that it followed an easy convention we could use a more general purpose component that could be powered by configuration.

The process would be similar to this https://github.com/angular/material.angular.io/blob/e6dc7ead09e81cd60b84c256f762386c2d3c69a1/src/app/shared/documentation-items/documentation-items.ts which would require far less coding for existing and new components. We would only commit the generated documentation into our github.io account.

### API(Interface) Documentation
In addition to markdown, we need something that documents a components API(interface):
- `@Inputs()`
- `@Outputs()`
- Public methods and variables 
- Selectors
To do this we should use a document generator, since documentation written by hand goes stale fast and is rarely sufficient. I've been looking at a couple and https://github.com/angular/dgeni seems to be the most powerful.

### Examples
Finally for our examples we need to embed CodePen or some other similar website within our page so that the user can toggle between the src files and interact with the component. It would allow the users to play around in a sandbox environment

### Bringing it together
We could use the tab component so that we have the following three tabs for each component:
- Overview - rendering of the markdown file that had been converted to html
- Api - Generated Documentation from source code
- Examples - CodePen or similar examples embedded in page

The only thing that would be tricky is the Overview page. What we could do is, since we've converted the markdown files into html, we can create a component which fetches the html file from the server and renders its content.

**Comment by jtrujill** [comment]
The stuff about markdown and the api interface can be put off initially. The most important part of this discussion I want to be about making development easier and making the project structure more standardized. 

Right now the build doesn't work if you build the library and have those artifacts hanging around. I can get a PR out that fixes that issue and makes our structure more standard

**Comment by benjanderson** [comment]
I love many of these ideas, I agree with the project structure and would love to have a way to have a live coding example.

About a month ago, I created a new app and copied the demo site and added the npm package. It was eye opening how many things we didn't think of when creating the library. To reproduce Isaacs bugs, I installed the latest npm and the app is broken 😖 

I would propose we separate the demo site from the library. There are some libraries besides the markdown stuff that the demo uses that the library doesn't (not just for markdown)

- `highlight.js`  - source code highlighting
- `d3` - graphs

This would solve our problem of separate `package.json` files and having to cleanup the build objects.

**Comment by corykon** [comment]
I LOVE the idea of using dgeni, and embedding some kind of code previewer like code pen. Many conversations have been had conversations about both of those... tough thing is being able to invest the time needed to make it happen.

**Comment by jtrujill** [comment]
@benjanderson I think that is a really good idea about separating it completely. If that's the consensus I can even do that, but for what I was proposing I could just move the demo under a root directory or src/  so that it follows the structure I had in the above comment. I'll see if I can mess around with that sometime this week and get something in a PR

**Comment by benjanderson** [comment]
It looks like angular material uses stack blitz for their live coding examples. I was able to get something working with cashmere

https://stackblitz.com/edit/cashmere-demo

I think this would be a great alternative so the demo matches the code

**Comment by andrew-frueh** [comment]
A couple thoughts to throw in:
- Regarding separating the demo site from the library: the only thing that I could see being annoying there is the ability to test a component as you're developing it.  Could you guys help me understand how that would work if they are separated?  Would a developer just make a placeholder page for testing in the library project while they're writing that they would then remove?  And then build the library, and say open the demo site project and write the documentation over there?  In other words, how much of a pain will it be to have to switch between two projects while writing a component?
- Overview, API, and Examples sound good to me as the sections for each component.  Under Overview I'd suggest an "About" tile in addition to showing a demo of the component (as we currently do in most cases).  And potentially another tile describing secondary uses or how the tile behaves responsively.  I'm thinking mostly about a Product Manager persona now, who would probably only look at the Overview tab when trying to think through strategy for new pages in their app.
- I'm not opposed to separating the styles out from the library, but would definitely like to keep everything together on the demo site.  I know that if I have to tell folks to bookmark multiple sites to find our standards, it's going to be a problem.  But it sounds like if the demo site was a separate project, it could pull both Cashmere and whatever we call the package of styles (Plaid?).

**Comment by joeskeen** [comment]
The project structure has definitely kept me up at night.  Thanks @jtrujill for calling it out!

**Comment by jtrujill** [comment]
That's a good point @andrew-frueh. We could keep a very simple demo of the app for the lib development purposes only and as further examples for developers only.

I think that it'd be a good idea to separate the documentation and examples from this repository because this repo is intended for the development of Cashmere.

As a developer when I'm unsure about how to use a library I go to the github page and look for a getting-started.md, which will guide me through the basics of getting setup. Along with that they usually have a CONTRIBUTION.md, CODING_STANDARDS.md, and a DEV_ENV.md. These files tell a developer everything they need to know about using the library. 

Because the markdown files tell a developer everything they need to know there's no reason to complicate things and have some hosted server which shows the same thing but requires more maintenance.

From my perspective we should restructure http://cashmere.healthcatalyst.net for developers. The things a developer needs is an explanation of the different interfaces provided by the different Angular objects(Components, Directives, Pipes...) and something like CodePen or Stackblitz. 

Then we should have a separate repo which serves as a web style guide. In here we could have examples of Sidnav filters, proper use of progress indicators... I've worked across many apps and I've realized that many people use similar component libraries but their use of them is very different. Everyone does progress indicators different is a good example. Some do a full page indicator others do a partial and some don't use them.

With the Web style guide project what I'm proposing is that we show how to properly compose Cashmere to follow a company wide standard. It's not enough to just create a component library and ask that developers use it. An example application needs to be done to show how to compose those components. 

As a small aside it might be useful to host svg images/icons that are organized for developers to use instead of messaging @andrew-frueh directly for everything

**Comment by jtrujill** [comment]
The web style guide app could then have a reference to http://cashmere.healthcatalyst.net, which would have the generated documentation for each component for the developers

**Comment by benjanderson** [comment]
At ng-conf they announced support for libraries in the angular cli https://github.com/angular/angular-cli/releases

Here is the project structure of a project created this way:
![image](https://user-images.githubusercontent.com/1934453/38968906-cfd7b422-434a-11e8-9957-7adb7a8b59cf.png)

It does have a separate package.json, probably so you can have multiple libraries in one project

`ng serve` stopped working after I added the library but `ng build` built the library like a charm. They mentioned its only a few weeks away from release so I imagine they have some finishing touches. I would vote to follow the official structure.

**Comment by benjanderson** [comment]
@jtrujill Let me get this clear on your proposal: 
#### repos
@healthcatalyst/cashmere - component library to be packaged up as an npm package, contains auto generated docs, and simple examples. This would also contain the sass style sheets
@healthcatalyst/cashmere-demo (or whatever) - demo site
@healthcatalyst/style-guide (or whatever) - example of components used in real app

#### websites
cashmere.healthcatalyst.com - developer site for components
styleguide.healthcatalyst.com (or whatever) - style guide that uses cashmere bu establishes how to use it

Unless the angular cli team has a way to separate out library and demo in the same project, I would like to see the demo and the library in separate repos.  They have been silent about how the new `ng generate library {name}` feature works, and I think they are waiting until they figure out the "best" and least buggy way to create a library. 

The biggest criticism I have is the lack of resources. Cashmere is struggling as it is to get work done, as an example there are quite a few more issues being created then closed. We also had a goal of releasing a 1.0 this Friday and I have only seen one pull request from Cory about this which tells me most people are pretty strapped for time on their own projects. I would like to compete with libraries like material that have a full time team dedicated to them but we need to be realistic about what we can do. I think the style guide website may be too ambitious for us to tackle.  I think having a place where a list of links to our apps as demos might be the next best thing as having a real application may be too much work.

**Comment by andrew-frueh** [comment]
We've now have all the approvals needed from leadership to form the steering committee for Cashmere.  For those who haven't heard, the steering committee will be made up of Bryan, Imran, myself, and one developer representative from each of the products lines.  The product line leads are currently working on selecting who those representatives will be, and then we can get that group together to meet for the first time.  My suggestion would be that we table making any decisions on this issue for now, and bring it up with the committee.  I think one of their first responsibilities will be coming to an agreement on who Cashmere is for and who the intended audience of the demo site is.  Once we're all on the same page about that, then I think this will be a much easier decision to make.

**Comment by jtrujill** [comment]
@benjanderson You seem to have a good understanding about what I'm proposing

@andrew-frueh I agree that we should hold on making radical changes like pulling our current demo out until after this meeting, but I'd like to proceed forward with moving all of our source code under the /src directory. @benjanderson I'll take a look at the structure used by @angular/cli-rc2 and see if I can get that in place because I'm all about following standards
