### ISSUE TITLE
Input update

### ISSUE THREAD

**Issue by jtrujill** [HealthCatalyst/Fabric.Cashmere#216]
I'll be making an update to the input component so that it's easier to use. Currently this is what you need to do:

```
<label hc-label required="true">Validate an email address:</label>
<input hc-input name="inputEmail" required highlight="false">
<div class="form-errors" *ngIf="inputEmail.invalid">
    Use the form-errors class for error messages
</div>
```

What I had originally planned to do before getting swamped with work was this

```
<hc-input-container>
   <input hc-input [formControl]="control">
   <hc-error *ngIf="control.hasError('required')">This is required</hc-error>
   <hc-error *ngIf="control.hasError('minlength')">This also has a minlength</hc-error>
</hc-input-container>
```
I had created a ticket a while ago that talked about copying the style that angular material uses for their labels. Which style is preferred? I could make it so it's configurable, so that the input could have the placeholder frozen above the input. [Material](https://material.angular.io/components/input/examples)
 
I'm thinking this will need to work with hc-input and hc-select which shouldn't be too difficult. I'll also get some unit tests in place for these components since these will be very important

**Comment by isaaclyman** [comment]
Where does the label go in this configuration?

**Comment by jtrujill** [comment]
Here's one solution:

```
<hc-input-container>
   <input hc-input [formControl]="control" placeholder="AwesomeLabel">
</hc-input-container>
```

Another:

```
<hc-input-container>
   <hc-input-label>AwesomeLabel</hc-input-label>
   <input hc-input [formControl]="control" placeholder="AwesomeLabel">
</hc-input-container>
```

I prefer solution one because it doesn't introduce another element the user needs to use in the template and I don't want them to be confused and think they need to do some kind of `label for=""` matching using IDs. I'd like to keep that abstracted away from the user and handle the label myself. It's less error prone and just easier to work with
