### ISSUE TITLE
Angular 15

### ISSUE THREAD

**Issue by andrew-frueh** [HealthCatalyst/Fabric.Cashmere#2165]
Somehow we got a bit out of sync with the official Angular release schedule:
https://angular.io/guide/releases#support-policy-and-schedule

...as per our stated policy, we should be supporting the _most current version_ that is in LTS.  Angular 15 went into LTS on May 3rd.  So we should move our Angular dependency to Angular 15 in the next month or so.

**Comment by hc-jordenlowe** [comment]
This is also out of date:  https://cashmere.healthcatalyst.net/web/guides/supported-angular-versions
