### ISSUE TITLE
Drawer and Sidenav could use a "click outside to close" feature

### ISSUE THREAD

**Issue by isaaclyman** [HealthCatalyst/Fabric.Cashmere#2198]
**Describe your idea**

Cashmere's Drawer and Sidenav components stay open after expansion unless you specifically close them. Especially in Drawer's `over` mode, this is unexpected UX—typically anything that covers the screen closes when you click or tap outside of it.

It would be nice if they had an optional backdrop so they would close when you interact with something outside of them.

**Comment by aaronbrethorst** [comment]
I think this is a great idea, @isaaclyman

**Comment by isaaclyman** [comment]
See #2222 - this can't be done for the Sidenav in its current state.
