### ISSUE TITLE
Cleanup imports

### ISSUE THREAD

**Issue by jtrujill** [HealthCatalyst/Fabric.Cashmere#220]
I'm going to cleanup the imports in the project so that they are easier to read. An example of what the imports look like can be found in the components.module.ts

```
import { NavbarModule } from '../../../lib/src/navbar/navbar.module';
import { PopoverModule } from '../../../lib/src/popover/popover.module';
```

I'm going to use typescript pathMapping to help clean them up so that we can import the components needed by doing the following

```
import { NavbarModule } from '@healthcatalyst/cashmere/navbar/navbar.module';
import { PopoverModule } from '@healthcatalyst/cashmere/popover/popover.module';
```

@joeskeen what was the issue with using the index.ts file for every component? It's standard in all libs to have an index file for individual modules which can be imported. It is also how node module resolution works by looking for an index.js file. 

The imports above could be further shortened if we went with the standard:

```
import { NavbarModule } from '@healthcatalyst/cashmere/navbar';
import { PopoverModule } from '@healthcatalyst/cashmere/popover';
```

If you are able to tell me what the issue was I can also introduce index files for all components and make sure everything works

**Comment by jtrujill** [comment]
I saw you mentioned something about using explicit exports and I can do that and maybe that will fix whatever issue you were seeing

**Comment by joeskeen** [comment]
Be sure to test building the demo app, building with AOT, the library, and usage of the library after it is `npm pack`'d.  I seem to recall some issues with the TS aliasing earlier in the project, but maybe you can figure out how to get past them.

**Comment by jtrujill** [comment]
@joeskeen I just tried to get a reference to a ButtonComponent and the import looks like this
`import {ButtonComponent} from '@healthcatalyst/cashmere/src/button/button.component';`

and when I try to get a reference to the button in the html like so 

`@ViewChild(ButtonComponent) button: ButtonComponent;`

it produces the following error at compile-time
`Module not found: Error: Can't resolve '@healthcatalyst/cashmere/src/button/button.component' in '/Users/jeremy.trujillo/Documents/projects/claims-quality-explorer/angular/src/app/jobs/mapping'`

I'll mark this as a bug and get something out
