### ISSUE TITLE
Create Standard for in-app Release Notes

### ISSUE THREAD

**Issue by corykon** [HealthCatalyst/Fabric.Cashmere#2220]
### **Describe your idea:**
Each web app has a slightly different way of presenting release notes. We should create a standard for this. Could be a component, a set of styles, or just an example template.

### Things to consider for the standard:
- Separate sections for features vs fixes
- Screenshots are great
- Linking to HC Community docs and release notes is great.
- Should include links to a place to request features
- Collapsible sections is a helpful thing, per release and/or per feature

### **Examples of what is in use today:**
**PopInsights**
![image](https://github.com/HealthCatalyst/Fabric.Cashmere/assets/12416432/f53212c4-b87c-47d9-bca1-186dd4b35cdf)

**Atlas**
![image](https://github.com/HealthCatalyst/Fabric.Cashmere/assets/12416432/3cc09bc4-3c93-4d2e-946e-84004ea91725)

**Operations Console**
![image](https://github.com/HealthCatalyst/Fabric.Cashmere/assets/12416432/428effd7-2a1e-4d78-821d-8bb4aff534f1)

**Pop Analyzer**
![image](https://github.com/HealthCatalyst/Fabric.Cashmere/assets/12416432/12c2395b-2e83-43f5-a759-d9e79ac37334)

**AccessControl** - opens a Health Catalyst Community page
**IDEA** - doesn't have anything
**Patient Safety Monitor** - opens a Health Catalyst Community
**Value Sets** - has nothing

**Comment by corykon** [comment]
@AdamGMiller @corinnen @atkulp anything you would add?

**Comment by atkulp** [comment]
might be nice to offer the option to set the actual content from objects or a feed url. I think Pop Insights has the closest to what I'd want at this point other than needing expanding sections. is it also worth considering a flag/role on items to show/hide based on the person being an admin or certain class of user? not as a security feature, but just to streamline what you see
