### ISSUE TITLE
hc-subnav should not have a margin

### ISSUE THREAD

**Issue by isaaclyman** [HealthCatalyst/Fabric.Cashmere#223]
`<hc-subnav>` has a bottom margin of 22px. This makes it harder to implement e.g. a sub-sub-navbar, such as the one in this design spec:

![image](https://user-images.githubusercontent.com/9139369/38953377-cdf38670-430b-11e8-87eb-6c8d738d94ba.png)

IMO a subnav should have no margin, and if a margin is desired, the element beneath should implement margin or padding.

Any dissenting opinions? If not, I'll make a pull request.

**Comment by jtrujill** [comment]
I may not understand this but none of these components should have an outside margin applied. The user of the component should be able to set whatever margin they need

**Comment by andrew-frueh** [comment]
@isaaclyman - I think I added that back when I was building it.  I agree with both of you about components not having their own margin and leave that to the app.  So please go ahead and submit a PR to remove that.
