### ISSUE TITLE
Descenders getting clipped on SideNav

### ISSUE THREAD

**Issue by andrew-frueh** [HealthCatalyst/Fabric.Cashmere#2244]
**Summary**

Just noticing that on the sidenav component, any values with descenders (g,y,etc) are getting clipped.  Probably just need to allow for overflow or expand the height.

![Screenshot 2023-10-06 at 11 06 38 AM](https://github.com/HealthCatalyst/Fabric.Cashmere/assets/22795893/6dfef13b-4665-4b81-a982-c05dc65441c7)

**Comment by corykon** [comment]
This reminds me that I really want to see the product catalog app. Demo
next 1-on-1?
