### ISSUE TITLE
Sidenav should support nested links OR content projection on the main body

### ISSUE THREAD

**Issue by isaaclyman** [HealthCatalyst/Fabric.Cashmere#2261]
**Describe your idea**

`hc-sidenav` should support links that have children (e.g. the `SidenavLink` interface should have a recursive `children` field) _or_ it should support content projection in the main body (and provide a context variable indicating if the nav is expanded or collapsed).

The first option would be preferable so more of the behavior can be abstracted away, but the second might be easier to implement.

**What problem are you trying to solve?**

We've found that SidenavComponent lacks some key features we'd need in order to use it in BDS apps. We have nested links (up to 3 levels deep) in our sidenav, which is a necessity due to the number of pages in our apps, but also nice for keeping links organized.

We still use hc-drawer, which works fine, but it would be nice to get the look and feel of hc-sidenav.

**Comment by corykon** [comment]
@isaaclyman I've got a similar request from another application, so i'm going to get working on it soon.

Could you send me a screenshot of your current nav, and/or a list of the nav structure you after to make sure I meet the needs with the changes I make?

**Comment by isaaclyman** [comment]
## PowerPlanning

Navigation, part 1

![image](https://github.com/HealthCatalyst/Fabric.Cashmere/assets/9139369/42399ea8-b4c1-4692-aa55-9e2de967aadc)

Navigation, part 2

![image](https://github.com/HealthCatalyst/Fabric.Cashmere/assets/9139369/def8f4dc-eb1f-466f-b837-007e058c9559)

Navigation, part 3

![image](https://github.com/HealthCatalyst/Fabric.Cashmere/assets/9139369/8857f83d-494c-475a-9371-5a10a48d2a7e)

Hovered item

![image](https://github.com/HealthCatalyst/Fabric.Cashmere/assets/9139369/1de47e79-3436-48ad-baf7-242ac8f5a2e6)

Colllapsed nav

![image](https://github.com/HealthCatalyst/Fabric.Cashmere/assets/9139369/8a8e6eed-2efa-45ee-a707-b35e79756d5f)

## PowerLabor

Navigation

![image](https://github.com/HealthCatalyst/Fabric.Cashmere/assets/9139369/c315c3cf-9fbe-4c84-a1de-71c4563d45bf)

Hovered item

![image](https://github.com/HealthCatalyst/Fabric.Cashmere/assets/9139369/781d8518-d42e-441d-8aca-d3dfef494b69)

Collapsed nav

![image](https://github.com/HealthCatalyst/Fabric.Cashmere/assets/9139369/f6b406fc-6240-49b3-ac15-7019e75e39a7)

**Comment by corykon** [comment]
Thank for that @isaaclyman. Here's where I'm headed. Call out anything you see that I'm missing.

**Requirements**
* Allow projection into the main body of sidenav
* Configurable sidenav widths
* Nested Links
    * Option to have nested link structure open by default
    * Option to allow collapsing nested link structures (or not)
    * Option to auto open a nested link structure if the parent link is active
    * Option to show or hide nested link structure lines
    * Option to make a link not clickable
        * (different than disabled… this item would have normal styling, just not be clickable)
* Dark mode
* Link Sections
    * Totally separate group of links with a header, styled like the Favorites section

**Mock Ups**
![image](https://github.com/HealthCatalyst/Fabric.Cashmere/assets/12416432/953b1b36-c7b0-47cd-80a1-e09249028338)
![image](https://github.com/HealthCatalyst/Fabric.Cashmere/assets/12416432/4ae49aca-1a21-4d70-92b6-2e23675325ea)

**Comment by isaaclyman** [comment]
Looks great, @corykon. How customizable are the labels of those links? You'll notice that there are a few cases where we show a status chip on the link, e.g. `BETA`. If there's a custom HTML option, that would be great, or something more specific - just so long as we're not restricted to a string.

**Comment by corykon** [comment]
Yeah that's a good callout :+1:
