### ISSUE TITLE
Feature request: Icon buttons

### ISSUE THREAD

**Issue by isaaclyman** [HealthCatalyst/Fabric.Cashmere#228]
UI libraries often have two categories of buttons: regular buttons and icon buttons.

- Regular buttons are rectangular, whereas icon buttons are round
- Icon buttons may or may not have a visible background color or borders
- Icon buttons have very little padding
- On hover, the icon itself will often change color

This is something that shows up frequently in design specs:

![image](https://user-images.githubusercontent.com/9139369/38956520-0d88c9fe-4315-11e8-8f2f-07eb7ff9db74.png)

It would be great to have this built into Cashmere. I recommend using the `[hc-icon-button]` attribute as opposed to (or in addition to) the `[hc-button]` attribute, and making it clear in the documentation that this type of button should have an `hc-icon` as its only child.

**Comment by jtrujill** [comment]
I've been wanting to do this, so I'll assign this to myself and get something done
