### ISSUE TITLE
Tables should be discoverable in the Components list

### ISSUE THREAD

**Issue by isaaclyman** [HealthCatalyst/Fabric.Cashmere#229]
When I was first looking for a table component, I scanned through the Components list, didn't see one, and implemented my own. That's an avoidable mistake. It was only later, when I was exploring the Cashmere docs generally, that I discovered Cashmere has table styles.

The `.hc-table` class may not add functionality to the native HTML, but in my mind neither does `[hc-button]`. Whether or not it implements an Angular component is probably an implementation detail that the user shouldn't need to know about. I think we should either move Tables to the Components list or add an entry in the Components list that links back to it. It's sort of an odd man out where it's at, anyway.

**Comment by jtrujill** [comment]
There is/was table component under development. I think those styles were really only meant as a starting guide to our own table component

**Comment by isaaclyman** [comment]
Yeah, Andrew mentioned that on Slack. Sounds like it will be ready soon. I'll close the issue.
