### ISSUE TITLE
Cashmere does not export ActiveModal

### ISSUE THREAD

**Issue by isaaclyman** [HealthCatalyst/Fabric.Cashmere#230]
If I try to inject an ActiveModal object in my modal component, VS code offers to import it from Cashmere. But if I do, I get this error:

![image](https://user-images.githubusercontent.com/9139369/39002771-8657555c-43b6-11e8-887c-51410b5de8d2.png)

I think this is because ActiveModal is in the TypeScript declaration file for the module but not exported by the module itself.

~As a workaround, I can do this:~ This makes the IDE error go away but doesn't build:

```typescript
import { ActiveModal } from '@healthcatalyst/cashmere/src/modal/active-modal';
```

**Comment by jtrujill** [comment]
I have a PR out to fix this issue right now

**Comment by jtrujill** [comment]
PR #225

**Comment by isaaclyman** [comment]
Awesome.
