### ISSUE TITLE
Accessibility Docs are broken

### ISSUE THREAD

**Issue by corykon** [HealthCatalyst/Fabric.Cashmere#2307]
Look like accessibility tab in cashmere isn't in good shape. I don't remember everything that belongs there, but write now there are only two tabs, and one of them is labeled incorrectly (UX Writing)

![image](https://github.com/HealthCatalyst/Fabric.Cashmere/assets/12416432/85fda71c-d79f-4203-af65-4ab2cbf71177)

**Comment by corykon** [comment]
@aaronbrethorst Should there be more than two tabs here?

Its possible that the only problem is just that the second tab is mislabeled.

**Comment by aaronbrethorst** [comment]
I think the issue may just be mislabeling

**Comment by corykon** [comment]
The section is question is about writing for accessibility - so UX writing does fit, I just was worried it was using the label from another section. It's totally fine though.

I'll rename to "Writing for Accessibility"
