### ISSUE TITLE
Discussion: Use the Angular CDK

### ISSUE THREAD

**Issue by joeskeen** [HealthCatalyst/Fabric.Cashmere#235]
At ng-conf last week I was made aware of the Angular Component Development Kit, or Angular CDK.  This is a collection of common interaction patterns used in every UI library that enables UI library developers to focus more on the look of their components without having to worry about complications surrounding accessibility, managing overlays, mobile breakpoints, or LTR/RTL content flows.

This package, `@angular/cdk`, was separated out from the Angular Material 2 library, and powers interaction management for Angular Material.  I think it would be worth investigating integrating this into Cashmere to align with industry standards.

More information can be found here: <https://blog.angular.io/a-component-dev-kit-for-angular-9f06e3b4b3b4> and here: <https://material.angular.io/cdk/categories>

**Comment by joeskeen** [comment]
After having worked for a while on the Cashmere table (#79), and understanding the high degree of complexity in implementing such, I am encouraged to see that the CDK contains an "unopinionated, customizable data-table with a fully-templated API, dynamic columns, and an accessible DOM structure".  This may be a better starting point than what we currently have, and allow for further functionality and customization than we can currently provide.  See more here: <https://material.angular.io/cdk/table/overview>

**Comment by jtrujill** [comment]
I'm all for using the CDK. I had mentioned using it for the table since it provides everything that we need and is quite flexible. I've tried to design my own table component and it's difficult to do and I honestly would rather write a wrapper for the CDK table element. There are some other useful features that we could use to cleanup our code

**Comment by andrew-frueh** [comment]
This sounds good to me.  If we use the CDK as our base, I'm assuming our component's default skin will still follow our [table style standards](http://cashmere.healthcatalyst.net/styles/table)?

**Comment by jtrujill** [comment]
Yes we would be able to do that. I'm just getting back from vacation so once I finish the input component I can take a look if no one else has taken this on

**Comment by jtrujill** [comment]
Looks like we're going to use the cdk
