### ISSUE TITLE
hc-table relative position

### ISSUE THREAD

**Issue by benjanderson** [HealthCatalyst/Fabric.Cashmere#239]
While using `hc-table` styles in atlas, we have a loading spinner that overlays the table while network requests happen. To get this spinner to position I had to do the following 
```
.hc-table {
position: unset !important;
}
```
Is their a reason the position is set for the table? This seems too opinionated 

https://github.com/HealthCatalyst/Fabric.Cashmere/blob/master/lib/src/sass/tables.scss

**Comment by corykon** [comment]
Are you talking about `position: relative`? (I don't think `display` is being set by tables.scss).

If so I'd agree with you, that opinion is not needed. I think it was a hold over from some other code I'd written before, needed to position something (likely a spinner, coincidentally) and wanting to center it within the table.

I'd approve a PR with that property removed. 👍

**Comment by benjanderson** [comment]
I meant position, I have corrected the original comment. I will assign this to myself as I have been intending a number of small bug fixes
