### ISSUE TITLE
Navbar app icon as html

### ISSUE THREAD

**Issue by jtrujill** [HealthCatalyst/Fabric.Cashmere#243]
I was messing around with the NavbarComponent today and couldn't get it to let me put a custom html element in the navbar. I just wanted to style some text and have that get projected into the app icon location but nothing was happening.

Right now it's limiting in that you need to pass a link to an asset instead of being able to define it as html. This issue is also present for the app brand location(tri-flame).

My proposal is to alter Navbar so that you instead have directives that will project the content into the correct location. For example:

### Using images:
```
<hc-navbar>
  <img src="./assets/tri-flame.svg" hcNavbarBrandIcon/>
  <img src="./assets/cqe.svg" hcNavbarAppIcon/>
<hc-navbar>
```

### Using html: 
```
<hc-navbar>
  <img src="./assets/tri-flame.svg" hcNavbarBrandIcon/>
  <div class="app-icon" hcNavbarAppIcon>
    CQE 
  </div>
<hc-navbar>
```

The end result should look about the same:
<img width="122" alt="screen shot 2018-05-10 at 7 11 34 pm" src="https://user-images.githubusercontent.com/5596515/39901497-1b80405a-5486-11e8-9ff7-838ce614f28d.png">

**Comment by benjanderson** [comment]
The idea behind making the component opinionated as I did was to have the navbar consistent through each of the applications. The navbar is one of the most important elements that make are web apps look like a "brand". 

However the `<hc-navbar-icon>` are as you described and allow you to put any html you desire. I do agree with you on the username section, looking back it shouldn't be so restrictive. 

To quote the guiding principles I want to make things "flexible enough to be customized" but firstly a "unified, consistent user experience". An angular component gives developers an interface that they can plug into and things just work. If we want it more customizable I suggest we abstract the css so people can just use pure html and leave the navbar opinionated. If you look at your suggestions, it doesn't have much angular in it. The idea of extracting css from our components give us the best of both worlds while allowing the majority to subscribe to supported components.

**Comment by andrew-frueh** [comment]
I think @benjanderson makes a good point here.  Referring back to our guiding principles of how Cashmere is trying to [unify the user experience across our entire catalog of Health Catalyst applications](https://github.com/HealthCatalyst/Fabric.Cashmere/wiki/Guiding-Principles#what-problems-does-it-solve), the navbar is probably our most central UX element - every app has it.  If you look across all our apps currently, we have a situation where the navbars are all similar, but look and act slightly differently.  And those small differences can be really jarring with something this central.

So I'd argue that if any of any of our components should be more heavily opinionated, the navbar is the one where that is most appropriate.  We mentioned in our steering committee meeting that where it made sense, we should abstract the css for certain components.  And I think Ben's suggestion to do there here would be a good idea.  I actually had to do pretty much that very thing for the dgeni templates I just posted anyway.  So I'd be happy to clean that up and submit a stylesheet for the navbar that could be used in cases where there needs to be something really custom.

**Comment by jtrujill** [comment]
What I'm proposing allows you to still enforce a particular style; however, it allows users more freedom with what gets added into the navbar. Maybe I want to add my own login/user section, currently you can't do that. If you take a look at the source code for the list component it demonstrates what I'm talking about. You can still use named projects that target elements like 

- hc-navbar-link
- hcNavbarBrandIcon 
- hcNavbarAppIcon

With hcNavbarBrandIcon and hcNavbarAppIcon as directives you could apply a css class which would style the elements to match the current style, while also giving users more power.

Using the named projects(`<ng-content select=""></ng-content>`) you'd be able to move the brandIcon, appIcon or NavbarLink where we think they should go. But there should also be a place to project the rest of the html that is within the hc-navbar, using an unnamed projection (`<ng-content></ng-content>`) 

We should not create a separate css file for this solution. It makes use of the library more confusing and requires that we maintain code in two places, which will eventually lead to issues. 

Use of the library shouldn't be fragmented into the use of CSS for one instance and Angular in another. If we have people using css provided by the library but building their own navbar, buttons, drawers... we will fail with the core principal of having a _unified, consistent user experience_. The reason this is troubling is that if everyone is doing their own DOM structure and picking and choosing their own CSS to apply to these components, when the company decides to change the look, those people will be left behind.

The Angular components abstract those details away from the user. They don't need to know the correct css classes or html structure. This allows us to easily change the look of these components because people are working with abstractions. When we remove those abstractions it will make things very difficult. That's why providing CSS as an alternative should not be done

**Comment by jtrujill** [comment]
I created an issue #256 where I talked about creating a hc-tab-link component that could be used in this component to simplify this component. I think this would be a very good idea in order to stay DRY

**Comment by andrew-frueh** [comment]
Just circling back on this one.  I think there are some great topics that have come up in this thread, and we have our next steering committee meeting in less than two weeks.  I'm going to make this our first topic of conversation in that meeting because it can lead to several important decisions not just around the navbar but our approach to components in general.

@jtrujill - just so I don't surprise you, I'll plan on giving you the floor first to summarize your points above, and then we can dig into it.
