### ISSUE TITLE
Tabs title multi-line?

### ISSUE THREAD

**Issue by jtrujill** [HealthCatalyst/Fabric.Cashmere#257]
I think that it looks odd to have the tabs title be multiline since it adds a huge margin to the bottom of all the other tabs. I'm thinking that we shouldn't let text wrap. Here's an example of what it looks like:
![2018-05-20 23_25_17-claims quality explorer](https://user-images.githubusercontent.com/5596515/40292018-e1d0a964-5c85-11e8-8393-7cdeb4b871cf.png)

**Comment by andrew-frueh** [comment]
Also agree - those horizontal tabs shouldn't be multi-line.  So maybe let's add `whitespace: nowrap;` and `overflow: hidden;`?
