### ISSUE TITLE
Add checkbox component

### ISSUE THREAD

**Issue by nickrflynn** [HealthCatalyst/Fabric.Cashmere#26]
I'm working on adding a checkbox component based on one we made for use in Atlas.  Posting here to avoid duplicated work.

**Comment by andrew-frueh** [comment]
Hooray!  @nickrflynn I actually had this on my todo list for this week to put together some html/css for what a checkbox should look like.  How can we work together on this?  Do you want to let me know what branch in your fork you're working on for this, and then I can make visual tweaks and submit a pull request to your fork?

**Comment by nickrflynn** [comment]
Sounds great @andrew-frueh.  I'll let you know when I have a branch in a good state for you to grab.  Might be a day or so though balancing this with other dev work.

**Comment by nickrflynn** [comment]
Branch (named [checkbox](https://github.com/nickrflynn/Fabric.Cashmere/tree/checkbox)) is up if you want to take a look at styling @andrew-frueh.  The component isn't quite ready for a pull request yet but it's close.  It will be a good v1 addition but there will be more we can/should do with it (e.g., read-only support, utilize Angular's ControlValueAccessor, an possible indeterminate state, etc.).
