### ISSUE TITLE
Prettier for a consistent codebase

### ISSUE THREAD

**Issue by jtrujill** [HealthCatalyst/Fabric.Cashmere#261]
I'm interested in keeping a consistent code style and I've been looking at the following [Prettier](https://github.com/prettier/prettier). I'm thinking this will be the way to go and a can get a pre-commit hook set so that it'll run prettier. This will keep our code looking the same and will remove any inconsistencies that IDEs introduce

**Comment by benjanderson** [comment]
We have been using "prettier" on my team and we really like

**Comment by jtrujill** [comment]
I'll get a PR together and look into how we can use a precommit hook. I'm thinking about using [Husky](https://github.com/typicode/husky)

**Comment by jtrujill** [comment]
@benjanderson what's needed to get vscode setup with this? Does a file need to be committed?

**Comment by jtrujill** [comment]
This has been merged into master
