### ISSUE TITLE
Remove vertical tabs

### ISSUE THREAD

**Issue by jtrujill** [HealthCatalyst/Fabric.Cashmere#269]
For a while now I've been thinking that horizontal tabs shouldn't exist. The reason I believe that is that the same thing can be accomplished with the DrawerComponent. It doesn't make sense to have overlapping features and so what I'd like to do is finish the drawer component so that it has an additional mode called 'side' that'll remain open even if the user tries to close the drawer.

Once that is done the whole horizontal part of tabs can be removed.

**Comment by andrew-frueh** [comment]
Could you explain this suggestion a little further @jtrujill?  I'm not sure I understand how the [drawer component](https://cashmere.healthcatalyst.net/components/drawer) and the horizontal version of our [tabs component](https://cashmere.healthcatalyst.net/components/tabs/1) overlap.

**Comment by jtrujill** [comment]
I'm just realizing that I said horizontal tabs when I meant vertical. Sorry, yesterday was a long day doing that conversion to angular/cli@6.0.3. Also what I meant is that that style conflicts with the sideNav. I imagine that most pages will use the sideNav and within the content area it would look odd to have two vertical menus and so I imagine you'd almost always want to use the horizontal tabs.
