### ISSUE TITLE
Deprecated rxjs imports

### ISSUE THREAD

**Issue by jtrujill** [HealthCatalyst/Fabric.Cashmere#271]
I noticed while moving the project to the newest CLI that many rxjs imports are imported incorrectly from 'rxjs' or 'rxjs/Rx' which pulls the entire rxjs library into our project. 

Other issues I saw are that operators are being pulled in like this `import "rxjs/add/operator/take`. This also makes it difficult to perform tree-shaking and is actually deprecated. The new way is described here https://github.com/ReactiveX/rxjs/blob/master/doc/pipeable-operators.md

I'd like to introduce an rxjs linter which validates that we are using the correct imports so that we don't run into issues when angular changes to rxjs 6. Here's a blog describing a linter we could use https://blog.angularindepth.com/rxjs-tslint-rules-for-version-6-d10e2482292d

**Comment by benjanderson** [comment]
according to https://update.angular.io/ these are the steps to follow. I am marking this as a good first issue as its a very straight forward fix

- Remove deprecated RxJS 6 features using rxjs-tslint auto update rules.
- npm install -g rxjs-tslint
- rxjs-5-to-6-migrate -p src/tsconfig.app.json
- Once you and all of your dependencies have updated to RxJS 6, remove rxjs-compat.

**Comment by jtrujill** [comment]
I'll get a PR together by end of day
