### ISSUE TITLE
Upgrade to Angular 6

### ISSUE THREAD

**Issue by jtrujill** [HealthCatalyst/Fabric.Cashmere#276]
When do we want to upgrade to Angular 6? I could do it now without much hassle. If you read the changes that have been done for 6, they all seem to be about dev tooling. I don't think it'd be difficult for developers to upgrade to 6, but before doing this I need to know from those using it if they're in a position to make that upgrade soon

**Comment by benjanderson** [comment]
We are in a position to upgrade to 6 👍

**Comment by corykon** [comment]
PopBuilder upgraded to 6 last week. :+1:

**Comment by jtrujill** [comment]
I'll get a PR together and if we decide that it's okay to move forward with Angular 6 it can be merged in otherwise not a big deal to shelve it until we're ready
