### ISSUE TITLE
Secondary Entry Points with ngPackagr

### ISSUE THREAD

**Issue by corytak** [HealthCatalyst/Fabric.Cashmere#292]
**Describe the problem this feature request is solving**
As per discussion in Cashmere meeting today, the package size appears to be large even when only one module is imported 

**Describe the solution you'd like**
Add secondary entry points to ngPackagr config in order to facilitate the import of just one module by itself

**Describe alternatives you've considered**
We've talked about having only a single entry point like now, only secondary entry points, or a hybrid. 

**If any, which components will have to change, and how**

*   Components changed?
the public_api index may be removed?
*   Are these breaking changes to public interfaces?
yes, this could potentially change the way imports are done if we replace the primary entry point with only secondary entry points. However, if we do a hybrid nothing currently will break. 

**Additional context**
Search for secondary entry points [here](https://github.com/dherges/ng-packagr)

**Comment by corytak** [comment]
Per our phone call discussion, we're going to use the [Webpack Bundle Analyzer](https://www.npmjs.com/package/webpack-bundle-analyzer) to see if this is an issue that needs to be done at all.

**Comment by jtrujill** [comment]
Closing because this doesn't seem worth the hassle
