### ISSUE TITLE
Styling split between .scss files and inline html

### ISSUE THREAD

**Issue by nickrflynn** [HealthCatalyst/Fabric.Cashmere#30]
We are styling inline in the html in some places and in others we are splitting that out into .scss files.  Personally I would prefer to write all css in one place.

**Comment by jtrujill** [comment]
I agree with that. I'm probably a perpetuator of this issue since I basically took a demo components html and copied and pasted and made the necessary changes to that file. Maybe we should come up with a demo scss that we can import into our demo components

**Comment by corykon** [comment]
I'll go do some cleanup

**Comment by benjanderson** [comment]
great job @corykon #86
