### ISSUE TITLE
Radio Button - Documentation Update

### ISSUE THREAD

**Issue by andrew-frueh** [HealthCatalyst/Fabric.Cashmere#308]
Update component code to work with Dgeni doc generation.  See the [project overview](https://github.com/HealthCatalyst/Fabric.Cashmere/projects) for more details.

**Comment by benjanderson** [comment]
The following file was deleted and the contents will need to be transitioned to the new documentation standard

https://github.com/HealthCatalyst/Fabric.Cashmere/blob/a231015e618be05f10c8bb73f41cda070fc63037/guides/components/radio-button.md
