### ISSUE TITLE
Tile - Documentation Update

### ISSUE THREAD

**Issue by andrew-frueh** [HealthCatalyst/Fabric.Cashmere#312]
Update component code to work with Dgeni doc generation.  See the [project overview](https://github.com/HealthCatalyst/Fabric.Cashmere/projects) for more details.

**Comment by andrew-frueh** [comment]
There's actually nothing to update on this one, because this is the simplest of components - it's pretty much a glorified css style; no inputs or public functions.  So the I wonder what dgeni will do if there is nothing for it to generate?  @jtrujill - do you think it will create an empty table, or just not create a table at all (preferable).

**Comment by jtrujill** [comment]
It will still generate some stuff such as the selector the component name the way to import it. If there's nothing to hide then I'd say it's done. I'll take a look and let you know
