### ISSUE TITLE
Cannot commit

### ISSUE THREAD

**Issue by benjanderson** [HealthCatalyst/Fabric.Cashmere#320]
**Describe the bug**
When I try to commit code I get the following error

**To Reproduce**
```
$ git commit -m "added login page styles"
husky > npm run -s precommit (node v8.9.4)

25lRunning tasks for *.{js,scss,css,md,json} [started]
Running tasks for *.{ts} [started]
Running tasks for *.{ts} [skipped]
→ No staged files match *.{ts}
prettier --write [started]
prettier --write [completed]
git add [started]
git add [completed]
Running tasks for *.{js,scss,css,md,json} [completed]
25h25hhusky > npm run -s commitmsg (node v8.9.4)

'commitlint' is not recognized as an internal or external command,
operable program or batch file.

husky > commit-msg hook failed (add --no-verify to bypass)
```
**Expected behavior**
commit without any errors

**Comment by benjanderson** [comment]
after running `npm install -g @commitlint/cli @commitlint/config-conventional` I can commit, but I am still having issues getting the correct commit syntax

**Comment by benjanderson** [comment]
figured it out, but it really should be documented

**Comment by jonest** [comment]
@benjanderson if you look at the last several commits on `master` you'll need to follow that convention where it's something like `fix: message"` or something. I'm on my phone at the moment so it's hard to look! I'm sure the Husky documentation will have some details about how it's set up

**Comment by jtrujill** [comment]
You should only need to install `npm install -g @commitlint/cli` and then you should be able to do the following `git cz` this will walk you through setting the commit message correctly

**Comment by jtrujill** [comment]
git cz is a replacement for git commit, so use git cz to easily write commit messages

**Comment by jonest** [comment]
Oh is it commitizen? For some reason I thought I saw Husky 😃

**Comment by jtrujill** [comment]
Husky helps with git precommit hooks. The linting is tied into the precommit hooks using husky

**Comment by jtrujill** [comment]
I'm going to close this issue since it's been resolved. I've updated the contribution-guide, which could use an overhaul but with so few people showing interest in contributing it's at the bottom of my list. Also this is probably the only thing that could use documentation. Everything else is fairly standard. I'll see about creating an issue to update the contribution.md so that it talks about best practices, committing and getting a dev environment setup
