### ISSUE TITLE
Documentation for multiple options in split buttons

### ISSUE THREAD

**Issue by cedar-ave** [HealthCatalyst/Fabric.Cashmere#333]
There may be a need for more clarification on split button options, particularly when there are multiple items to select.

_Current in Cashmere documentation:_

![2018-06-18 10_27_06-cashmere](https://user-images.githubusercontent.com/15255009/41549217-56e7fd3e-72e2-11e8-82e4-49ce713daf09.png)

_Use case (the way this example is styled is from a pre-Cashmere prototype):_

![2018-06-18 10_28_48-adobe xd cc](https://user-images.githubusercontent.com/15255009/41549267-838228e2-72e2-11e8-8fea-4eaea969ce8f.png)

Thanks.

Edit: Ignore the light blue boxes in the screenshots... they are just from me hovering over items in the Cashmere site or Adobe XD - sorry

**Comment by jtrujill** [comment]
Split button allows for multiple items. There is already a ticket to improve documentation for all components. The button component documentation specifically is being traced by issue #295.

I'll be doing a lot to improve documentation of Cashmere in general such as improving the demos that are available. This is going to be an iterative approach and I'll require help from others with the documentation, but I'll be getting a lot of the infrastructure done.
 
I'm going to close this issue and if you have more to add just post in #295
