### ISSUE TITLE
Cashmere docs

### ISSUE THREAD

**Issue by jtrujill** [HealthCatalyst/Fabric.Cashmere#334]
I've created this ticket so people can track where I am in the process of doing documentation for Cashmere. The only part I'll really need help with is creating demos for the different components. First thing I'll do is create the Stackblitz demo project so that I can get help from people with writing demo files.

### UserGuide Component Section
To make adding a new component easier we need to remove all the components found under `src/app/components` and instead use a single component called `component-viewer` which is routed to with a route like `components/:id` and the `component-viewer` could use the `:id` to determine what component to show.

The `component-viewer` should have a tab component which allows the user to switch between the API documentation and the examples for that component. A config object will be needed to know what examples belong to which component.
 
**UserGuide Components rewrite**
- [x] Create component-viewer (parent element that uses url params to get component info from config object)
- [x] Create example-viewer (provides example source code tab for each demo and provides Stackblitz redirect for the examples)
- [X] API doc render object (renders dgeni generated docs)
- [x] Create a config object which maps Cashmere components to their examples and any other necessary details about the component(used during routing)

**Demo Project requirements**
- [x] Create Stackblitz project
- [x] Generate Stackblitz module for the project(annoying and difficult to maintain for all demos)
- [x] Create a separate demo for each use of a component(place demo at root of project and each demo has its own directory)
- [ ] Create necessary files for Stackblitz to run demos
  - [ ] index.html
  - [ ] main.ts
  - [ ] polyfills.ts
  - [ ] Move these files into a directory under user-guide assets/ during CI publish step
- [x] Serve demo static files(scss, html, ts)
  - [ ] Copy Stackblitz demo's directories into user-guide assets/ during CI publish step
  - [x] Create a component which utilizes tabs to show the source files for a component. Given a demo name it should download the correct source file based on the currently selected tab for the given demo name
- [ ] Add Stackblitz redirect button next to static source code fetcher
  - [ ] On click use [Stackblitz sdk](https://stackblitz.com/docs) to send index.html, main.ts, polyfills.ts along with the demo static files(typescript, scss and html)

**Comment by corykon** [comment]
@jtrujill think we might be able to just close this issue, since we now have #377? maybe migrate any of these detail needed into that newer issue.

**Comment by jtrujill** [comment]
Yeah I'll do that tomorrow and add those steps to the ticket
