### ISSUE TITLE
Input box background color should be white

### ISSUE THREAD

**Issue by jonest** [HealthCatalyst/Fabric.Cashmere#336]
**Describe the bug**
The input box takes the same color as the background, but I _think_ all our mockups have it with a white background, regardless of the container, similar to what the select box has in the demo below.

**To Reproduce**
https://stackblitz.com/edit/cashmere-demo-trmhwv

**Expected behavior**
I'd expect the background of the input box to be white, regardless of what it's contained within, with the option to change the color (not sure how exactly we want to accomplish that).

**Screenshots**
![image](https://user-images.githubusercontent.com/3075414/41624390-878fb542-73e3-11e8-8840-6067495ae856.png)

**Comment by jonest** [comment]
I'm currently looking into this if someone wants to assign me to this @jtrujill @benjanderson @andrew-frueh

**Comment by jtrujill** [comment]
I'm doing some work on the input component at the moment I can sneak that in
