### ISSUE TITLE
`hc-navbar-mobile-menu` has a dependency on the App Switcher

### ISSUE THREAD

**Issue by jonest** [HealthCatalyst/Fabric.Cashmere#340]
**Describe the bug**
`hc-navbar-mobile-menu` appears to have a dependency on the App Switcher. Adding in `hc-navbar` works fine without the app switcher, but adding in `hc-navbar-mobile-menu`, leaving the `appSwitcher` property off or setting to `false` causes this error in the console:

```
ERROR
Error: StaticInjectorError(AppModule)[IAppSwitcherService]: 
StaticInjectorError(Platform: core)[IAppSwitcherService]: 
NullInjectorError: No provider for IAppSwitcherService!
```

**To Reproduce**
https://stackblitz.com/edit/cashmere-demo-a69f58

On this particular page ([navbar.component.html](https://stackblitz.com/edit/cashmere-demo-a69f58?file=app%2Fnavbar%2Fnavbar.component.html,`)) if you uncomment the `hc-navbar-mobile-menu` it will no longer load the page correctly

**Expected behavior**
I wouldn't expect to need the app switcher provided when adding in a mobile menu.

**Comment by benjanderson** [comment]
@jonest you created this bug #280 I believe this is a duplicate of that one

**Comment by jonest** [comment]
@benjanderson you're right! I didn't realize I'd logged this once before :) I'll close it and add the stackblitz link as a comment (plus this is now referenced there).

**Comment by andrew-frueh** [comment]
Reopening this as per the conversation in #426 for @benjanderson to take a look at when he has a minute.
