### ISSUE TITLE
Split button menu item triggers primary button click in addition to it's own click action

### ISSUE THREAD

**Issue by jonest** [HealthCatalyst/Fabric.Cashmere#345]
**Describe the bug**
Clicking on a split button menu item triggers both click events (primary button and the menu item).

**To Reproduce**
https://stackblitz.com/edit/cashmere-demo-oavfrk

Open the console and click on the main button, then click on the dropdown menu item button. Both functions are called when the menu item is clicked, instead of just the menu item function.

**Expected behavior**
I would expect both buttons to trigger their own respective click actions.

**Screenshots**
![image](https://user-images.githubusercontent.com/3075414/41802163-dffd1ac4-764c-11e8-87b2-cb7dde4443eb.png)

**Comment by jtrujill** [comment]
So the reason this happens is that when you click on the menu item it doesn't stop the propagation of the event which ends up reaching hc-split-button. This will most likely require a large change of the structure of the component. Let me think about this over the weekend
