### ISSUE TITLE
Create hc-icon directives for pre-defines icon sizes

### ISSUE THREAD

**Issue by jtrujill** [HealthCatalyst/Fabric.Cashmere#353]
Moving the pre-defined icon sizes to directives instead of css classes has the added benefit of having it be auto-completed by the IDE. This will also allow for better documentation of this feature.

**Comment by corykon** [comment]
A note on this... as I've tried implementing hc-icon I've had problems with the predefined sizes. If one of the three available sizes doesn't work, I'm out of luck because they're styled with `!important`. Wondering if there's a way to be a bit more flexible...

**Comment by jtrujill** [comment]
@corykon It makes sense for them to be defined with !important if one of the predefined size attributes. Doesn't make sense to have that attribute defined and then allow the user to easily override it with some css either by mistake or not. Instead if the predefined sizes don't work in your case you should be able to easily set the size yourself. I don't have ViewEncapsulation on so it's easy to override.

If you need help message me
