### ISSUE TITLE
Input with type `date` overflows out of input box

### ISSUE THREAD

**Issue by jonest** [HealthCatalyst/Fabric.Cashmere#363]
**Describe the bug**
When using the `hc-form-field` with an `input` element of type `date`, the date is pushed off the left side. Using an `hc -icon` `hcSuffix` or not does not affect this behavior.

**To Reproduce**
https://stackblitz.com/edit/cashmere-demo-b7wlzj

**Expected behavior**
I'd expect to be able to see the entire date that I've selected.

**Screenshots**
![image](https://user-images.githubusercontent.com/3075414/42662246-20b90b3a-85ee-11e8-8c71-12eaba7e3e30.png)

**Browser:**

*   Chrome
*   Version 67.0.3396.87 (Official Build) (64-bit)

**Comment by jtrujill** [comment]
Should be a quick fix

**Comment by jonest** [comment]
Cool, any idea when the next release of Cashmere will be?

**Comment by jonest** [comment]
Awesome, thanks!
