### ISSUE TITLE
Horizontal Tabs

### ISSUE THREAD

**Issue by andrew-frueh** [HealthCatalyst/Fabric.Cashmere#37]
Horizontal tabs can be used anywhere, but are most commonly used as a secondary navigational elements on pages that have a limited number of sub pages.  Those with long lists of sub pages are better served using Vertical Tabs.  

**Example of Horizontal Tabs for Secondary Navigation**

![horiztonaltabs](https://user-images.githubusercontent.com/22795893/35474110-dcec57d8-0346-11e8-82da-7e4604b09771.png)

There may also be instances where vertical and horizontal tabs are used together, where the vertical tabs provide secondary navigation and the horizontal tabs provide tertiary navigation.

**Example of Vertical and Horizontal Tabs Used Together**

![horizontalverticaltabs](https://user-images.githubusercontent.com/22795893/35474137-46fcbac8-0347-11e8-8477-df9fe7b104bf.png)

**Comment by jtrujill** [comment]
Could we modify the vertical tabs to take an argument specifying whether it's vertical or horizontal?

**Comment by corytak** [comment]
@jtrujill that's a good question. The general gist of putting the tab's content between the tags and paging between them should be the same. It's just the styling that would change. Based on these two examples it looks like horizontal tabs can have varying background colors. Further, the style guide has a scenario where there's a dark theme and the text needs to be white. The vertical tabs don't seem to have as many flavors.

**Comment by andrew-frueh** [comment]
I'm probably 50/50 on this one - in my brain I see them as two different things, probably because they look so different.  Especially if we get into responsive stuff down the line, it seems like responsive behavior of the horizontal tabs would be pretty different than vertical.  So I think my preference would be to keep them separate, but it's a huge deal for me if others feel strongly about combining them.

**Comment by corytak** [comment]
@jtrujill @andrew-frueh I made [some progress](https://github.com/corytak/Fabric.Cashmere/tree/horizontal-tabs) on combining them together. I generalized the name of the components to be `hc-tab-set` and the `hc-tab`. You can specify the direction on the `hc-tab-set` component. 

This is what it could look like together, but it wouldn't be that big of a deal to create a separate horizontal tabs component either.

**Comment by andrew-frueh** [comment]
Well @corytak - you've made a believer of me.  I think what you've got here looks great.  Thumbs up from me for combining horizontal and vertical tabs into one component.
