### ISSUE TITLE
Vertical Tabs

### ISSUE THREAD

**Issue by andrew-frueh** [HealthCatalyst/Fabric.Cashmere#38]
Vertical Tabs are most often used as a form of secondary navigation on pages that have a large number of sub-pages.  For those with a fixed, smaller number of sub-pages, using @[Horizontal Tabs](https://github.com/HealthCatalyst/Fabric.Cashmere/issues/37) might be more appropriate.  Horizontal and Vertical tabs may be used in conjunction on pages where secondary and tertiary levels of navigation are required.

**Example of Vertical and Horizontal Tabs Used Together**

![horizontalverticaltabs](https://user-images.githubusercontent.com/22795893/35474197-409ad3d0-0348-11e8-895b-1184ebc63f31.png)

In our style guide we depict these tabs with rounded edges on the left side as in the image above.  I'm currently leaning towards a more simplified style that takes up less screen real estate as in this mockup below:

![verticaltabs](https://user-images.githubusercontent.com/22795893/35474217-75abe44c-0348-11e8-9b1e-2eddad0bc49e.png)

**Comment by andrew-frueh** [comment]
Thanks for taking this one @corytak!

**Comment by corytak** [comment]
@andrew-frueh here's [what I've got so far](https://github.com/corytak/Fabric.Cashmere/tree/vertical-tabs). I'd love your feedback on styling as I wasn't sure if the tab should have a box-shadow or on the padding amounts.

**Comment by andrew-frueh** [comment]
This is looking awesome @corytak - well done!  Two minor tweaks, but overall you nailed the styling:
- I think we want to leave a little bit of whitespace above the very first tab like you'll see on [this prototype page](https://xd.adobe.com/view/f0c739fa-f83c-4cf5-ad04-d8f39a419fe7/screen/183af570-387b-4ea1-8ea3-e75df8bfdaa5/Admin)  It keeps everything from running together.  In that mockup, I left 15px above the first tab.
- Also in that mockup, you'll see that I made the selected item's blue thumb flush with the left edge. It looks like your .tab-demo class just has 5px padding on it.  So I'd go ahead and remove that.
