### ISSUE TITLE
Typography Additions

### ISSUE THREAD

**Issue by corykon** [HealthCatalyst/Fabric.Cashmere#390]
**Describe the problem this feature request is solving**
Started switching over to Cashmere styles, and found a few handy typography styles that I use often that probably could/should be in Cashmere.

**Describe the solution you'd like**
The following new classes
- `.hc-text-link`: styled just like `<a>`, but in cases where I don't actually want to use an anchor tag
- Sizes: 
     - `.hc-type-xsm`: fontSize(12px)
     - `.hc-type-sm`: fontSize(14px)
     - `.hc-type-md`: fontSize(16px)
     - `.hc-type-lg`: fontSize(18px)
- Weights (`hc-type-bold` at 600 already exists): 
     - `.hc-type-light`: font-weight: 300
     - `.hc-type-reg`: font-weight: 400
     - `.hc-type-xbold`: font-weight: 700
- Casings:
     - `.hc-type-titlecase`: capitalize first letter of each word
     - `.hc-type-uppercase`: capitalize all letters
     - `.hc-type-lowercase`: all letters lowercase
- `hc-type-ellipsis`:
     -often needed with displaying custom user input, or to help with responsiveness
![image](https://user-images.githubusercontent.com/12416432/43740614-f7202a0c-9988-11e8-9404-d9f4704be72d.png)

**Describe alternatives you've considered**
Could have more/fewer helpers than these... but these are what I use in PopBuilder

**If any, which components will have to change, and how**
Nothing changed, just adding new classes

**Additional context**
...

**Comment by jtrujill** [comment]
- The idea of hc-text-link seems very similar to `<button hc-button color="tertiary"></button>`, do you agree? The hc-button component also has different preset sizes
- The idea of casings should probably be an angular pipe
- I think there is already an ellipsis pipe

If you don't believe that these components cover these cases, could you please describe the cases that you want these features to cover.

**Comment by jtrujill** [comment]
The weights stuff is something that maybe could be useful? @andrew-frueh what do you think about having some standardized weights for font and what values should be used?

**Comment by corykon** [comment]
- `.hc-text-link` is super similar to the tertiary button, buts it's meant to be used inline, without all the built-in extra padding that the buttons have. It'll be exactly the same as the `<a>` tag, just as a helper class
- casings is a built in css attribute, so this is just simple helper class without the overkill of a pipe
- an ellipsis pipe is good when you know exactly how many characters you want, but wouldn't work for those cases where you're looking to be more responsive

**Comment by jtrujill** [comment]
I believe that HealthCatalyst should try to remain follow the idea of [semantic html](https://shapeshed.com/the-importance-of-semantic-markup/) as much as possible. Because .hc-text-link is something that can be clicked but doesn't change the route, we should use a button. hc-button tertiary was designed for this purpose. If the padding and margins need to be changed, then I have two suggestions: 
- Add an additional color property to hc-button (this would stretch the meaning of the color attribute, however)
- Look at a new button link component that doesn't have padding, margin or centered text

For the font and text manipulation shortcuts I like what bootstrap has for naming
- .font-weight-light, .font-weight-reg, .font-weight-xbold
- .text-capitalize, .text-lowercase, .text-uppercase
- .text-nowrap

I don't know if we'd want to scope these to hc or not. I feel that we should leave it off just to keep them shorter

**Comment by corykon** [comment]
The semantic html argument is a good point... although we do already have classes like `.h1`, `.h2`, `.p`, etc, which kind of invite you to break semantics a little bit. Do you think its ok that those are there?

I kind of think the button property being called `color` is already sort of off... what if we made these changes?
- change the button `color` property to be `buttonStyle` (breaking, I know.. so maybe we leave it)
- change "tertiary" option to be called "link" (like how bootstrap does it... it feels WAY clearer)
- create a new option "link-no-padding" (or something like that) to be a link styled button without the extra spacing around it

I'm good with or without the hc namespace on the classes. Brevity is good, and so is safe namespacing...  and I'm not sure which is more important here.

**Comment by jtrujill** [comment]
@andrew-frueh what is the style guide for actions triggers, things that trigger something when clicked?

I can't see a good reason for keeping those header classes, so I'd say we should remove them and put those styles on the html elements that they're replacing. 

I'd actually be okay with changing the color property to something else. What we could do is introduce a deprecated annotation on that property and phase it out over time. This would give people time to make the change. Anyways, what you suggested makes sense and I'd be okay with doing that and it'd be an easy implementation. It would just be some quick css changes.

**Comment by corykon** [comment]
Cool. I like that approach for changing the button property, and I'm good with wiping out the h1, h2 sort of classes. I'll update my PR.
