### ISSUE TITLE
Minor Table Style Issues

### ISSUE THREAD

**Issue by corykon** [HealthCatalyst/Fabric.Cashmere#393]
**Describe the bug**
- Tables without a header are missing their top border
- in `.hc-active-table`, a top row th shouldn't have the blue clickable hover effect by default, because sometimes the headers aren't sortable
- `<th>` should always be bold by default... currently `<th>` tags are only bold in the `thead`, but fairly commonly there are th tags in places other than the top row
- clicking a table cell and giving it focus results in a blue outline... we should probably turn that off by default since there's no usually a reason to tab through or show focus on table cells

**Browser:**
All

**Comment by jtrujill** [comment]
Thanks for finding these issues. I'm implementing the component version of this and I'll be using the styles you created. I'll link back to this issue when I'm done
