### ISSUE TITLE
Accordion background color is always white

### ISSUE THREAD

**Issue by jonest** [HealthCatalyst/Fabric.Cashmere#399]
**Describe the bug**
The accordion background color is always white instead of matching the parent (or perhaps being configurable?).

**To Reproduce**
https://stackblitz.com/edit/cashmere-demo-aysnjq

**Expected behavior**
I'd expect the background to match the container instead of always being white

**Screenshots**
![image](https://user-images.githubusercontent.com/3075414/43788505-cc2eb244-9a2a-11e8-90e3-58a0d71bb7bb.png)

**Comment by jtrujill** [comment]
Rather than introduce some kind of variable, I'll get this setup so it's background color is inherited. If the user needs to change the color they can easily override the background color with css 
```
.hc-accordion-content {
    background-color: <color>;
}
```
