### ISSUE TITLE
Navbar Issues

### ISSUE THREAD

**Issue by corykon** [HealthCatalyst/Fabric.Cashmere#417]
**Describe the bug**
- Alignment of links/icons is slightly off. Should be bottom aligned with the logo.
- Would be helpful if docs mention default value of fixedTop
- App icon should have no hover effect if the app switcher isn't being used

**Screenshots**
![image](https://user-images.githubusercontent.com/12416432/43867308-08387080-9b26-11e8-9f74-22b1d84fd1a2.png)

**Browser:**
All

**Comment by andrew-frueh** [comment]
Cory and I looked at these alignment issues together.  So thumbs up from me on making that change
