### ISSUE TITLE
Deprecate hc-label

### ISSUE THREAD

**Issue by jonest** [HealthCatalyst/Fabric.Cashmere#423]
**Describe the bug**
Not sure if this would be a bug or a feature, but let's go with bug :)

It appears there are two separate `LabelComponent`s. 

The first, which requires `LabelModule` targets elements such as `<label hc-label></label>`.
The second, which requires `InputModule` targets elements such as `<hc-label></hc-label>`.

When using both in the same file, importing `LabelModule` causes an error to be thrown for the `<hc-label></hc-label>` element, whereas importing the `InputModule` appears to cover both.

**Comment by jtrujill** [comment]
I don't mean to hijack your thread but I'm wondering if we should deprecate and remove hc-label. My understanding is that it was to be used to inputs but they now use hc-form-field. Select is the next component to be transferred over to formField.

Is there a use case I'm unaware of? I think if we provide standard label styling it'll be through typography

**Comment by jtrujill** [comment]
@andrew-frueh I believe you were the original creator what do you think

**Comment by andrew-frueh** [comment]
I think you're right @jtrujill that this should probably be deprecated.  The original intent was to be able to have one label that could be used for both select and input components - because as @jonest pointed out, they are very similar.  And yes, we are overdue to address #168 that creates a sass file specifically devoted to forms.

**Comment by jtrujill** [comment]
I'll see if I can get the hc-select working with formField over the weekend through Tuesday. I'm taking a couple of days off from work which will free some time for cashmere
