### ISSUE TITLE
Subheader

### ISSUE THREAD

**Issue by andrew-frueh** [HealthCatalyst/Fabric.Cashmere#43]
The subheader is an optional space, but it very commonly used among Catalyst apps. It is meant to be a flexible area that can be used as per the needs of the application. Some may choose to use it for breadcrumbs, others for secondary navigation, filtering, search, etc.  The most common usage pattern for the subheader is breadcrumbs pinned to the left and one or more buttons pinned to the right.

Because content within the subheader is flexible, the component will need to reflect that.  I'd imagine it would allow the user to define whether the components included in it either belong to the left or right side groups.  But I'd very much appreciate input from @corytak @corykon @jacquie @benjanderson and any others who are making use of the subheader in their apps for their suggestions on configuration options for this component.

<img width="1375" alt="subheaderspec" src="https://user-images.githubusercontent.com/22795893/35475238-2aa12646-0358-11e8-8aad-5e4cafd9f0d1.png">

**Comment by jtrujill** [comment]
Hey @andrew-frueh could if you can get me the design specifics for the header and subheader I can write a component for both of them. 

What I could do for a design is create a toolbar parent component which will act as the main toolbar(header) and then within that I could create a child component that would house the subtoolbar(subheader)

```html
<hc-toolbar>
   <div>Everything other than hc-subtoolbar will be shown in the main toolbar</div>
    <hc-subtoolbar>Anything here will go into the subtoolbar</hc-subtoolbar>
<hc-toolbar>
```

**Comment by andrew-frueh** [comment]
I like the idea of the subheader as a child of the main navbar @jtrujill.  You and @benjanderson should sync up, because Ben has already started working on a component for the navBar - it's currently in the upstream branch called "navbar" I think.  You're absolutely right though that the subheader will never exist in the absence of the main navbar, so it only makes sense that their would be a parent/child relationship there.

As far as the subheader goes, the specs for that are pretty straight forward - you can grab them from the style guide image attached to this issue (Bar: 50px height, etc).

**Comment by andrew-frueh** [comment]
Just remembered one wrinkle to keep in mind when thinking about the subheader.  In most situations it will go full width to match the navBar.  But when using #38 Vertical Tabs (particularly in Admin sections), we've sometimes used the subheader as a way to do secondary navigation within a tab.  So it would be ideal if this subheader component can accommodate both use patterns.

![admin - roles detail](https://user-images.githubusercontent.com/22795893/35485926-ad5894c2-0423-11e8-9a78-2ffe3e1444db.png)

**Comment by jtrujill** [comment]
There are several ways to do this. At a previous job I had created a .less file which provided a grid system similar to what bootstrap provides except that it was based on flexBox. LeadingWisely uses something similar where you can add padding, margin, flex-row...etc. I really like this system and it's something that I think would be great to provide to users of this library.

To answer your question I think this styling should be left out of the component so that the user could either use a scss file that we provide or to use some 3rd-party styling library
