### ISSUE TITLE
Mark library as alpha discussion

### ISSUE THREAD

**Issue by jtrujill** [HealthCatalyst/Fabric.Cashmere#44]
I think we should make it very clear that all these components are in their early stages and that their interfaces and stylings could change. Basically we should discourage it's use until it's more stable. I'd hate for people to do an entire site based on these components only for us to introduce breaking changes causing a complete re-write. 

However, I do think getting the components out their for use would be good to learn what works and doesn't and to help us with testing the components more thoroughly. Maybe people who work on small side projects or some personal project could use these components to give feedback.

**Comment by andrew-frueh** [comment]
You make a good point, and @benjanderson brought this up as well.  I'll make a warning at the top of our demo pages and also add it to the ReadMe that this is currently pre-release and in development.

But you're also correct that we'll need to test out these components in context a bit before we can call a 1.0 release of the library official.  I think this is a perfect topic for conversation at the Cashmere Open Space session next week.  I'll make sure this is at the top of the list.

**Comment by benjanderson** [comment]
I would suggest publishing the npm with the prerelease tag, that makes it clear that it is not release ready

**Comment by andrew-frueh** [comment]
Closing this issue because the conversation picked up on #83
