### ISSUE TITLE
List Component

### ISSUE THREAD

**Issue by jtrujill** [HealthCatalyst/Fabric.Cashmere#45]
I'm going to write a list component that allows you to have 1 or 2 lines of text and an icon or avatar on one or both the left and right side. 

This component will have an outside component and an child component. The outside component will house all the child component and will be in charge of layout. 

The child component will be in charge of laying out the list-items content: text, icon and/or avator

I'm thinking it'll it'll look something like this:

```html
<hc-list>
     <hc-list-item>
          <div hc-avatar></div>
          Main text
          <div hc-subtext>I'm subtext</div>
          <hc-icon class="fa-filter"></hc-icon>
     </hc-list-item>
</hc-list>
```

I'd also like to use this for the side navigation, which I'm also working #42

**Comment by andrew-frueh** [comment]
I could see this being useful in a number of places.  In addition to #42, it could also work really well in #38 and #39 as well.

**Comment by andrew-frueh** [comment]
@benjanderson - I might be remembering wrong, but did you end up writing something like this for your popover component?  And if not, I'm guessing something like what @jtrujill is suggesting here would well for the list of actions that are often displayed in our popovers.
