### ISSUE TITLE
Sorting of nulls feels backward in default DataSource sort

### ISSUE THREAD

**Issue by corykon** [HealthCatalyst/Fabric.Cashmere#455]
**Describe the bug**
When sorting A-Z, the order ends ups like this
1. Nulls
2. 0-9
3. A-Z

**To Reproduce**
1.  Go to [https://stackblitz.com/edit/cashmere-demo-sort-nulls](https://stackblitz.com/edit/cashmere-demo-sort-nulls)
2.  Click on the "name" header

**Expected behavior**
Might just be me, but I'd prefer the default to be like this:
1. 0-9
2. A-Z
3. Nulls

...In PopBuilder, we'd actually always just sorted nulls to the bottom regardless of sort direction, but that might not be the right way to go. **Other thoughts?**

**Browser:**
All

**Comment by andrew-frueh** [comment]
Sorting nulls to the bottom would be the behavior I would expect also.

**Comment by jtrujill** [comment]
It doesn't make sense when you think about it. Why when in ascending order should null be greater than all other values? There is no value so it should come first.

**Comment by jtrujill** [comment]
Doesn't that seem odd that descending order would give you nulls at the top and ascending would give you nulls at the bottom?

**Comment by jtrujill** [comment]
@corykon the provided demo seems to be blank

**Comment by jtrujill** [comment]
If this behavior other than what the default it needed sortData can be overriden on the DataSource

**Comment by jtrujill** [comment]
We should keep what logically makes sense. When I think about this you probably never want to actually show 'null' to a user and instead would want to replace that with some string value, which would render this PR nil

**Comment by andrew-frueh** [comment]
Okay - I'll yield on this one.  Your argument makes sense to me.  And if we've learned anything from our past history with a table component, the way every team handles their data is unique.

But I'd really like to hear from @jacquie @benjanderson and @corykon to make sure we have a consensus before we close this issue/PR.

**Comment by corykon** [comment]
I'm fine if we close it, I can just override.
