### ISSUE TITLE
Support for additional filtering in Table (beyond filtering by search term)

### ISSUE THREAD

**Issue by corykon** [HealthCatalyst/Fabric.Cashmere#459]
**Describe the problem this feature request is solving**
Tables often have various methods of filtering beyond just search. It would be awesome if HcDataSource supported custom filters out of the box.

**Describe the solution you'd like**
A quick fix would be to provide a function in HcDataSource to manually trigger running the filter logic provided via the `filterPredicate` input. 

I've been able to provide a custom filterPredicate that did all the filtering I needed, but I can't trigger it to run without changing the search term or sort order or something.

**Describe alternatives you've considered**
A more robust solution might be adding the ability to pass in an array of custom filter models to HcDataSource. They might look something like this:
```
class HcDataFilter {
    name: string;
    active: boolean;
    filterFunc: (element: <T>, filterData: any) => boolean;
}
```
Then changes to the state of any of these custom filter could trigger rerunning the filter/sorting/paging logic in the same way as is already implemented in `HcDataSources` `_updateChangeSubscription` function, this would just be another stream to merge in.

**If any, which components will have to change, and how**
HcDataSource, as described above.

**Additional context**
Couple common examples that should be supported:
(Mine/All)
![image](https://user-images.githubusercontent.com/12416432/44234157-1e7ad200-a163-11e8-90fb-e9113b07d8b4.png)

(Other Filters)
![image](https://user-images.githubusercontent.com/12416432/44234168-2dfa1b00-a163-11e8-9c1f-c34b6af053f0.png)

**Comment by jtrujill** [comment]
I don't think this is a good use-case for changing the way filtering works. If you need to do complex filtering like you have described above it would be better to filter the data before passing it into the datasource.

You could run your data through all the different filters that you need and pass it into the table which will cause it to re-render your data.  Having multiple functions all filtering the same datasource using a name key to add/remove from the table is complex. On top of that it'll be very slow. When a new filter term is entered in it'll run that query on all of your data again. 

It's easier to do the complicated filtering of your data before passing it to the table and then you can do simple searches of your table by using the default filterPredicate or providing your own

**Comment by jtrujill** [comment]
The filterPredicate is mainly used to tell the datasource what part pieces of the data you passed in should be searched. Maybe you only want to allow searches by an id or maybe id and username. You don't want to add complicated filters to the table

**Comment by jtrujill** [comment]
Closing since filterPredicate is not intended to do complex dynamic filtering of your data. Instead you should filter that data before setting it on the datasource. When you set new data on the datasource, it'll automatically trigger a re-draw of the table
