### ISSUE TITLE
Reactive Forms cannot set value on hc-select

### ISSUE THREAD

**Issue by jkjudd** [HealthCatalyst/Fabric.Cashmere#464]
**Describe the bug**
hc-select does not allow reactive forms to set the value of the underlying select element.

**To Reproduce**
The bug is demonstrated here! Yay!
https://stackblitz.com/edit/cashmere-demo-4erszy?file=app%2Fhome%2Fhome.component.html

**Expected behavior**
We want hc-select to be able to receive values from setValue just like select.

**Comment by andrew-frueh** [comment]
Thanks @jkjudd - likely this will get put at the top of the backlog for next month.  Let us know if this is blocking you and you need a fix sooner.

**Comment by jonest** [comment]
I was curious if I could just use the `writeValue()` method to work around this but that also doesn't seem to work. I'm a little brain dead at the moment so I'm not totally sure if this is a proper demonstration: https://stackblitz.com/edit/cashmere-demo-vqas3t?file=app%2Fhome%2Fhome.component.ts

**Comment by jonest** [comment]
Which part is incorrect? Should it just be the `$event` itself?

We both took off for the evening and we going to reconvene on Monday so no real rush. Thanks though!
