### ISSUE TITLE
Picklist initial value placement

### ISSUE THREAD

**Issue by jtrujill** [HealthCatalyst/Fabric.Cashmere#475]
Is there any way to initially define what pane a value belongs in(available or selected)? I need to use the picklist for filter selection, but if I can't set the selected filters in the correct pane, the client will need to re-add all filers in addition to any new additions

**Comment by jtrujill** [comment]
Do you have a working example of this feature? I've gone through some iterations trying to get it to work and I'm running into a lot of issues. First valueSets must be set or it blows up. When I use reactive forms it doesn't set the initial value of selected values. You must trigger a change for it to update the value else you just get an empty string

```
{
  "selected": {
   "valueSets": []
    "values": []
  },
  "options": {
    "values": [
      {
        "code": "admin_gen_svcs",
        "title": "admin_gen_svcs"
      },
      {
        "code": "ancillary",
        "title": "ancillary"
      },
      {
        "code": "facility_svcs",
        "title": "facility_svcs"
      },
      {
        "code": "intervent_diagnostic",
        "title": "intervent_diagnostic"
      },
      {
        "code": "nursing",
        "title": "nursing"
      },
      {
        "code": "other_clin_svcs",
        "title": "other_clin_svcs"
      },
      {
        "code": "surgical_svcs",
        "title": "surgical_svcs"
      }
    ]
  }
}
```

**Comment by corykon** [comment]
@jtrujill those would be good bugs or enhancements to log! I'm happy to get on a call with you to see if we can work around your issues, but the component and its interface could most definitely use some work...

**Comment by jtrujill** [comment]
I'll probably modify the source code in my project and create a PR for it. Thanks.
