### ISSUE TITLE
Texts get clipped from the bottom for select boxes

### ISSUE THREAD

**Issue by shlok297** [HealthCatalyst/Fabric.Cashmere#478]
**Describe the bug**
While using <hc-select> the text inside the select boxes gets clipped from the bottom. 
For example letters like 'g' and 'y' does not appear fully.

![image](https://user-images.githubusercontent.com/31379055/44675394-a8d9f600-a9ed-11e8-914b-a26fd6a8f5bd.png)

![image](https://user-images.githubusercontent.com/31379055/44675448-cad37880-a9ed-11e8-8c4a-b117dadb5980.png)

**Comment by andrew-frueh** [comment]
Thanks for calling this one out @shlok297.  @corykon pointed this out to me last week as well, but we haven't logged it as a bug yet.

**Comment by andrew-frueh** [comment]
@corykon - I noticed we're not totally out of the woods on this one.  In Chrome and Safari on the Mac, the ligatures of the the longer characters are still getting cut off:
<img width="391" alt="screen shot 2018-10-10 at 12 27 40 pm" src="https://user-images.githubusercontent.com/22795893/46757661-079abc80-cc88-11e8-92f5-d21db46e01b1.png">
Does not appear to be an issue on Firefox however.

**Comment by andrew-frueh** [comment]
Closed in #540
