### ISSUE TITLE
Table styling needs to match styleguide

### ISSUE THREAD

**Issue by jtrujill** [HealthCatalyst/Fabric.Cashmere#480]
**Describe the bug**
Currently the hc-table component isn't being styled correctly

**Expected behavior**
Needs to follow style guide for the table component

**Screenshots**
Current styling:
<img width="1655" alt="screen shot 2018-08-30 at 10 53 29 am" src="https://user-images.githubusercontent.com/5596515/44866615-fb602000-ac42-11e8-82a9-77c36ae19535.png">

**Browser:**

All

**Related**
issue - #412

**Comment by andrew-frueh** [comment]
With the updates in #541 the table component is a pretty close match to the style guide.
