### ISSUE TITLE
hc-checkbox throws an Angular warning if the [disabled] attr is used

### ISSUE THREAD

**Issue by isaaclyman** [HealthCatalyst/Fabric.Cashmere#484]
**Describe the bug**
If you use `<hc-checkbox [formControl]="formControlName" [disabled]="value">`, Angular throws the following warning:

> It looks like you're using the disabled attribute with a reactive form directive. If you set disabled to true when you set up this control in your component class, the disabled attribute will actually be set in the DOM for you. We recommend using this approach to avoid 'changed after checked' errors.

If you use `formControlName.disable()` in the component class, the checkbox doesn't get disabled. If you try to use `[attr.disabled]` instead, which would work on a native checkbox, it still doesn't get disabled.

*The only way to dynamically disable/enable an hc-checkbox which is also a reactive form control is to use `[disabled]`, which is explicitly discouraged by Angular.*

**To Reproduce**

1.  Create a reactive form.
2.  Add an `<hc-checkbox>` component with `[formControl]` and `[disabled]` attributes.
3.  `[formControl]` should refer to a `FormControl` instance in the component class; `[disabled]` can refer to any value.
4.  When the form loads, you'll see the warning in the console.

**Expected behavior**
Either the `<hc-checkbox>` component should be reactive form-aware and respond properly to a `formControl.disable()` event, or it should work with `[attr.disabled]`.

Alternately, the `[disabled]` Input field could be renamed so as not to throw a warning in Angular.

**Browser:**

*   Chrome
*   Version 48

**Additional context**
Angular v5.2.9

**Comment by jtrujill** [comment]
Seems to work just fine https://stackblitz.com/edit/cashmere-demo-sb4tpb

Closing. If the problem persists provide the version of cashmere used and provide a demo
