### ISSUE TITLE
Automatically expand modal width or provide ability to configure

### ISSUE THREAD

**Issue by jonest** [HealthCatalyst/Fabric.Cashmere#485]
**Describe the problem this feature request is solving**
Currently, when displaying data in a modal, there's a maximum width. Once that's reached, the content is cut off (see screen shot below).

**Describe the solution you'd like**
I'd like to either:
- Specify some sort of max width I'd like, or
- Have a modal (or all modals) that will expand horizontally as much as needed until it reaches the edge of the screen (perhaps with a buffer)

**Describe alternatives you've considered**
Currently, I'm overriding some of the CSS to accomplish this:
```scss
hc-modal-window {
  .hc-modal.hc-modal-xl {
    width: auto;
  }
}
```

**If any, which components will have to change, and how**

*   `ModalComponent`
*   `ModalWindowComponent`

**Additional context**
![image](https://user-images.githubusercontent.com/3075414/44935374-a947f900-ad2d-11e8-8a63-717070654bfc.png)
Looks like there isn't a horizontal scroll bar, so I'll log a bug for that.

**Comment by jonest** [comment]
@jtrujill helped me figure out how to target the modal correctly yesterday. Hopefully I've captured this correctly/well enough :)

**Comment by jtrujill** [comment]
So the main problem is that by default if no size is specified in modalOptions it uses medium. Maybe by default the width should be Auto.

The issue with the horizontal scrollbars would be with the modal content.

**Comment by jtrujill** [comment]
In addition to the above it'd be nice if the user could style a specific modal rather than all models with some generic css selector. To achieve that we could apply a user supplied class to the modal. The user would need to put the css definition outside of a an angular component that uses encapsulation or they'd need to use `::ng-deep`
