### ISSUE TITLE
Making required="true" for hc-label does not add ' * ' sign to the label

### ISSUE THREAD

**Issue by shlok297** [HealthCatalyst/Fabric.Cashmere#488]
label hc-label required="true"
-------------------------------------------------------------
making required="true" does not add ' * ' sign to the label

**Comment by jtrujill** [comment]
This is a deprecated component. We'll need to mark it as such in the documentation

**Comment by jtrujill** [comment]
It looks like this component isn't even in the documentation any more. I'll just remove it and get this merged into v3 of the app

**Comment by jtrujill** [comment]
closing since this is no longer a supported component
