### ISSUE TITLE
Resizable table columns

### ISSUE THREAD

**Issue by andrew-frueh** [HealthCatalyst/Fabric.Cashmere#496]
**Describe the problem this feature request is solving**
This is something we uncovered in our HAS user testing that I hadn't previously thought of.  In the Atlas test, the user was looking for a field called "HospitalAccount".  The data set had numerous instances of "HospitalAccount2", "HospitalAccount3", etc.  But because of the width of the column, the content was truncated before the number.  So it was a pretty serious usability issue not to be able to see a wider column.

**Describe the solution you'd like**
For our table component, we should allow users to resize table columns on their own so they can control how much content they see.  This is a good example the functionality I'd be looking for: https://codepen.io/validide/pen/aOKLNo

**Describe alternatives you've considered**
We have tooltips on the truncated cells, but most users missed that, or said it would be annoying to have to do that for every row to try and scan the data.

**If any, which components will have to change, and how**
hc-table; shouldn't be a breaking change

**Comment by corykon** [comment]
This would be REALLY cool. Very unique to see on a web app.

**Comment by andrew-frueh** [comment]
Looks like this is something that has been proposed and is listed as a future enhancement to the Angular CDK table:
https://github.com/angular/material2/issues/8312
No timeline announced, but worth keeping an eye on before we build out this functionality ourselves.
