### ISSUE TITLE
Removing ButtonComponent options

### ISSUE THREAD

**Issue by jtrujill** [HealthCatalyst/Fabric.Cashmere#5]
So this is somewhat related to issue #4, but I didn't want to take over that issue. I feel that the entire Button component's options input could be removed entirely by using the select statement I [mentioned](https://github.com/HealthCatalyst/Fabric.Cashmere/issues/4#issuecomment-351557714)

In addition to defining a different component selection, if we added ng-content to our buttons template it would allow us to grab all of the users html. The benefit of that is that it would function like the standard button element allowing you to specify the text or component like so:

```
<button hc-button>Hello</button>
```
The real benefit of this would come from when you need to incorporate i18n. It would be difficult to pass text that goes through an i18n transformation if you need to pass it through an object. This would also remove the need for the buttonIcon since that could be another component that you could place between the button's tags.

When it comes to the buttonType, I believe that it's more appropriate to use classnames to achieve the same effect. In our sass file we could reference the defined class by using the :host element. I feel the following is error prone and difficult to read:

```
[ngClass]="[options.buttonDisplayed ? '' : 'hide',
			options.buttonType === 'primary' ? 'btn btn-primary': '',
			options.buttonType === 'primary-alt1' ? 'btn btn-primary-alt1': '',
			options.buttonType === 'primary-alt2' ? 'btn btn-primary-alt2': '',
			options.buttonType === 'primary-alt3' ? 'btn btn-primary-alt3': '',
			options.buttonType === 'secondary' ? 'btn btn-secondary': '',
			options.buttonType === 'tertiary' ? 'btn btn-tertiary': ''
			]"
``` 
 
The template should have no logic and by having this logic we would now have to write a unit test to make sure it functions correctly.

For the buttonDisabled we should actually use the predefined attribute of disabled.

We can hook that into our code if we need by creating a getter and setter where the getter looks like so

```
private _disabled:boolean = false;

@HostBinding('attr.disabled')
set disabled(isDisabled) {
     this._disabled = !!isDisabled;
}
get disabled() {
     return this._disabled;
}
```
However the above is most likely not needed since we could use css to achieve the same effect that is currently being done.

I don't feel that buttonDisplayed is needed since the user could do the following

```
<button hc-button [hidden]=[true]>Hola</button>
<button hc-button *ngIf=[true]>Hola</button>
```

For tooltip I mentioned soemthing [here](https://github.com/HealthCatalyst/Fabric.Cashmere/issues/4#issuecomment-351561855) that shows it's not needed

Anyways sorry if this seems a bit harsh

**Comment by corytak** [comment]
@jtrujill Not too harsh at all! All very valid points. I'm hoping that the culture of this project allows people to speak freely and not worry about apologizing for calling things out. 

Agreed about not reskinning native html element functionality. There's no need for a popover/disabled setting if we're able to use the native button and a elements' title/disabled properties. 

Also agreed that passing in the button name wouldn't be necessary if using ngContent. Further by using the attribute selector we don't need to specify an icon (or be dependent on FontAwesome) and are able to use a custom font if we so desire (as discussed in the meeting today). 

I agree with the idea of switching to an attribute selector as it does allow us to remove unnecessary input options and utilize native html element apis. I would like to flesh out the plan around styling a little more in depth.  We could add the styles for the primary, secondary, tertiary, and disabled to the button component's styles or we could just add them to some global scss file. If those styles were added to that style sheet, the argument not to include a button component at all could be made. What are your thoughts about that option? Do we gain anything by having a button component that we could not accomplish with styles alone?

**Comment by jtrujill** [comment]
You make a valid point that we could just have our styles defined in some sort of global scss file; however, I like the idea about keeping it as an Angular component just because that gives you more power. I'm not sure how the button could be expanded upon but I'd hate to take that power from us in the future

**Comment by jtrujill** [comment]
Something I just thought about is that with Angular components it helps to protect your elements styling by applying attributes to your DOM and CSS to make the component's stylings even more specific, emulating shadow dom. 

This leads me to another issue which is should all of our components have ViewEncapsulation? There are benefits and cons to using it. Say we have a library-wide scss file which contains variables that we use in our components, with ViewEncapsulation turned on a user couldn't change one of those variables to alter a components style. This would also help to prevent the user from "corrupting" our component's styles, but it makes the library more rigid.

Now imagine that we have ViewEncapsulation turned off and that library-wide file acts as a styling template that the user has to import in the DOM's head using a link element or through angular-cli.json. This would allow for us to create different style sheets or allow the user to create their own. So there's more flexibility but you loose that benefit of encapsulating your component's styling.

In today's meeting it was mentioned that there are two button sizes. We could create a class called "sm-button" or something better and use CSS to change the button's size. I feel it achieves the best of both worlds, at least in this situation.

I'm torn between what to do because the point of this is to make our apps more uniform and yet I feel that I would come across a situation where I might need to modify the styling of a component slightly. Anyways this is for another discussion

**Comment by corytak** [comment]
There are definite tradeoffs between flexibility and standardization. Erring on the side of ViewEncapsulation turned on would push us toward more standardization with less flexibility and that's the way I'm leaning right now. 

As an aside, ViewEncapsulation by itself would not guarantee that our components always looked identical, we would also want to prefix our class names. E.g. if we define a btn class as 
```
.btn{
  prop1: Y;
  prop2: Z;
}
```
and somebody has already imported bootstrap into their app and it defines a class named btn as 
```
.btn{
  prop1: A;
  prop2: B;
  prop3: C;
}
```
then end result would look like
```
.btn{
  prop1: Y;
  prop2: Z;
  prop3: C;
}
```

In order to avoid this we could prefix our btn class with hc or cashmere so that there are no collisions. 

In looking at [angular/material](https://github.com/angular/material2/blob/master/src/lib/button/button.ts) and [kendo ui](https://www.telerik.com/kendo-angular-ui/components/buttons/button/) there are some additional alternatives to consider:

The angular team creates many directives and components and allows the button type to be specified quite simply by the user despite being a little complex under the hood.
```
<button md-button color="primary">Primary</button>
<button md-raised-button color="primary">Primary</button>
```

The KendoUI team does it a little bit differently by allowing the user to pass a boolean to a `primary` input:
```
<button kendoButton (click)="onButtonClick()" [primary]="true">Browse</button>
```

I feel convinced that a bulky options object will be painful to use and should be removed, but when it comes to styling, I like the approaches of the angular and kendo ui teams rather than relying on classes alone. These approaches seem to place more boundaries on what is allowed with an official hc button.

**Comment by jtrujill** [comment]
I agree with you. I guess I'm worrying about having too rigid of a library but that's kinda what we're trying to achieve. I think that's a good point that having our own property defined for the color makes our button interface more explicit and obvious to the user. 

I also hadn't even thought about how the class could possibly conflict with another definition. I'd hate to have to prefix our classes with hc- and would rather that be an implementation detail that is encapsulated from the user of our library.

**Comment by jtrujill** [comment]
I'll see if I can get a pull request in over the weekend that has the features that we've discussed and we can have discussions about that next week

**Comment by jtrujill** [comment]
I created a pull request #6 which has the updates that we were talking about. The pull request is still a work in progress but this will allow people to see the work that has been done and make suggestions

**Comment by jtrujill** [comment]
I'm going to close this issue since pull request #6 has now been merged in
