### ISSUE TITLE
Formatting issues

### ISSUE THREAD

**Issue by jtrujill** [HealthCatalyst/Fabric.Cashmere#50]
I've noticed that files are being committed that don't match the formatting standards that we have currently have. There seems to be an issue with tslint not identifying a file which doesn't use the correct amount of indent space. That issue can be found here https://github.com/palantir/tslint/issues/2814

I don't know what it's like to use Visual Studio since I use intellij and Rider for my development, but we need to make sure that everyone is correctly configured and that the files look like they are appropriately formatted.

Currently there is tslint and an editorconfig file which specify that the library use spaces with an indent size of 2, so if you're using Visual Studio make sure that it's able to read those two files to get the correct formatting

**Comment by corykon** [comment]
I def may have been part of the problem... I use VSCode, which is set to detect and match indentation, but it's default is 4 spaces.

Curious to know how we landed on 2 as the standard. Was there a strong reason for 2, or a democratic vote that I missed? Happy to change, but 4 is my pref, so I have to ask ;)

**Comment by jtrujill** [comment]
A while ago when I added the formatting stuff I started a discussion to get some conversation going on code formatting. I believe maybe 1 or 2 people responded and they also seemed fine with the 2 spaces

**Comment by waldnercharles** [comment]
I wasn't entirely sure how to create a poll on github, so here's a straw poll for indent preference.

http://www.strawpoll.me/14964094
