### ISSUE TITLE
Refactor Popover Component (remove popper.js)

### ISSUE THREAD

**Issue by corykon** [HealthCatalyst/Fabric.Cashmere#502]
**Describe the problem this feature request is solving**
Getting rid of a dependency on popper.js.

**Describe the solution you'd like**
Instead use the angular cdk overlay.

**Describe alternatives you've considered**
None really, sorry.

**If any, which components will have to change, and how**
Popover component. This may result in interface changes, but hopefully those can be avoided. I'd need to dig in some more to know for sure.

**Comment by benjanderson** [comment]
This is now possible with the new dialogue component see #677 It is a clone of materials own popover component. 

It is a very simple wrapper around built in functionality of the angular cdk. For examples of how to convert controls over see https://material.angular.io/components/dialog/overview

**Comment by corykon** [comment]
#783
