### ISSUE TITLE
(Opt-in) Convert the Button component

### ISSUE THREAD

**Issue by isaaclyman** [HealthCatalyst/Fabric.Cashmere#511]
https://github.com/HealthCatalyst/Fabric.Cashmere/blob/7adc22557ba90a5e17433225e776d4c4e35526af/guides/using-and-customizing-components.md

See https://github.com/HealthCatalyst/Fabric.Cashmere/pull/500/files

**Comment by andrew-frueh** [comment]
hey @isaaclyman - I'm going to redirect you to @corykon on that question.  He recently finished an update to split button and will be the best person to help you out.  Maybe ping him on Slack.
