### ISSUE TITLE
Dropdown/Select component arrow toggle

### ISSUE THREAD

**Issue by jonest** [HealthCatalyst/Fabric.Cashmere#53]
Looking at the style guide v1.3 page 42, the dropbown/select component should have the arrow toggle depending on the open or closed state of the menu:

![image](https://user-images.githubusercontent.com/3075414/35530212-a31ecbde-04f0-11e8-8c01-18dd63cbac88.png)

**Comment by jonest** [comment]
I don't have permissions to assign this to myself, but I've got a fix for this

**Comment by andrew-frueh** [comment]
I'm going to close this one for now while our select component uses the native DOM select.  If we get to a point where we create our own dropdown (as in the image above), then toggling the arrow is definitely something we should do.
