### ISSUE TITLE
Every option in ModalOptions should be optional

### ISSUE THREAD

**Issue by joeskeen** [HealthCatalyst/Fabric.Cashmere#532]
**Describe the bug**
If you use the overload for `ModalService.open` that allows you to pass options, you are required by TypeScript to pass in the `size` option.  As the `size` option defaults to medium, it should be optional.

**To Reproduce**
Reproduce it on stackblitz fork
https://stackblitz.com/edit/cashmere-demo-fpvyku

**Expected behavior**
```ts
this.modalService.open(ModalDemoComponent, { data: this.data });
```
should compile with no issues.

**Screenshots**
![image](https://user-images.githubusercontent.com/12286274/46769517-5147cf00-cca9-11e8-93b2-3203dd20d88a.png)

**Browser:**
N/A

**Comment by andrew-frueh** [comment]
Realized that this was fixed in #555
