### ISSUE TITLE
Tabs: Allow "add tab" button use case

### ISSUE THREAD

**Issue by joeskeen** [HealthCatalyst/Fabric.Cashmere#556]
**Describe the problem this feature request is solving**

We are in the process of converting IDEA from AngularJS / Bootstrap to Angular / Cashmere.  One use case we have that I have discovered Cashmere can't really accommodate (well) at the moment is the ability to dynamically add tabs.  Consider this AngularJS / Bootstrap page:
![image](https://user-images.githubusercontent.com/12286274/47246378-a0cd7f80-d3ba-11e8-872c-1e9d83b8f841.png)
Notice that the tab set allows the user to add tabs by clicking the '+' icon at the right side of the tab set.  There are a few things that make doing this with Cashmere tabs today impossible:

* #548 Can't bind click events to tab headers
* #259 Can't use the 'plus' icon as a tab title (using the `+` character looks super lame)
* Can't programmatically select/activate a tab (or it isn't documented at all)

**Describe the solution you'd like**
I can think of a handful of viable solutions, but this is the one I think would work the best.  Feel free to propose a better way:

Add an option to show an add button (by default `false`).  Then we could surface the `newTab` event to bind to.  The tricky part is we would still have to be able to control which tab is selected programmatically so that the newly created tab can be selected.

**Describe alternatives you've considered**
If the issues referenced above were fixed, we could make the tab header be a plus icon, then create the tab without content and bind it to a click event which modifies the tab list backed by the binding.  This is how I tried to implement it:

```html
<div class="content">
    <hc-tab-set direction="horizontal">
        <hc-tab tabTitle="Details">
            <div class="tab-content">
                Details
            </div>
        </hc-tab>
        <hc-tab tabTitle="Main">
            <div class="tab-content">
                Main
            </div>
        </hc-tab>
        <ng-container *ngIf="application">
            <hc-tab *ngFor="let subset of application.subsets" [tabTitle]="subset.name">
                <div class="tab-content">
                    {{subset.name}}
                </div>
            </hc-tab>
        </ng-container>
        <hc-tab tabTitle="+" (click)="newSubset()">
        </hc-tab>
    </hc-tab-set>
</div>
```

Overall, it feels a bit clunky (having a tab that's not a tab, but rather a button).

**If any, which components will have to change, and how**

*   Components changed? : Tabs
*   Are these breaking changes to public interfaces? not necessarily

**Comment by andrew-frueh** [comment]
@joeskeen - I might have some time next week to help you out with this, especially because it pulls together several other requests on the tab component as you cited.  We already have a Cashmere meeting scheduled on Monday so let's talk then about how we can make this happen.
