### ISSUE TITLE
Create Catalyst Icon Font

### ISSUE THREAD

**Issue by corykon** [HealthCatalyst/Fabric.Cashmere#57]
_...recreating this issue. We've got a nifty icon component now , but still have a desire to roll our own icon font at some point..._

Develop an HC-Icons font to remove our dependency on FontAwesome, GlyphIcons, or any other 3rd party glyph set. This document represents the current best understanding of what icons should be included in this font:

https://spark.healthcatalyst.com/docs/DOC-3157

Please look it over and let us know us know if anything is missing that you currently make use of in your apps.

**Comment by andrew-frueh** [comment]
Reviving this issue in light of some recent conversations with the Atlas and SAMD teams.  There is actually the beginnings of Catalyst icon font already in the works, and I think I can push it over the edge to turn it into a standard set of glyphs for all our apps to leverage.
