### ISSUE TITLE
Custom Catalyst Icon Font

### ISSUE THREAD

**Issue by corykon** [HealthCatalyst/Fabric.Cashmere#58]
_...recreating this issue. We've got a nifty icon component now , but still have a desire to roll our own icon font at some point..._

Develop an HC-Icons font to remove our dependency on FontAwesome, GlyphIcons, or any other 3rd party glyph set. This document represents the current best understanding of what icons should be included in this font:

https://spark.healthcatalyst.com/docs/DOC-3157

Please look it over and let us know us know if anything is missing that you currently make use of in your apps.

**Comment by andrew-frueh** [comment]
@corykon - is this still something we want to do?  I could probably create the font, and it could potentially solve #412.  But I worry that if we only use a subset of FontAwesome and a few others, that there are going to be apps that need icons we're not including.  In that case do we just let them create their own dependency on FontAwesome?  And if they're going that anyway, does that defeat the point of having a custom font?

**Comment by corykon** [comment]
@andrew-frueh Good question. I still think it would be awesome, but it might be easier to justkeep  pointing people to font awesome for now. Personal opinion, I'd push for using FA 5 over 4. I think alot of those just look better.

Also, I've got a batch of custom, healthcare related stuff, and their are several other icons we use in popbuilder that aren't available in font awesome that others may or may not find useful. Perhaps we stick those SVGs (or a font) in a repo or available for download somewhere. Though I suppose if they've not been asked for by anybody yet, maybe they're not really needed?

![image](https://user-images.githubusercontent.com/12416432/44161334-40e4f080-a07a-11e8-81bb-1297a9dbe279.png)

**Comment by andrew-frueh** [comment]
Ah, that's interesting - I bet people would use them if they knew they were available.  So maybe that would be the best use for a Catalyst font - not to replace FA, but for any icons we use that aren't already in FA?

**Comment by andrew-frueh** [comment]
Suggestion from the steering committee is to create a page in Styles called "Icons" that allows the user to download svgs of the standard iconography.
