### ISSUE TITLE
New Button Style

### ISSUE THREAD

**Issue by corykon** [HealthCatalyst/Fabric.Cashmere#585]
![image](https://user-images.githubusercontent.com/12416432/47805587-51157f00-dcfd-11e8-86f3-28f42b772b3b.png)

**Describe the problem this feature request is solving**
A new minimal button style to be used for non-primary functions.

**Describe the solution you'd like**
Dark grey font color for text and icon. Can be just text, or just icon, or both. Has hover effect as shown in screenshot. The height of these button is much smaller than our standard button size (only 20px)

**Describe alternatives you've considered**

**If any, which components will have to change, and how**
new `buttonStyle` in `hc-button`

**Are these breaking changes to public interfaces?**
not breaking!

**Comment by corykon** [comment]
Here's another minimal button style we use and like...

*In context:*
![image](https://user-images.githubusercontent.com/12416432/48291525-077f0f80-e434-11e8-9e7c-499e61678481.png)

*Hover effect:*
![image](https://user-images.githubusercontent.com/12416432/48291532-14036800-e434-11e8-87e7-d9e76748bcfa.png)

@andrew-frueh yea/nay on that one?


```
&.btn-simple {
        color: $gray-600;
        background-color: $white;
        border-color: $gray-300;
        transition: background-color 0.3s, border-color 0.3s, color 0.3s;

        &:hover, &:focus {
            background-color: $gray-500;
            border-color: $gray-500;
            color: $white;
        }
        &:active {
            background-color: darken($gray-500, 10%);
            border-color: darken($gray-500, 10%);
            color: $white;
        }
    }
```

**Comment by andrew-frueh** [comment]
Yeah I agree with you that this one and secondary style are almost identical.  So 👍 on your decision to remove and go with the secondary style in pop builder.
