### ISSUE TITLE
Image Upload Component

### ISSUE THREAD

**Issue by joeskeen** [HealthCatalyst/Fabric.Cashmere#592]
**Describe the problem this feature request is solving**
An easy-to-use control for uploading / cropping / resizing images.

**Describe the solution you'd like**
This is my prototype for the control I'm working on in Atlas:
https://stackblitz.com/edit/cashmere-demo-zjm1su?file=app%2Fimage-input%2Fimage-input.component.ts
This prototype doesn't yet allow you to pass in options, such as aspect ratio and/or desired size(s).  I'll be working on implementing those things shortly.

**If any, which components will have to change, and how**

*   Components changed?: no
*   Are these breaking changes to public interfaces?: no, only adding, although this would introduce an `optionalPeerDependency` of `cropperjs`.

**Additional context**

![image](https://user-images.githubusercontent.com/12286274/47942287-0a6b8480-deb7-11e8-95a8-ade62e5d8c17.png)
![image](https://user-images.githubusercontent.com/12286274/47942306-1a836400-deb7-11e8-8660-4822936d327f.png)
![image](https://user-images.githubusercontent.com/12286274/47942346-40a90400-deb7-11e8-9550-1277488b726e.png)
![image](https://user-images.githubusercontent.com/12286274/47942371-4ef72000-deb7-11e8-868b-fc723649146c.png)
![image](https://user-images.githubusercontent.com/12286274/47942390-5dddd280-deb7-11e8-9536-d30580247fb7.png)

**Comment by andrew-frueh** [comment]
@cikeddy designed UI for a similar component that we'd want to include in this:
https://www.figma.com/file/XAOGcZUspfSvnOaE5pYx6n/CDM-Attachments?node-id=44%3A3622

**Comment by andrew-frueh** [comment]
From @atkulp - 

> important to allow setting optional min/max dimensions with aspect ratio, or absolute dimensions that it resizes to. sometimes the backend can resize, but wants to be sure aspect is right, other times it needs the right number of pixels in the right place
