### ISSUE TITLE
Button Dropdowns

### ISSUE THREAD

**Issue by andrew-frueh** [HealthCatalyst/Fabric.Cashmere#60]
Split Button Dropdowns have a primary action, and then a series of secondary options that can be surfaced by clicking the split arrow.  Below is an example from @corykon in Population Builder.

This button component should closely mirror the main button component, and perhaps we should remove the dropdown option from the main button component?  Then we could call this a "button-dropdown" or "button-select" component and include an option for split button or not.

![buttongroup](https://user-images.githubusercontent.com/22795893/35548725-aadddc22-053e-11e8-86dd-ddde793afde9.png)

**Comment by benjanderson** [comment]
This should be able to use the upcoming popover component #39

**Comment by corykon** [comment]
I think there may still a place for the dropdown option in the normal button. Sometimes everything just belongs in menu. But sometimes, like in the example above, it's helpful to have the primary action (save) available at the surface level, so it's just one click away, while keeping other related actions buried in a menu.

**Comment by jtrujill** [comment]
This is copied and pasted from a code review that I gave Andrew

For the dropdown what I would do is incorporate styling for the popover component. I don't know how the popover component is being written but it could be written so that it has a directive which can be attached to another component or element. When that element is clicked it triggers the popover.

```html
<button hc-button-drop [popover]="myPopover">
  Trigger popover
</button>

<popover #myPopover>
  <div>
    Popover content
  </div>
</popover>
```
Then in the button you could apply styling that adds a dropdown caret or however you'd want that to be styled

**Comment by andrew-frueh** [comment]
I'm with you @corykon - and I agree that we wouldn't want to get rid of a straight button dropdown.  I was just trying to decide if that belongs in the hc-button component.  I'm wondering if it might not to be better to do what @jtrujill is suggesting and have a separate **hc-button-drop** or **hc-button_select** component.

I think Jeremy's suggested code looks good for that - and we could potentially build an option for "isSplitButton" that indicates this should be a split button, and include a way to designate what the primary action of the button is (aside from the split dropdown).

**Comment by jtrujill** [comment]
I'm going to be creating a dropdown button component which implements the above
