### ISSUE TITLE
ButtonSize param

### ISSUE THREAD

**Issue by corykon** [HealthCatalyst/Fabric.Cashmere#612]
**Describe the problem this feature request is solving**
Allow for smaller buttons when needed

**Describe the solution you'd like**
New parameter, `buttonSize`

**If any, which components will have to change, and how**
`hc-button` and `hc-split-button`

**Additional context**
Probably will use something like this:
```
font-size: 14px;
height: 26px;
padding: 3px 10px;
line-height: 14px;
min-width: auto;
```

**Comment by corykon** [comment]
discussed in #611

**Comment by andrew-frueh** [comment]
Also a reminder to update one of the existing button examples to demonstrate this functionality when the parameter is added.
