### ISSUE TITLE
IE 11 Bugs

### ISSUE THREAD

**Issue by corykon** [HealthCatalyst/Fabric.Cashmere#614]
**Describe the bug**
Collection of small styling bugs, in both the demo site and in individual components, only in IE 11.
1) Form field errors don't render correctly.
2) Inputs with prefix or suffix icons aren't aligned.
3) The app switcher icons overlap on one another
4) The picklist search bar isn't as wide as it out to be, is partially covered by the list below.
5) Progress indicator demo's are smushed height-wise, have scrollbars
6) Some table demos have unnecessary scrollbars.
7) Split button styles can get wacky because IE 11 doesn't understand min-width: unset; (Need to use auto).
8) Home page styles are off.

**Browser:**
IE 11

**Screenshots**
![image](https://user-images.githubusercontent.com/12416432/48506737-62837e80-e807-11e8-9889-242a6796827e.png)

**7) Split button styles**
![image](https://user-images.githubusercontent.com/12416432/50310770-4d31ed80-0460-11e9-9a51-d13440f80b82.png)

8) Home page styles are off.
![image](https://user-images.githubusercontent.com/12416432/50310812-72266080-0460-11e9-9e4c-141da23e7a60.png)

**Comment by YaroBear** [comment]
I'll drop this here: https://github.com/philipwalton/flexbugs
We were having some issues with Cashmere's modals, and I think the main issue was with flexbox. Looking at the pictures above, I think most of these could be flex box as well.

**Comment by andrew-frueh** [comment]
Have split this issue into individual issues for easier assignment with the label "IE 11 bug"
