### ISSUE TITLE
Add unit tests for the Typeform-survey component

### ISSUE THREAD

**Issue by jacquie** [HealthCatalyst/Fabric.Cashmere#629]
**Describe the problem this feature request is solving**

**Describe the solution you'd like**

**Describe alternatives you've considered**

** If any, which components will have to change, and how **

-   Components changed?
-   Are these breaking changes to public interfaces?

**Additional context**

**Comment by andrew-frueh** [comment]
Hey @CameronAFaust - I see that you've got code pushed up to the unit test branch for this one that hasn't ever been merged.  Should we get a PR in to close this issue?

**Comment by andrew-frueh** [comment]
Recommending this component be sunset - so unit tests won't necessary
