### ISSUE TITLE
Filter Drawer

### ISSUE THREAD

**Issue by andrew-frueh** [HealthCatalyst/Fabric.Cashmere#63]
@jtrujill got us started on this by creating a drawer component #42.  I'm wondering if we can create an additional component that leverages Jeremy's drawer specifically for filtering.  The reason I think a filter drawer component is worth including is because of how common this use pattern appears in our apps.

In my mind, the way this would work would be something like:
`<hc-filter-drawer visible='false' filterSets='true'>
     <hc-filter target='agePicker'>Patient Age</hc-filter>
     <hc filter target='payerPicker'>Payor</hc-filter>
</hc-filter-drawer>`

_Some additional functionality info below:_
Within the drawer users can save Filter Sets to easily flip between previously saved sets of filter selections. Clicking on a filter row typically triggers a modal with a picklist where specific selections can be made.

The filter drawer integrates with filter chiclets that are visible in header row of the page content next to the button used to open/close the filter drawer. The chiclets tell the user what filters are currently active and allow the user to clear specific filters without opening the drawer.

A clickable prototype to demonstrate the functionality described above is available here:
https://xd.adobe.com/view/5260b164-4d93-4238-8fef-8bde1575f248/screen/9180b57f-a454-46eb-bf46-fe1bbc8a005a/Dashboard-Filters

![35475134-4ac49752-0356-11e8-97d7-031f4a047147](https://user-images.githubusercontent.com/22795893/35576384-12dee732-059c-11e8-9404-24b3cfef970a.png)

**Comment by jtrujill** [comment]
I think we should try to keep this library more general, as a tool for a developer. What I was going to do was create a list component that can be used to generate a list in the filter as you see in the image above.

If we make the library too specific it'll restrict its use and make it more difficult to use. What we can do in the design of our components is style other library components within our library component without introducing new attributes/properties to our components.

**Comment by andrew-frueh** [comment]
You make a fair point @jtrujill - and I completely hear you about general components.  Which is why I think making a drawer component first as you did was the right thing to do.  And having those general components as tools for developers as you said makes perfect sense.  So I'm not advocating that we overwrite the general component with a filters only component.  I'm suggesting we have both.  

And here's why - one of the biggest struggles I have as a single UX director for all of product development is to try and keep consistency across many teams developing their own versions of the same elements.  In addition to increased efficiency, the promise of me being able to sign off on a component once - and then know it'll look the same in every app is extraordinary.  So if I know that there are currently a half dozen versions of our "standard" filter drawer floating around out there right now, that means it's on me to go around to each and try and make them all as similar as possible.  But if it's all one component that everyone is using, I know that if a new app wants to add filtering, they can just leverage the component and I don't have to go spot check the styling to make sure it matches.

So I'm not trying to lock you in a really rigid framework as a developer, and I think having foundational components that you can build on is perfect.  But when it comes to elements that are 95% the same in multiple applications, it would help me a ton to know that all those teams are leveraging the same resource.

**Comment by jtrujill** [comment]
@andrew-frueh I'll get my list component done soon and then I'll get in contact with you to go over the details

**Comment by jtrujill** [comment]
PR #69 implements the list component. I'm going to update the drawer component so that it styles the list like the image above

**Comment by andrew-frueh** [comment]
After a discussion about this today, we decided that our standard advanced filters drawer would be more of a "cookbook" in our documentation to explain how you can assemble Cashmere components into that filter drawer.  @jtrujill is working on some enhancements to the hc-list and hc-drawer components to help facilitate this, and I'll also add a new issue for the filter "chips" or "chiclets" that appear outside the drawer.
