### ISSUE TITLE
Pagination: two way data binding for pageNumber and pageSize broken

### ISSUE THREAD

**Issue by joeskeen** [HealthCatalyst/Fabric.Cashmere#630]
**Describe the bug**

It is easy enough to subscribe to the event for when page number or size changes, using `(page)=""`, but if you don't always want to start with page 1 and page size 20 every time you refresh the page, it gets ugly.

See, you can bind those values into the pagination component using `[pageSize]` and `[pageNumber]`, but if you attach those bindings to the current page size and page number, it quickly becomes an issue.  As soon as the user changes the page, you get the signal from `(page)` telling you to change the page and what the new page number and page size are.  But the `[pageNumber]` is one-indexed (as it would make little sense for page 1 to be 0, page 2 to be 1, etc...), but the number coming out of the event is sometimes zero-based, so the behavior is unpredictable and leads to `ExpressionChangedAfterItHasBeenCheckedError`s.

**To Reproduce**
Reproduce it on stackblitz fork
https://stackblitz.com/edit/cashmere-demo-seiqvh?file=app%2Fhome%2Fhome.component.ts

**Expected behavior**
You should be able to seed the paginator with values for pageSize and pageNumber on load (using data binding, not ViewChild and setting it manually).

**Screenshots**
![image](https://user-images.githubusercontent.com/12286274/48570197-0da43e80-e8c1-11e8-9f64-2eeed6a1cdf8.png)

**Browser:**

-   All

**Additional context**

This worked previously before #594, and is a regression.  Previously the `[(pageNumber)]` was a two-way data binding, and it worked great.  I think we may need to revisit using `[(pageNumber)]` and `[(pageSize)]` instead of having a separate event for `(page)`.

CC @corykon

**Comment by corykon** [comment]
@joeskeen hit me up when you're available and lets look at it together!
