### ISSUE TITLE
Pagination: `Showing` message can sometimes seem weird

### ISSUE THREAD

**Issue by joeskeen** [HealthCatalyst/Fabric.Cashmere#639]
**Describe the bug**
In the Pagination component, when the page size is larger than the total number of items, you can see something like this:

![image](https://user-images.githubusercontent.com/12286274/49102839-17ba2b80-f237-11e8-87e4-9933b735b24b.png)

This looks weird, and could potentially confuse the user.

**To Reproduce**
Reproduce it on stackblitz fork
https://stackblitz.com/edit/cashmere-demo-1ff4zp?file=app%2Fhome%2Fhome.component.ts

**Expected behavior**
When total number of items < the page size, display `all` in the drop-down instead of the configured page size.

**Screenshots**
![pagination_all_of_10](https://user-images.githubusercontent.com/12286274/49103068-a333bc80-f237-11e8-991c-3a37743624ba.png)
![pagination_20_of_10](https://user-images.githubusercontent.com/12286274/49103072-a62ead00-f237-11e8-890e-0362f9e8f7b5.png)

**Browser:**

-  all

**Additional context**
Note that this shouldn't actually change the value of the page size, only displays to the user that they are seeing all the items.  Still allow the user to click on the page size dropdown to both see the current page size and select a different page size.

**Comment by andrew-frueh** [comment]
Great suggestion @joeskeen.  👍 from me.
