### ISSUE TITLE
Pagination doesn't limit table rows to pageSize

### ISSUE THREAD

**Issue by bvanfleet** [HealthCatalyst/Fabric.Cashmere#651]
**Describe the bug**
I'm working to implement a table with both pagination and sorting. However, neither are working. I've followed the tutorial, but I feel like I'm missing something.

When I load up the app and navigate to where the component is used, a table is displayed, but with all rows showing. E.g. if the `pageSize` is set to 5, and the table has 6 items, it shows all 6 items and 2 pages. Navigating to other pages doesn't change the view.

The sort also doesn't work, although that's secondary to this bug and can be submitted separately later.

I did find in a separate use of the component in my actual project that if I add an element to the component, then paginator works as expected. However, the use case I'm focusing on is a history table that loads upon user sign-in (and therefore static).

**To Reproduce**
I've isolated the component I'm getting the issue with in a separate GitHub repo [here](https://github.com/bvanfleet/TransactionTable)

It should work out of the box, as far as clone, install, `ng serve`.

I've tested this in both Chrome and Edge (I don't have FireFox installed on this machine) and the behavior is present in both browsers. I also don't see any errors in the console on either browsers.

**Expected behavior**
A table is displayed with the limited number of items defined by `pageSize`.

**Browser:**

-   Browser Chrome
-   Version 70.0.3538.110

**Browser:**

-   Browser Edge
-   Version 41.16299.785.0

**Additional context**

Fabric.Cashmere version 3.3.0

```
ng version


Angular CLI: 7.0.7
Node: 8.11.3
OS: win32 x64
Angular: 7.1.1
... animations, cdk, common, compiler, core, forms
... platform-browser, platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.10.7
@angular-devkit/build-angular     0.10.7
@angular-devkit/build-optimizer   0.10.7
@angular-devkit/build-webpack     0.10.7
@angular-devkit/core              7.0.7
@angular-devkit/schematics        7.0.7
@angular/cli                      7.0.7
@angular/compiler-cli             7.0.4
@angular/language-service         7.0.4
@ngtools/webpack                  7.0.7
@schematics/angular               7.0.7
@schematics/update                0.10.7
rxjs                              6.3.3
typescript                        3.1.6
webpack                           4.19.1
```

**Comment by corykon** [comment]
@bvanfleet, I think I've found the issue.

In `transaction-table.component.html`, things worked for me when I changed line 10 to this:
`<div [hidden]="!datasource || datasource.data.length == 0">`.

The issue was that when ngOnInit() in the component file executes, the paginator and sort components are undefined, because they aren't yet on the page due to the *ngIf that was on line 10. 

Hopefully that helps!

**Comment by bvanfleet** [comment]
Changing from `*ngIf` to `[hidden]` was able to get it working properly. It was also able to fix an issue I was having with sorting too.

**Comment by andrew-frueh** [comment]
Thanks for the response @corykon.  And @bvanfleet - just want to make sure you know about our #cashmere slack channel as well.  So if you have any questions as you're working with the library, we're all on there also and you can usually get a pretty quick response from someone.
