### ISSUE TITLE
Should have option to auto close navbar dropdown after clicking to navigate

### ISSUE THREAD

**Issue by corykon** [HealthCatalyst/Fabric.Cashmere#652]
**Describe the problem this feature request is solving**
After navigating to a page from the user dropdown of the navbar, I have to manually click away to close the dropdown. This feels a bit off. An option in the popover to close on click would help.

**Describe the solution you'd like**
A new option on the popover. Granted... we may want to hold off on this until swapping out the old popover for a new one that uses the CDK overlay.

**Describe alternatives you've considered**
For now, I'll manually trigger the close() function when clicking on the popover, but this seems like a bit of manual work that many devs will want to repeat.

**If any, which components will have to change, and how**
Popover, add an option with something about closing when an option is clicked.

**Additional context**
![mustclickaway](https://user-images.githubusercontent.com/12416432/49537352-0354df00-f886-11e8-9e03-f0648ac02f5b.gif)

**Comment by andrew-frueh** [comment]
This issue has been addressed on `hcPop` by setting the `autoCloseOnContentClick` property to true.
