### ISSUE TITLE
Navbar responsiveness can cut off navigation links

### ISSUE THREAD

**Issue by njwhc** [HealthCatalyst/Fabric.Cashmere#671]
**Describe the bug**
At some resolutions (or when resizing the browser), Navbar links can run off the page or get hidden underneath items on the far right.

**To Reproduce**

1. Go to https://cashmere.healthcatalyst.net/guides/getting-started
2. Open your developer console
3. Resize your browser window to 775px (or similar) wide

**Expected behavior**
Navbar links would not be cut off by right container or run off the page.

**Screenshots**

Gif of browser resizing:

![cashmere-navbar](https://user-images.githubusercontent.com/30876456/50852499-e441e500-133c-11e9-8dbf-f4824f3ccd44.gif)

![image](https://user-images.githubusercontent.com/30876456/50853464-8b278080-133f-11e9-9a1f-232bd1174a38.png)

**Browser:**

-   Browser: Chrome 
-   Version: 71.0.3578.98

**Comment by njwhc** [comment]
I'm curious if this is a version issue. Testing again locally on another project, I find that the latest version of Cashmere is wonderfully responsive. That is, the above described issue is much better, but still happens to some extent.

**Comment by jacquie** [comment]
This is a timing issue - the calculations for the element widths are sometimes made before the app logo img has time to load so the wrong value for its width is used.

**Comment by jacquie** [comment]
Additionally, if you start out with a narrow screen before loading the app so the hamburger is displayed, the elements for the nav-links are not available for the initial collecting of their widths.

**Comment by jacquie** [comment]
Another thing we have noticed is that the right hand links aren't added to the mobile menu.

**Comment by njwhc** [comment]
> Another thing we have noticed is that the right hand links aren't added to the mobile menu.

For reference:

![image](https://user-images.githubusercontent.com/30876456/51211851-f50dd000-18d3-11e9-8a4c-364faad6af8a.png)

![image](https://user-images.githubusercontent.com/30876456/51211857-f808c080-18d3-11e9-889d-d8de9b533812.png)

![image](https://user-images.githubusercontent.com/30876456/51211907-1a024300-18d4-11e9-9e84-13f1a9f4e8a0.png)

**Comment by jacquie** [comment]
PR #681 fixes the first issues here where the 'More' menu doesn't show up soon enough. It needed to wait for the app logo to be loaded before its width could be incorporated in the available space for menu items could be calculated.

Also if you started with the mobile navbar the available width for the full navbar width was calculated too soon as 0 so again the 'More' wasn't being displayed.

The adding the right links to the mobile menu issue has been worked on in LeadingWisely by @njwhc and I think he will be able to add his code here to fix it here too....

**Comment by benjanderson** [comment]
Resolved with #681

**Comment by corykon** [comment]
Looks like responsiveness is a problem again:
![image](https://user-images.githubusercontent.com/12416432/67425201-d2ac8f80-f594-11e9-9ff0-897f0bdcf487.png)
