### ISSUE TITLE
Separate out menu from split button

### ISSUE THREAD

**Issue by joeskeen** [HealthCatalyst/Fabric.Cashmere#676]
**Describe the problem this feature request is solving**
The recent changes to the split button allowing a drop down menu are awesome!  Only issue is, this type of menu is useful outside of the context of the split button, particularly with icon buttons.  

**Describe the solution you'd like**
Separating this out into its own thing that is used by both the split button and any other buttons would make it much more useful.

**Describe alternatives you've considered**
See #567 

**If any, which components will have to change, and how**

-   Split button
-   add new Menu component

**Comment by andrew-frueh** [comment]
Probably will roll this in to #961 - because if we're updating our standard for the help menu, it should probably leverage the new standard menu component.
