### ISSUE TITLE
When using tables styles, icons should be base64 encoded instead of relying on FontAwesome

### ISSUE THREAD

**Issue by corykon** [HealthCatalyst/Fabric.Cashmere#678]
**Describe the problem this feature request is solving**
Title pretty much says it

**Describe the solution you'd like**
Base64

**Describe alternatives you've considered**

**If any, which components will have to change, and how**
Tables.scss

![image](https://user-images.githubusercontent.com/12416432/51623340-b68c9c80-1ef5-11e9-901b-87f159555dad.png)

**Comment by andrew-frueh** [comment]
@corykon - I'm pretty sure I've already taken care of this in #663.  I just looked back through tables.scss and I think I've got everything base64 encoded.  I'm not seeing any instances of 'fa' in there.  Maybe I'm missing something?

**Comment by corykon** [comment]
@andrew-frueh I thought you had too, maybe I'm not on a new enough version. Just checked and I'm on 3.4.1, maybe that fix was in 3.4.2.

**Comment by andrew-frueh** [comment]
Ah yup, just checked the issue page and that's definitely it.  It was part of 3.4.2.

**Comment by corykon** [comment]
back in business 👍 sorry about that.
