### ISSUE TITLE
Ability to freeze headers on a fixed height table

### ISSUE THREAD

**Issue by corykon** [HealthCatalyst/Fabric.Cashmere#685]
**Describe the problem this feature request is solving**
Something we do in a table on PopBuilder, may or may not be something other teams need.

**Describe the solution you'd like**
Maybe two new parameters for the table:
maxHeight: number
freezeHeaders: boolean

Or, a new wrapper component that holds holds the table.

![freezecolumnheaders](https://user-images.githubusercontent.com/12416432/52016224-37710880-24a1-11e9-86f9-6a215557f533.gif)

**Comment by andrew-frueh** [comment]
Review #734 related to this.  There is currently a `sticky` value on the columnDef.  Should make sure we follow similar syntax for a header row.

**Comment by andrew-frueh** [comment]
#889 is also related
