### ISSUE TITLE
Multi-select Dropdown Component

### ISSUE THREAD

**Issue by iamboo** [HealthCatalyst/Fabric.Cashmere#689]
Inline element that appears as a button and provides a dropdown list of selectable items that can be part of a form.

FEATURES:
- Input for the settings below
- Show checkbox when items are selected in multi mode
- Select all option in the top of the list
- Fixed position for the search input

SETTINGS/CONFIG:
- List of objects
- Enable search - filter the loaded list if search api is not defined
- Single or Multi select
- Unselected button label (Select Period, All Types, All Codes, etc.)
- Search API URL
- List item property for main label, sub-label, badge
- Select All option boolean
- (click) action

**Comment by andrew-frueh** [comment]
Thanks for adding this @iamboo.  I could imagine there being a variety of elements that a dev might want to use to trigger this enhanced dropdown - different types of buttons, maybe an input box suffix, etc. So do you think the best way to go is with a directive that can be added to any element?  Sort of like:
`<button hc-button buttonStyle="primary-alt" hcDropdown="#myEnhancedDropdown">`

Also, wondering if we need to have any specific considerations for mobile with this?  Probably if we just use the Angular CDK's overlay similar to what @benjanderson did on Datepicker, it'll probably be fine.  Just figured I'd ask though.

**Comment by iamboo** [comment]
@andrew-frueh That is a great idea.  This could be triggered from many element types.  This is just the starting point for requirements.  Before coding begins, I need to gather feedback and compare config to the current dropdown component that is being used in CORUS.  Please share any additional thoughts.  Thanks!

**Comment by benjanderson** [comment]
For an example of how to create a popover the angular cdk way see the datepicker. Here is the line of code that is helpful. https://github.com/HealthCatalyst/Fabric.Cashmere/blob/00e6df09e24f7232de90b4f41a95eb16b4f011cc/projects/cashmere/src/lib/datepicker/datepicker.component.ts#L375

**Comment by corykon** [comment]
@andrew-frueh should we close this issue now? Called themed ng-select good enough.

**Comment by andrew-frueh** [comment]
Agreed @corykon
