### ISSUE TITLE
Homepage styling is broken

### ISSUE THREAD

**Issue by andrew-frueh** [HealthCatalyst/Fabric.Cashmere#697]
**Describe the bug**
IE 11 visual bug

**Screenshots**
<img width="1196" alt="screen shot 2019-02-06 at 10 37 54 am" src="https://user-images.githubusercontent.com/22795893/52361416-718b5e80-29fb-11e9-9336-5480185871d4.png">

**Comment by corykon** [comment]
You'll want to watch the mobile breakpoints too... the cashmere logo gets smushed at a certain point
![image](https://user-images.githubusercontent.com/12416432/52362288-76511200-29fd-11e9-94df-eb6304b5843b.png)
