### ISSUE TITLE
Table Styles Issue: Dashed borders

### ISSUE THREAD

**Issue by corykon** [HealthCatalyst/Fabric.Cashmere#700]
All browsers appear to show dashed borders for tables that don't have borders around every cell. Looks like styles are spilling over from a font awesome style sheet.

![image](https://user-images.githubusercontent.com/12416432/52362751-77cf0a00-29fe-11e9-86a2-17bca205ab9b.png)

**Comment by andrew-frueh** [comment]
This might be a happy accident @corykon - I actually like the dashed borders.  I vote to keep them.  What do you think?

**Comment by corykon** [comment]
@andrew-frueh Haha, it doesn't look bad - I guess that's your call. Does a dashed border communicate anything differently than a solid border? Would a lighter border have the same effect?

If you do want to purposely go with dashed borders on that kind of table, we'd still have to make a tweak. The dashed borders are showing up on the cashmere site because of some style leakage, but don't actually happen for someone implementing the library (I don't think).

**Comment by andrew-frueh** [comment]
Hmmm - I don't know that it communicates anything different, probably just entirely a matter of aesthetics.  I tried it with a solid border of that same lighter color and I think you're right - that works just as well, and maybe is a little less out there.  So yeah, maybe that's the change to make here - is to adjust that divider on the "no border" table to `!important` with the lighter color.  I'll submit a PR for that.
