### ISSUE TITLE
IE 11: Typography Styles page has flexo logo missing

### ISSUE THREAD

**Issue by corykon** [HealthCatalyst/Fabric.Cashmere#701]
Go to https://cashmere.healthcatalyst.net/styles/typography.
Where's the image? :(

![image](https://user-images.githubusercontent.com/12416432/52362840-b238a700-29fe-11e9-85ce-af9ac2a7d9f5.png)

**Comment by andrew-frueh** [comment]
Hey @corykon - I was just checking this one on BrowserStack, and it seems to be showing up for me on Windows 10 with IE11.  Could you check this one again and see if it's resolved - or if it's an intermittent thing?

<img width="1147" alt="screen shot 2019-02-07 at 9 35 18 am" src="https://user-images.githubusercontent.com/22795893/52426813-ef16a380-2abb-11e9-9409-f2fa4adfd5df.png">

**Comment by corykon** [comment]
@andrew-frueh I just retested and it looks good :+1: Not sure what must have happened, but I'll close this for now
