### ISSUE TITLE
IE 11: Why is there a date showing at the bottom of the Cashmere website?

### ISSUE THREAD

**Issue by corykon** [HealthCatalyst/Fabric.Cashmere#706]
Go to any page, scroll to the bottom:

![image](https://user-images.githubusercontent.com/12416432/52363921-25dbb380-2a01-11e9-9130-21e308f2cfd1.png)

**Comment by andrew-frueh** [comment]
I noticed this cropping up with the new navigation changes as well in Chrome/Firefox.
