### ISSUE TITLE
Formal Design Review

### ISSUE THREAD

**Issue by jtrujill** [HealthCatalyst/Fabric.Cashmere#72]
I would like to get some kind of a formal design review process that would help to get more people involved during the design phase. It would be great if we could have more people participate in the design so that knowledge and consistency could be transferred. It would also to help flesh the component out a bit more than having one person design it and submitting a pull request.

On the ACO Finance team we've implemented a requirement that before you can begin coding you must submit a design document for the team to review and make comments on. This has helped us with knowledge transfer, consistency and really helped us to think about the different use cases or issues that could pop up.

I'm proposing that we have something similar where you give a basic use of the component in html to see what the final use would be, list it's inputs and outputs and what interfaces are going to be implemented(ControlValueAccessor). 

What I don't want to do is get into the nitty gritty details of implementation but instead want to focus on the components interface, since that is what is going to be used, and is what makes changes most difficult.

What are your ideas?

**Comment by andrew-frueh** [comment]
I think this is an excellent idea, especially as this library matures and becomes our standard.  A couple questions about how you're doing this on the Finance team:

- Do you have a template for what a design document should look like or include?
- Would you imagine that an issue would be created first identifying a need for a particular component?  And then the design document, and follow up discussions would take place within that issue before development begins?

**Comment by jtrujill** [comment]
I don't have a design doc template, but that would be nice if someone could create a markdown design template.

I would imagine that an issue would first be created and then as a team we could discuss if that component is needed or not. We could have just a general discussion to determine what we need from it. 

Then I believe it would be best if someone volunteered to write the design doc, and after which, we would have a discussion to make sure it meets our requirements and if the interface looks good. 

Again, someone else would then volunteer to implement the component following the design doc and if there are any issues/concerns they'd post that in the original issue for the component. After the implementation is done the people doing a code review would be in charge of making sure the design doc was followed and looking for any general mistakes or improvements that could be made

**Comment by corytak** [comment]
I like this idea a lot but also want to make sure that we consider how to balance this need for process with making contributing to the library very accessible to newcomers. My worry is that the more processes and red tape that are in place, the less likely it is that someone will contribute. Perhaps we could counteract this by fostering a culture that errs on the side of being helpful if someone doesn't follow all of the procedures exactly. E.g. someone submits something without a design document or creating an issue, instead of just denying it and linking them to our contribution guidelines, we could help them create a design doc and step them through the process.

**Comment by benjanderson** [comment]
@jtrujill I am new to having those design docs as a part of the process. Could you provide an example so I have a better idea how it all works?

**Comment by isaaclyman** [comment]
A common practice on GitHub repos is that before an individual contributor (i.e. not an official project maintainer) writes any code, they create an issue detailing their intentions (a design document). It includes:

- Why a change is needed
- Whether it's a bug fix or a new feature
- Which files are going to be modified
- Which public interfaces will have to change, and how

This doesn't need to take longer than a couple minutes, and we can make it easy by using GitHub [issue templates](https://help.github.com/articles/creating-an-issue-template-for-your-repository/). Then a maintainer adds a tag to the issue (to the effect of `go-ahead`), the fix or feature is implemented, and a pull request is submitted. If we keep the issue template small and explain the process in a root-level `CONTRIBUTING.md` or in the README, it shouldn't create too much friction for newcomers, especially if you're really hands-on about explaining the process and being helpful.

I'm all for inclusivity and low barriers to entry, but this library needs to be predictable and mature if the whole company is going to use it. The only way to get there is with a process that ensures all changes are planned out ahead of time and well-vetted before merging.

**Comment by corytak** [comment]
@isaaclyman that sounds like a great plan! @jtrujill, are you cool if I close this issue and create another issue for creating an issue template?

**Comment by jtrujill** [comment]
Makes sense. I would quote Isaac's comment from above when creating a new issue
