### ISSUE TITLE
Popover is hidden when displayed inside an element that doesn't have visible overflow

### ISSUE THREAD

**Issue by jacquie** [HealthCatalyst/Fabric.Cashmere#728]
This might be more of  a feature request.  We wanted to use the Cashmere popover on our LeadingWisely dashboards, but they get cut off because they are inside gridster elements which don't display overflow.

The popover we are currently using is based on popper.js which I know was eliminated from the Cashmere popover. What it does allow however is the option to attach the popover to the `<body>` tag which gets us over our problem.

It would be great if this option could be added to the Cashmere popover.  Possibly even better would be the option to attach it anywhere up in the DOM hierarchy from where you initiate it?

**Comment by corykon** [comment]
I've run into this problem too! I think this would be taken care of by dropping popper.js and instead using CDK stuff. https://github.com/HealthCatalyst/Fabric.Cashmere/issues/502

**Comment by corykon** [comment]
There's a brand new popover  #783
