### ISSUE TITLE
IE11 does not respect `sticky` on Table Footers/Headers

### ISSUE THREAD

**Issue by jkjudd** [HealthCatalyst/Fabric.Cashmere#734]
**Describe the bug**
When using ***IE11***, if a table has a `sticky` attribute applied to the footer or header, the user will not experience a `sticky` footer or header. The footer or header will scroll with the rest of the table.

**To Reproduce**
Reproduce it on stackblitz fork
https://stackblitz.com/edit/cashmere-demo-mbwqv1?file=app%2Fhome%2Fhome.component.html
https://cashmere-demo-mbwqv1.stackblitz.io

1.  Create a cashmere table with a sticky header and/or footer
2.  Put a set height on the table so scrolling will show the sticky header or footer as sticky
3.  View in IE11
4.  Notice the header and footer is not sticky

**Expected behavior**
Sticky footer/headers are relied upon, and HC supports IE11. Sticky footers/headers should appear to function the same to users no matter the browser.

**Browser:**
Internet Explorer 11

**Additional context**
Sticky Footers can be worked around by not using them, but sticky headers are especially needed because they cannot be worked around if they do not function.

**Comment by corykon** [comment]
IE11 no longer supported as of Cashmere 13.
