### ISSUE TITLE
Tabs - ability to set the default tab

### ISSUE THREAD

**Issue by andrew-frueh** [HealthCatalyst/Fabric.Cashmere#754]
**Describe the problem this feature request is solving**
Adding this on behalf of @jonest and the Ops Console team - who are creating their tabs dynamically and don't want a tab clicked event thrown on their first tab automatically.

**Describe the solution you'd like**
Potentially add a parameter called `defaultTab` that a user can set to tell the app what tab to select on display.  And if that parameter is set to `null`, no tab will be selected by default.

**If any, which components will have to change, and how**
Tabs

**Additional context**
@jonest - feel free to add any additional color commentary that I may have missed.

**Comment by jonest** [comment]
No additional details, though I just had the thought about whether it might make more sense to just have it be a directive on the tab you want selected instead of telling the tab set which number to select. I think that would change a bit of the code around (and require a directive to be created)
