### ISSUE TITLE
Enhance tabs to allow deep links/set active tab

### ISSUE THREAD

**Issue by corytak** [HealthCatalyst/Fabric.Cashmere#76]
User feedback with the tabs module: tried to see if they could get it to work in their app, but need the ability to set the active tab based on the route. Unsure of best implementation/route, but wanted to log the issue as an enhancement.

**Comment by benjanderson** [comment]
To put in my two cents, the navbar just uses the built in [RouterLink](https://angular.io/api/router/RouterLinkActive), I thought that was a pretty good option

**Comment by corytak** [comment]
@andrew-frueh, @corykon I followed @benjanderson 's suggestion and incorporated the router link. I swapped out our sidenav for the tabs and while it works, I feel like some of the styles in the demo components became less appealing. 

![image](https://user-images.githubusercontent.com/9749465/35824614-9dccdc4a-0a70-11e8-8421-1109da02d4a1.png)

![image](https://user-images.githubusercontent.com/9749465/35824632-a97d9d22-0a70-11e8-98a8-5edd67924bbd.png)

Right now the vertical tabs are opinionated in the background color of the content displayed, but perhaps we don't force the gray background color and do something like this: 
![image](https://user-images.githubusercontent.com/9749465/35824485-3bf6701c-0a70-11e8-8ce3-93255fdcf2b0.png)

Conversely, we can consider using the sidenav as is, providing additional themes for vertical tabs, force the tab content to specifically state their background color so it's not inherited from the tabs, etc. 

My current thought is to leave the sidenav as is, but I'd like to discuss this with you. Here's my branch if you want to interact with it: https://github.com/corytak/Fabric.Cashmere/tree/tabs-router

**Comment by corykon** [comment]
I agree it could use some love in one way or another, but I'll defer to @andrew-frueh on the styling. On a separate note - it would be nice to keep the division of "styles" and "components".

**Comment by andrew-frueh** [comment]
@corykon - I was thinking we could potentially do two separate navbar items for "Styles" and "Components" then they would have two separate sets of tabs, which could help because our list is starting to get pretty long (and still growing).  Any concerns with that approach?

**Comment by corytak** [comment]
@andrew-frueh in addition to adding a separate tab for styles, what are your thoughts about tab-content styling. Should we be prescriptive about the gray background color or are there potentially other styles that could accompany vertical tabs?
