### ISSUE TITLE
Add ability to pass in application version information to Typeform Survey

### ISSUE THREAD

**Issue by TonyCurtisLives** [HealthCatalyst/Fabric.Cashmere#768]
When feedback is received it is important to know which version is in use. It can also be helpful to know which versions of dependent services are in use. Currently there is no record of the version(s) in use included with the survey feedback.

It would be great if we could pass in a parameter to the Typeform Survey control to allow information to be annotated to the survey data. It could either be added to the free text portion of the survey, or added in some other way. The parameter should either allow formatted text or allow an array of information that could be formatted into separate lines to make the information about multiple dependent service versions more readable. This would likely also require a change to the survey itself, but not sure on that.

Could ask the user to enter the version in the free text feedback form, but the user doesn't usually know what version they are using, and certainly not the versions of the dependent services or what those services even are.

-   Typeform Survey changes to allow a (non required) parameter to be passed in. Should be a non breaking change since it is not required.
-   Actual survey page (administered outside Cashmere) would need to receive the annotation, preferably as an optional parameter so it is not a breaking change.

**Comment by andrew-frueh** [comment]
Great suggestion @TonyCurtisLives
