### ISSUE TITLE
The Typeform survey component doesn't work in Leading Wisely production builds

### ISSUE THREAD

**Issue by jacquie** [HealthCatalyst/Fabric.Cashmere#769]
The typeform survey works perfectly in our Leading Wisely dev environment, but throws the error
"cannot read property 'makePopup' of defined" 
on a prod build.

**Comment by jacquie** [comment]
So the issue here is XSS and we needed to add two items to our Content Security Policy - 
one in `script-src` for `https://embed.typeform.com/embed.js` that runs the survey code and one in `frame-src` for the uri that you give it for your particular survey.

We should add a note to the guide for this component to let users know they'll need to do the same.

**Comment by andrew-frueh** [comment]
Nice debugging, @jacquie.  Can you submit a PR with an update to the markdown file for the component that mentions all that?

**Comment by jacquie** [comment]
Sure! I was thinking at the bottom of the API section
