### ISSUE TITLE
Split Readme / Contribution Guide

### ISSUE THREAD

**Issue by joeskeen** [HealthCatalyst/Fabric.Cashmere#77]
When a user finds @healthcatalyst/cashmere on npmjs.com, they are presented with the Readme for the library:

![image](https://user-images.githubusercontent.com/12286274/35650262-b763eaa8-0698-11e8-8acf-48368987966f.png)

This doesn't tell them how to install the package, dependencies, browser support, or much of anything else about it.  As NPM users are mostly interested in consuming than contributing, it would be good to gear the Readme towards that audience, and have a separate `contributing.md` linked from the readme.

**Comment by joeskeen** [comment]
Some ideas for the Readme page:

* status badges powered by shields.io
* installation instructions
* browser support
* dependencies (or just generally that it is UI-framework-agnostic)
* license
* troubleshooting
* link to contribution guide

**Comment by jtrujill** [comment]
This is an old issue but I'm still seeing things that should not be shown to the user of our library. We should not have any information about running a demo app like the below image shows:
<img width="834" alt="screen shot 2018-05-22 at 8 19 50 pm" src="https://user-images.githubusercontent.com/5596515/40400083-cc91b51a-5dfd-11e8-94b0-fafe3af0f50b.png">

Either we need to provide a readme specifically for NPM or cleanup the readme that we are using for our github repo. It's just incorrect to show an npm user `npm start` when that will not start the demo app.
