### ISSUE TITLE
HcCellResizer was not found in '@healthcatalyst/cashmere' error

### ISSUE THREAD

**Issue by jonest** [HealthCatalyst/Fabric.Cashmere#785]
Seeing this error when I run `ng build --prod --build-optimizer` on our project:

![image](https://user-images.githubusercontent.com/3075414/55979555-b035d300-5c4f-11e9-8a44-6efdb6904b8c.png)

**Comment by andrew-frueh** [comment]
Hey Ty, that's a strange error.  Are you seeing `cell-resizer.component.ts` in projects/cashmere/src/lib/table?  And can you double check that `index.ts` in that table component is including HcCellResizer?

**Comment by jonest** [comment]
Looking at the definition file there in our node_modules folder, it looks like it's there

**Comment by jonest** [comment]
I ran that command again and didn't see the same issue so I'm going to close this out.
