### ISSUE TITLE
Remove Tri-Flame icon etc.

### ISSUE THREAD

**Issue by joeskeen** [HealthCatalyst/Fabric.Cashmere#81]
One of the main things about having an open-source project sponsored by HealthCatalyst is keeping what should be open open, and our 'secret-sauce' out of it.  Inclusion of anything proprietary makes it seem that it is freely usable by anyone worldwide for any reason under the Apache 2.0 license.

This being said, we should remove the tri-flame HealthCatalyst logo (perhaps replacing it with a cashmere favicon-like icon), and remove other traces of proprietary things (like app names in the app switcher demo, etc.).

**Comment by andrew-frueh** [comment]
@imranq2 - I'd be curious to hear your thoughts on this regarding how your approaching Catalyst branding in other Fabric GitHub libraries.  I think Joe makes a good point, and the only place where we're including the tri-flame is in the navBar.  So we could certainly do as Joe suggested and make the navBar logo generic in the component, but rely on any Catalyst developers to swap in the tri-flame svg.  It's one extra step away from being totally plug and play, but only a very minor inconvenience.  What do you think?

**Comment by jtrujill** [comment]
This would be easy to modify. We could create a directive which is only used for content projection called hc-navbar-icon then in the nabar we could have a ng-content which selects hc-navbar-icon and places it in the left corner. This would allow the user to use any icon. I'd have to look at the implementation of navbar but that's how I'd do it

**Comment by jtrujill** [comment]
I believe the tri-flame has been removed from the navbar so I'm closing this
