### ISSUE TITLE
Cannot download icons set on demo site

### ISSUE THREAD

**Issue by benjanderson** [HealthCatalyst/Fabric.Cashmere#834]
**Describe the bug**
When downloading the icons set from https://cashmere.healthcatalyst.net/styles/icons you get an invalid download 
![image](https://user-images.githubusercontent.com/1934453/56591603-42ba6880-65a6-11e9-9edc-a62e36d991db.png)

Looking into it the link 
https://cashmere.healthcatalyst.net/assets/hc-icons.zip 

should be

https://cashmere.healthcatalyst.net/assets/hcicons.zip

**Comment by andrew-frueh** [comment]
Gah - can't believe I missed this one.  Thanks @benjanderson, will fix now.
