### ISSUE TITLE
Icon Font v1.1

### ISSUE THREAD

**Issue by andrew-frueh** [HealthCatalyst/Fabric.Cashmere#837]
Adding this issue as a place to collect suggestions and comments on the Catalyst icon set.  

https://cashmere.healthcatalyst.net/styles/icons

My intention is to update the font in versions as we would with any component, so it will be clear to all team members what and when is changing in our iconography.

**Comment by andrew-frueh** [comment]
Suggestion for **hc-medical**

"One very, very minor criticism I have is that it uses the Caduceus (rod with two snakes and wings) for the symbol of medicine. Enough organizations have confused this for the Rod of Asclepius (rod with one snake) that they've become synonymous in many people's minds, but the latter is the correct symbol."

http://www.kristenelisephd.com/2013/10/what-difference-snake-makes-caduceus.html
https://www.premiumcaremd.com/blog/the-battle-of-the-snakes-staff-of-aesculapius-vs-caduceus

**Comment by andrew-frueh** [comment]
**Suggestion for addition**

Include the unique Catalyst filters icon.  It's currently in a CSS class here:
https://cashmere.healthcatalyst.net/components/drawer/examples

**Comment by andrew-frueh** [comment]
Collision on **hc-error**

naming collision with an existing class

**Comment by corykon** [comment]
Suggestion on folder icons:
I often use the closed and open folders as buttons that toggle back and forth, so its nice to have them set up in a way that switching between them is nice and smooth. I'm worried the new folder icons won't look quite as good when toggling as the icons I'm currently using.

![folder-icons](https://user-images.githubusercontent.com/12416432/56609940-9ee3b380-65cb-11e9-91b5-8200dc9ac721.gif)

(current icons are first, new hc-icons are second)

**Comment by corykon** [comment]
PopBuilder's population doesn't feel like it fits super well with the other db icons:
![image](https://user-images.githubusercontent.com/12416432/56610100-f2ee9800-65cb-11e9-94ad-91160baec617.png)
![image](https://user-images.githubusercontent.com/12416432/56610126-feda5a00-65cb-11e9-8a80-067f9643496d.png)

There is def a case where some icons that are solid (filled in) work better in certain scenarios (link in popbuilder, we use the population icon for filters over a colored circle. So maybe its fine? Just something that jumped out.

![image](https://user-images.githubusercontent.com/12416432/56610222-2d583500-65cc-11e9-9229-38242162fbfb.png)

**Comment by corykon** [comment]
Another thought, from a comment I saw about the skip icon. Maybe we could something that looks more like the queued icon.
![image](https://user-images.githubusercontent.com/12416432/56610825-a015e000-65cd-11e9-965e-9391ad93a0d4.png)

Bottom left was my quick and dirty, could make something that look alot nicer.

**Comment by corykon** [comment]
Could these clipboards be made look a more similar?
![image](https://user-images.githubusercontent.com/12416432/56611010-01d64a00-65ce-11e9-9f53-dba61a770732.png)

![image](https://user-images.githubusercontent.com/12416432/56611028-0dc20c00-65ce-11e9-8fa8-fdf8abea1297.png)

**Comment by corykon** [comment]
Looks like these strokes need to be merged:
![image](https://user-images.githubusercontent.com/12416432/56611221-81fcaf80-65ce-11e9-9ad3-d9f5c5040477.png)

**Comment by corykon** [comment]
hc-patient and hc-doctor are very similar in shape, but not quite the same
![image](https://user-images.githubusercontent.com/12416432/56611321-bd977980-65ce-11e9-8b95-dfd56daae9cd.png)
![image](https://user-images.githubusercontent.com/12416432/56611353-cdaf5900-65ce-11e9-966c-011864328069.png)

**Comment by andrew-frueh** [comment]
Include app switcher icon that we're using in our hc-navbar

**Comment by andrew-frueh** [comment]
Health Catalyst's commonly used Data Operating System illustration includes several concepts that we're touching on in this icon set, and a few others that should be considered:
![image001](https://user-images.githubusercontent.com/22795893/56679954-73240480-6683-11e9-8b1b-de59173c5758.png)
