### ISSUE TITLE
Toast throws an error if you click to close while it's fading

### ISSUE THREAD

**Issue by isaaclyman** [HealthCatalyst/Fabric.Cashmere#849]
**Describe the bug**
If you click a toast while it's fading, a console error will appear:

![image](https://user-images.githubusercontent.com/9139369/57255574-67382b00-7011-11e9-90d5-7dcd44d3f366.png)

**To Reproduce**

1.  Go to https://cashmere.healthcatalyst.net/components/toaster/examples
1.  Set the timeout to a non-zero number, e.g. 2000
1. Check "Allow clicks to dismiss toast"
1. Click "Display toaster message"
1. Double-click the toast, OR wait for the timeout to expire, then click it as it's fading.

**Expected behavior**
The first ending event (expiration of timeout or clicking to dismiss) will close the toast, and further events will have no effect on that toast.

**Browser:**

-   Chrome
-   Version 74

**Additional Context:**
I'm guessing @andrew-frueh will know what's going on here.

**Comment by isaaclyman** [comment]
Also worth considering: if you call `.close()` on the same HcToastRef more than once, you see the same error.

**Comment by andrew-frueh** [comment]
another good catch @isaaclyman - I'm on it

**Comment by isaaclyman** [comment]
Thanks, hopefully an easy fix.
