### ISSUE TITLE
Popover flickers with center/center alignment and hover trigger

### ISSUE THREAD

**Issue by jfrseeley** [HealthCatalyst/Fabric.Cashmere#861]
When the Popover is configured with "center" vertical alignment, "center" horizontal alignment, and "hover" as its trigger, hovering over most positions invokes an endless cycle of show/hide.

1.  Go to https://cashmere.healthcatalyst.net/components/pop/examples
2.  Scroll down to "Popover Overview"
3.  Change "Vertical Alignment" drop-down to "Center"
4.  Ensure "Horizontal Alignment" drop-down is set to "Center"
5.  Change "Trigger" drop-down to "Hover"
6.  Hover over "Trigger" button.
7. Flickering will begin for most hover positions.

The popover should show and _not_ block the hover event. No flickering.

![PopoverHoverWithCenterCenter](https://user-images.githubusercontent.com/17434477/57484298-e625a180-7265-11e9-8164-30f1dd4abf65.gif)

-   Chrome
-   Version 74.0.3729.131

I considered adding `pointer-events: none;` to the CSS, but found the div with class `cdk-overlay-pane` has an explicit style with `pointer-events: auto;`. Using browser tools to switch this to none appears to solve the problem, but I was only able to test this with a "click" trigger, due to the element's dynamic nature in the DOM.

**Comment by andrew-frueh** [comment]
@jfrseeley thanks for submitting this issue!  Take a look at the above PR (#994 ) and let me know what you think.
