### ISSUE TITLE
Modal observable not returning values when closed

### ISSUE THREAD

**Issue by benjanderson** [HealthCatalyst/Fabric.Cashmere#866]
**Describe the bug**
When creating a modal, you can subscribe to the result when it is closed. This observable never gets called, no matter how the modal is closed

**To Reproduce**
Reproduce it on stackblitz fork
https://stackblitz.com/edit/cashmere-demo-ah1ils?file=app%2Fmodal%2Fmodal.component.ts

**Screenshots**
![2019-05-17 14 31 50](https://user-images.githubusercontent.com/1934453/57954581-899f3380-78b0-11e9-908c-626da4fc120b.gif)

**Browser:**
-   Chrome 74

**Comment by jonest** [comment]
This is really bizarre to me since we're using the modals quite a lot in Ops Console and haven't seen any issues

**Comment by jonest** [comment]
I couldn't help put investigate after @joeskeen pinged me about this. @benjanderson it looks like you need to use the `this.activeModal.close()` method with a value in order to have it returned.

**Comment by jonest** [comment]
See the demo here which will give you the alert: https://stackblitz.com/edit/cashmere-demo-jdjsam

**Comment by Techgeekster** [comment]
.close() doesn't return the value because it's filtering out all null values.  Once I removed that filter, it started working again.

**Comment by Techgeekster** [comment]
Care Management Documents feature doesn't return a value with the modal because it won't use a value, it just uses the subscription to then reload data after the modal closes.  Filtering out null values should be up to the user that implements the modal component, in my opinion.

**Comment by jonest** [comment]
> Filtering out null values should be up to the user that implements the modal component, in my opinion.

There was something really strange when this component originally was created where the `null`s being returned were giving us some problems, but I can't remember exactly what it was. I believe it was sending `null` when you first opened the modal and also `null` if you clicked off the modal, but I think that was fixed since then (and the `skip` isn't really necessary anymore).

**Comment by jonest** [comment]
> I agree, filtering is better handled by the user, but it shouldn't return `null` when it first opens.

I probably could have done a better job fixing this originally 😆 Time constraints though 😛

**Comment by Techgeekster** [comment]
> > I agree, filtering is better handled by the user, but it shouldn't return `null` when it first opens.
> 
> I probably could have done a better job fixing this originally 😆 Time constraints though 😛

Oh you are good!  I completely understand.  I'm just glad it's an easy fix!

**Comment by jonest** [comment]
@Techgeekster Might be good to double check that it doesn't still send `null` when it opens when that `skip` is removed :)
