### ISSUE TITLE
Need Co-branding available on the navbar

### ISSUE THREAD

**Issue by Notsoutah** [HealthCatalyst/Fabric.Cashmere#875]
**Describe the problem this feature request is solving**
Our clients want to co-brand the HC applications and prominently display their logo on all the application, including leading wisely dashboards and reports.

**Describe the solution you'd like**
We want the Cashmere navbar to have a configurable section below the existing navbar to allow a user to co-brand by the addition of their logo and limited text or slogans

**Describe alternatives you've considered**
We have attempted to accommodate this within LW, but it does not address the consistency the client is looking for, nor does it allow the co-branded logo to be a prominent part of the NavBar

https://files.slack.com/files-pri/T04807US5-FJYPM5AQM/screen_shot_2019-05-23_at_4.28.22_pm.png
![image](https://user-images.githubusercontent.com/50970630/58344162-311ce880-7e12-11e9-9ce4-2d01178f70e4.png)

** If any, which components will have to change, and how **

-   Components changed?
Cashmere Navbar
-   Are these breaking changes to public interfaces?
Unknown

**Additional context**

**Comment by andrew-frueh** [comment]
@Notsoutah - it's only taken a year, but it looks like this one is moving to the top of the stack.  @corykon has some mockups we're going to align with the approach we've taken on co-branding our new BI templates.  Thanks for championing this one!

**Comment by corykon** [comment]
Couple quick mocks-

Ideally, if we can get an all white logo from the client, we'd do something like this:
![Pop List – 4](https://user-images.githubusercontent.com/12416432/76558318-b2f20700-6462-11ea-94dc-55bc760654bb.png)

If not, the right side of the navbar can just be white:
![Pop List – 1](https://user-images.githubusercontent.com/12416432/76558317-b2597080-6462-11ea-9a7e-39c337c029b2.png)
