### ISSUE TITLE
Documentation of Datepicker date implementation is unclear

### ISSUE THREAD

**Issue by njwhc** [HealthCatalyst/Fabric.Cashmere#884]
![image](https://user-images.githubusercontent.com/30876456/58639048-62366680-82b3-11e9-9853-adb0e2eb1013.png)

A few thoughts for consideration on the above documentation...

1. Are additional pre-made modules supposed to be listed after `HcNativeDateModule`?
1. Should `HcNativeDateModule` be described as imported from `@healthcatalyst/cashmere` instead of `@angular/material`?
1. If the use of `MomentDateAdapter` is so highly encouraged, why are there no examples of it's usage? Few people read documentation. Fewer read it thoroughly. I have to assume fewer still are going to read the documentation so thoroughly to see this note and then adapt every example in the rest of the documentation to accommodate this guidance.

I hope you'll forgive me for being nitpicky and griping about seemingly minor things here. However, little stumbling blocks like these make me want to just walk away from Cashmere. After all, if a library isn't easy to use or its documentation is unclear, why should I bother with it?

**Comment by andrew-frueh** [comment]
@njwhc thanks for calling this out a while back, somehow this got lost in the while but just recently was brought back to our attention.  I have a PR (#1199) currently in to clean up those docs, which admittedly were pretty rough.  If you have a second to look over the changes - and have any additional recommendations, I'd very much appreciate the input.  Thanks!
