### ISSUE TITLE
Angular 8 Support

### ISSUE THREAD

**Issue by joeskeen** [HealthCatalyst/Fabric.Cashmere#887]
**Describe the problem this feature request is solving**
Angular 8 is finally out, and has some great new features, such as smaller bundle sizes.  It would be great to get Cashmere up to date with the latest Angular version.

**Describe the solution you'd like**
Run `ng update` on Cashmere and test it out.

**If any, which components will have to change, and how**

-   Components changed? unknown, but probably not
-   Are these breaking changes to public interfaces? unknown, but probably not

**Additional context**
Official announcement:
https://blog.angular.io/version-8-of-angular-smaller-bundles-cli-apis-and-alignment-with-the-ecosystem-af0261112a27

**Comment by joeskeen** [comment]
Also, it would be good to see if enabling Ivy makes a difference to our Cashmere components as well.

**Comment by andrew-frueh** [comment]
Resolved in version 7.0.0
