### ISSUE TITLE
Sticky table headers aren't well-documented

### ISSUE THREAD

**Issue by isaaclyman** [HealthCatalyst/Fabric.Cashmere#889]
**Where does our documentation fall short?**

It's hard to figure out how to make a table header/footer sticky.

**What would you add or change?**

A snippet like the following would clear things up:

```html
<!-- Regular table header -->
<tr hc-header-row *hcHeaderRowDef="columnList"></tr>
<!-- Sticky table header -->
<tr hc-header-row *hcHeaderRowDef="columnList; sticky: true"></tr>
```

An example of a sticky table header with a Stackblitz would be even better.

We should also note that (needs testing to confirm) this doesn't work when using `*hcHeaderRowDef` on an `<ng-container>` element, which is the common implementation of multiple header rows. It only seems to work on `<tr>` elements.

**Comment by jacquie** [comment]
I am doing some work using Cashmere tables and needed to use the `when` predicate for the `hcRowDef` directive.  There is no documentation for that either and I had to go and look for it in the cdk documentation.

**Comment by isaaclyman** [comment]
@jacquie do you have the link handy to where you found that information?

**Comment by jacquie** [comment]
It's here https://material.angular.io/cdk/table/api in the `CdkRowDef` section.
I found an example of it's use here: https://stackblitz.com/edit/material2-rc0-6drmzf?file=app%2Fapp.component.html
