### ISSUE TITLE
HcTable Sort documentation is elusive

### ISSUE THREAD

**Issue by isaaclyman** [HealthCatalyst/Fabric.Cashmere#891]
**Where does our documentation fall short?**

Some of the most relevant information about sorting an HcTable (e.g. implementing your own custom sort function) is only present in Table > Usage > Features > Sorting, instead of Sort > Usage, where I would expect to find it.

**What would you add or change?**

Does it really make sense for Table and Sort to be separate pages? Is either useful without the other? If so, we should move all information relevant to sorting to the Sort page, then link to it from the Table page.

An example of a custom sort function would also be very helpful.

**Comment by andrew-frueh** [comment]
Closing this issue as its symptomatic of the greater documentation overhaul work indicated in #1034
