### ISSUE TITLE
hc-icons fontset doesn't seem to be working

### ISSUE THREAD

**Issue by njwhc** [HealthCatalyst/Fabric.Cashmere#892]
**Summary**

It seems that icons from the hc-icons fontset are not working.

**Reproduction**

Steps to reproduce:

1. Add an hc-icons icon: `<hc-icon fontSet="hc-icons" fontIcon="hci-drag" hcIconSm></hc-icon>`

Stackblitz reproduction: https://stackblitz.com/run?file=src/app/icon-overview/icon-overview-example.component.html&hidedevtools=1

**Additional context**

Here is a screenshot of the [example StackBlitz](https://stackblitz.com/run?file=src/app/icon-overview/icon-overview-example.component.html&hidedevtools=1) linked from the [Icon component](https://cashmere.healthcatalyst.net/components/icon/examples) documentation:

![image](https://user-images.githubusercontent.com/30876456/59875620-6f98bb00-935e-11e9-9da0-601855fd53fc.png)

**Comment by corykon** [comment]
I think `cashmere-examples\src\project-template\src\styles.scss` probably just needs a reference to hc-icon.

Something like:
```
$hc-icons-font-path: '../dist/cashmere/hcicons';
@import 'hcicons/hcicons';
```
