### ISSUE TITLE
The single-row chip component is unpleasant to look at

### ISSUE THREAD

**Issue by isaaclyman** [HealthCatalyst/Fabric.Cashmere#894]
**Summary**

![image](https://user-images.githubusercontent.com/9139369/60212195-dd8d2880-981d-11e9-8adc-3b1a40abe86d.png)

This looks bad to me. Does it look bad to anyone else?

**Reproduction**

Steps to reproduce:

1. Visit https://cashmere.healthcatalyst.net/components/chip/examples
2. Look at the "Chip Singlerow" example

**Comment by andrew-frueh** [comment]
Hah, you're gonna have to give me a little more help on this one @isaaclyman.  What is it about the look that you don't like.  It was designed to be used in a situation like the one below where filters are selected from a side drawer, and then the row of chips indicates the filters that have been selected.  

<img width="666" alt="Screen Shot 2019-06-26 at 3 14 42 PM" src="https://user-images.githubusercontent.com/22795893/60215616-42984c80-9825-11e9-93e2-07506aaff245.png">

**Comment by isaaclyman** [comment]
Fair enough. In your screenshot it looks great. In mine, there's an unnecessary scrollbar and the "...more" is flush with the edge of the scrollbar. Just kind of sketchy-looking, and possibly makes the library look less mature than it really is.

Is this a documentation-only issue, then? Is that fixable?

**Comment by andrew-frueh** [comment]
Ah gotcha, yeah the scrollbar shouldn't be there - that's definitely a bug.  Interestingly enough, the scrollbar doesn't show up on Mac Firefox or Mac Chrome.  I'll take a look in BrowserStack and see if I can figure out what's going on.
