### ISSUE TITLE
hc-navbar-link remains in active hover state after click

### ISSUE THREAD

**Issue by andrew-frueh** [HealthCatalyst/Fabric.Cashmere#90]
The dark blue background remains behind a navbar-link after a click, but will fade after a click anywhere else on the page.  @benjanderson - you might know easily how to fix this, but anyone else feel free to jump in instead.

**Comment by benjanderson** [comment]
I still see this issue happening. Here is my environment

Version 61.0.3163.100 (Official Build) (64-bit)
Windows 10

**Comment by benjanderson** [comment]
![2018-02-13 14 05 12](https://user-images.githubusercontent.com/1934453/36173675-0592a9e8-10c7-11e8-8cdb-9ee6821edd86.gif)

Here is my screenshot

**Comment by benjanderson** [comment]
I am clicking on the tri flame, not just hovering
