### ISSUE TITLE
Loading ring slides around on Cashmere docs site (Chrome only)

### ISSUE THREAD

**Issue by isaaclyman** [HealthCatalyst/Fabric.Cashmere#917]
**Summary**

On Chrome, the Cashmere loading circle slides around while the docs site is loading, much like a hula hoop around the triflame. It should probably remain in the same place and just rotate the white bar.

See gif:

![cashmere-loading](https://user-images.githubusercontent.com/9139369/60988972-0c1d0000-a302-11e9-9f34-4d4aafb837d8.gif)

**Reproduction**

Steps to reproduce:

1. Visit https://cashmere.healthcatalyst.net on Windows 10/Chrome

NOTE: problem does not occur on Firefox, nor does it occur on the Progress Indicator example on any browser.

**Comment by corykon** [comment]
'much like a hula hoop' haha
