### ISSUE TITLE
Convert Example's scss Colors to Variables

### ISSUE THREAD

**Issue by andrew-frueh** [HealthCatalyst/Fabric.Cashmere#920]
**Describe your idea**

As per @corykon 's suggestion, it would be better if our color values in our Cashmere examples don't use hard-coded hex values.  They should really be using our color variables instead.  The problem has been figuring how to import the color variables sheet.

**What problem are you trying to solve?**

Using hard-coded hex values sets a bad precedent, when we're trying to have developers use color variables instead

**Comment by joeskeen** [comment]
Suggestion: use https://www.npmjs.com/package/scss-to-json during the build to extract the variables to a JSON file that can be used at runtime on the docs site?
