### ISSUE TITLE
How to Implement Launch Screen

### ISSUE THREAD

**Issue by corykon** [HealthCatalyst/Fabric.Cashmere#922]
**Where does our documentation fall short?**
How do I implement the launch screen?

_Tell us which Cashmere documentation page this request is about and what's missing or unclear. The rest of this form is optional._
Teams have just heisted the code from the cashmere index page. Wish should provide better instructions for how to do this, since its a little trickier when you're operating pre-angular bootstrap.

**What would you add or change?**
Prob add a new page under styles called something like "Application Launch Screen"

**Comment by andrew-frueh** [comment]
@joeskeen you were asking about this one.  Looks like we've had an issue sitting in the backlog for it, but haven't implemented it yet.  Bumping it up.
