### ISSUE TITLE
Can't pre-select a preset radio button on the date-range  component

### ISSUE THREAD

**Issue by jacquie** [HealthCatalyst/Fabric.Cashmere#939]
When you  add radio buttons for preset ranges on the date range component it doesn't seem to be possible to pre-select one when you bring up the modal.

We are currently replacing our interval picker with the date range component and want to be able to indicate the default range for the dashboard when the dashboard is first displayed. And then as the user chooses different ranges via the buttons I think they would expect them to still be set on subsequent visits to the directive.

**Comment by benjanderson** [comment]
Good find, having these presets displayed as radio buttons gives the impression that they should be selected if the current date matches. That is currently not the case and they act less as a state and more just a button, this needs to be fixed
