### ISSUE TITLE
Responsive Navbar

### ISSUE THREAD

**Issue by andrew-frueh** [HealthCatalyst/Fabric.Cashmere#94]
Enhance the existing hc-navbar component to be fully responsive, including phone and tablet resolutions.  Should follow the pattern currently defined in the styleguide:

<img width="274" alt="responsivenavbar" src="https://user-images.githubusercontent.com/22795893/35812227-a72c8bbe-0a4d-11e8-8a33-a676cef8d08a.png">

**Comment by andrew-frueh** [comment]
Question for the group as I look at the style guide's layout again.  In the mockup, "View All Applications" is at the bottom of the hamburger menu, which implies that there is only one dropdown menu in the mobile version - and the triflame would be inactive.  Given that the user would likely already expect the triflame to be the app switcher, would it make more sense to have two possible menus in the mobile version?  The hamburger menu with all the navbar-links, etc; and the triflame menu as the application switcher?

Having content spread across two menus could be annoying...but it also might be confusing if the tri-flame app switcher is suddenly disabled (I'm not sure all users would notice the "View All Applications" button either).  So I'm 50/50 on this one, would love some additional opinions.

**Comment by benjanderson** [comment]
As a user I think one menu would be the way to go.  If we are going to make our applications more mobile friendly I would think any navigation that is frequently accessed to be on the bottom as a static navbar.  This is the paradigm of most of the apps I use on my phone

![image](https://user-images.githubusercontent.com/1934453/35821327-e6681024-0a65-11e8-809a-5bd96870af0b.png)

**Comment by andrew-frueh** [comment]
Got another design for the group on this one.  How should we determine at what width we hide the navbar links/icons and switch to a right side hamburger menu?  It kind of depends on how many items are in the navbar, no?  Should that be a property added to the navbar that the dev can set to say what width to go mobile?  Maybe there should also be an intermediate step for tablet resolution before we collapse everything to the hamburger menu?

**Comment by benjanderson** [comment]
@andrew-frueh the ones you use are pretty close the boostrap standard
xs: 0, sm: 576px, md: 768px, lg: 992px, xl: 1200px

I am thinking that my next task will be some css cleanup where we can standardize these and have helper mixins
