### ISSUE TITLE
Toast Styles Questions/Suggestions

### ISSUE THREAD

**Issue by corykon** [HealthCatalyst/Fabric.Cashmere#943]
**Describe your idea**
Couple questions/suggestions. While implementing the cashmere toasts, there were two things we found ourselves wanting to change.

1. Long messages make for really wide, awkward to read toasts. Feels like this should have a max width somewhere from 300-400px and then the text should wrap.
![image](https://user-images.githubusercontent.com/12416432/62235512-66056880-b38a-11e9-8b73-7ec8885bbda3.png)

2. The message text font size seems small. We're sitting at about 12px by default, which is "extra small" on our typography guidelines. I'd love to have that be at least 14px ("small") by default.

**Comment by andrew-frueh** [comment]
Both these changes make sense to me - good suggestions @corykon .  Regarding the first one, do you think we allow the developer to set their own max width?  So maybe we add a `width` parameter and have it default to 400px.  And if it's set to 0, there is no max width and it behaves as it does currently.

**Comment by JDavidStevens** [comment]
It would be very helpful to have the option to include a progress bar with the toasts.  Here is an example:
![image](https://user-images.githubusercontent.com/27790008/62720774-f9145300-b9c7-11e9-83ac-f71ff13326c9.png)
