### ISSUE TITLE
Add "tight" option for components (especially form controls)

### ISSUE THREAD

**Issue by thighfield** [HealthCatalyst/Fabric.Cashmere#944]
**Describe your idea**

Trying to implement the Care Management app according to the mockups developed by Karri Quintana, our UX Designer--and especially our inline forms or "edit cards"--we find that the elements have a lot of built-in padding, large line-heights, etc., which make the forms much more spread out than we need. It would be nice to have an option like a "tight" directive we could include on the components or something similar that would allow us to achieve a tighter design without breaking existing apps that already use the controls. This option was discussed with Andrew Frueh several months ago and he seemed to be very supportive and enthusiastic for this idea. The current controls, with their included padding, etc. are a bit too "opinionated" for general use. They look fine on a large stand-alone form in a modal with lots of room, but look a bit too spread out when trying to use them in something like an inline edit card that appears within the context of a page displaying lots of other data. I would suggest working with Karri Quintana and Andrew Frueh on the details of spacing and sizing when implementing some type of "tight" option.
 
**What problem are you trying to solve?**

Many of the standard cashmere components (hc-tile, form controls, etc.) have too much built-in padding/margins/large line-height, etc. to make them general purpose enough for use throughout the application.

**Additional context**

**Comment by JDavidStevens** [comment]
We are seeing a similar issue with the check boxes as we implement them in Pop Builder. We feel that the padding and the size of the check boxes are too big. For now, we are going to override the size. Here is an example of the difference. 
![image](https://user-images.githubusercontent.com/27790008/62720328-0b41c180-b9c7-11e9-98ec-e5c36e79fbaf.png)
![image](https://user-images.githubusercontent.com/27790008/62720362-1c8ace00-b9c7-11e9-8c89-705986dcad9f.png)

**Comment by andrew-frueh** [comment]
@joeskeen - this is probably one we should prioritize.  It's a pretty straight forward fix, and I think it was probably an oversight to default the padding to values that looked best on the demo site.  

As a side note @JDavidStevens - your column configuration sidebar is looking good!
