### ISSUE TITLE
Typeform survey breaks the app it's running in

### ISSUE THREAD

**Issue by joeskeen** [HealthCatalyst/Fabric.Cashmere#947]
**Summary**

In both Atlas and IDEA, both style and functionality of the application is broken after the Typeform Survey is opened and closed.  The page must be refreshed before it can be used again.

**Reproduction**

Ask DGX team for show and tell.

**Possible Solution*

There are multiple ways to embed Typeform surveys into web applications.  Instead we could use a Cashmere drawer to open the survey and display it in an iframe instead of injecting foreign scripts into the page that have free reign on everything.  That way it will be in a sandbox and won't affect the page before or after it's used.

**Comment by joeskeen** [comment]
Also tracked in ADO: https://healthcatalyst.visualstudio.com/CAP/_workitems/edit/175016

**Comment by andrew-frueh** [comment]
My recommendation is that we sunset this component in favor of having apps either link to surveys in a new tab, or leverage the TypeForm API directly.

**Comment by andrew-frueh** [comment]
@joeskeen pointed out that this issue is not currently reproducible - possibly due to a fix on the TypeForm side
