### ISSUE TITLE
Improve Theme Support in Cashmere

### ISSUE THREAD

**Issue by joeskeen** [HealthCatalyst/Fabric.Cashmere#950]
**Describe your idea**

When defining colors in Cashmere, use the ` !default` directive. (see https://stackoverflow.com/a/17090334/1396477)

**What problem are you trying to solve?**

Although for Health Catalyst we want to keep colors the same, the library is much less flexible for others in the Cashmere community, most notably WCF.  If the colors or other variables (mixins too?) were able to be overridden, it would make it much easier for others to adopt the library.

**Comment by andrew-frueh** [comment]
Duplicated in #999
