### ISSUE TITLE
Collapsible navigation drawer (like ADO)

### ISSUE THREAD

**Issue by pheebner** [HealthCatalyst/Fabric.Cashmere#952]
The EDWOps team is working on changing navigation in Operations Console and we had the thought that it would be nice to have a Cashmere component that could do something similar to what the master navigation drawer in Azure DevOps does.  What we mean by this is that when it is open it shows icons to the left with text to the right, and when it is closed it shows only the icons.  This would allow the user to have more screen space while still being able to navigate by removing the text to the right of the icons.

**Azure DevOps where left navigation bar is open**

![image](https://user-images.githubusercontent.com/5783377/63119146-69454a80-bf6d-11e9-9aa9-ba8b677445b2.png)

**Azure DevOps where left navigation bar is closed**

![image](https://user-images.githubusercontent.com/5783377/63119199-9db90680-bf6d-11e9-9c3a-b2d3a8697040.png)

Here is a mock up of what we are trying to do in Operations Console:

![image](https://user-images.githubusercontent.com/5783377/63119364-f8eaf900-bf6d-11e9-9b0d-014de0958e98.png)

We will be trying to implement this in the Operation Console app and just had the thought that if we got something nice working we could add it to Cashmere as well as collaborate on it if there is enough interest.

**Comment by pheebner** [comment]
Mark suggested we could do this by adding some features to the HC tabs component.  We could have a "collapsible" flag that would work only for vertical tabs.  A caret or chevron like in the above picture would appear if the tabs are collapsible.

**Comment by joeskeen** [comment]
That's an interesting idea!  I like it and it may be easier to implement than a drawer-based solution.  My only question with that is will we never have subitems?  I know with the navigation with ADO there are top-level and subitems that may appear on the left.

**Comment by pheebner** [comment]
We thought it would be nice to have sub items in the component, but I'm not sure we need them in Ops Console, at least the way it is now. I get a whiff of a code smell though if we add all this to the vertical version of the tabs but not the horizontal version.  Makes me just wonder if it should be its own component.

**Comment by andrew-frueh** [comment]
Closing as per conversation with @pheebner
