### ISSUE TITLE
Allow banner (without padding) at top of modal body

### ISSUE THREAD

**Issue by joeskeen** [HealthCatalyst/Fabric.Cashmere#954]
**Describe your idea**

Much like modal header, body, and footer, it would be nice to be able to specify a banner that would display without the body padding.

**What problem are you trying to solve?**

A couple pictures say 1K words:

This is what you can do today out of the box:

![image](https://user-images.githubusercontent.com/12286274/63393059-94b5a400-c376-11e9-83be-57a0dc477ee0.png)

This is what I would like to do:

![image](https://user-images.githubusercontent.com/12286274/63393002-47d1cd80-c376-11e9-968d-513f15521f6c.png)

Currently this is only possible by overriding Cashmere styles, which would be great to not have to do.

**Comment by andrew-frueh** [comment]
Related to #944
