### ISSUE TITLE
hc-table not working with @angular/cdk version 8

### ISSUE THREAD

**Issue by petermcclanahan** [HealthCatalyst/Fabric.Cashmere#958]
**Summary**

Upgrading @angular/cdk to version 8 causes hc-table to fail. See the following stackblitz: 

https://stackblitz.com/edit/angular-kwrmwq

Lowering the @angular/cdk version to 6 solves the problem.

**Comment by joeskeen** [comment]
As Cashmere currently targets Angular 6, it's not a surprise that CDK 8 (which is designed for Angular 8) has compatibility issues.  Currently Cashmere supports CDK 6 and 7.  When we change Cashmere to target Angular 8 we will also upgrade the peer dependency to CDK 8.

**Comment by joeskeen** [comment]
Related: #1230
