### ISSUE TITLE
Modal should not open more than one instance of itself at a time

### ISSUE THREAD

**Issue by tfoxley** [HealthCatalyst/Fabric.Cashmere#959]
**Summary**

You can open the same modal as many times as you want and they will just continually stack on top of each other. The modal should either prevent the same one from being opened multiple times or it needs to expose a function that allows a consumer to check and see if it is already open.

**Reproduction**

Steps to reproduce:
1. On the example page click on the either of the buttons to open the modal.
2. The button will still have the focus so if you hit the enter key a few times now you will open a few more of the same modal. The overlay gradually gets darker and you have more modals to close now.

**Additional context**

![image](https://user-images.githubusercontent.com/344920/63725612-1e9eba80-c818-11e9-957c-89a811a21092.png)

![image](https://user-images.githubusercontent.com/344920/63725639-30805d80-c818-11e9-80d3-9de88b48000c.png)

**Comment by andrew-frueh** [comment]
@tfoxley - thanks for submitting this issue!  Please take a look at the PR currently in review #990 and let me know what you think.
