### ISSUE TITLE
Help Menu change

### ISSUE THREAD

**Issue by aflanders** [HealthCatalyst/Fabric.Cashmere#961]
**Goal:** Update Help Menus in apps to align with new documentation strategy and to be more actionable.
**Change Needed:** Please change the bullets on this page to align to the below and add icons (suggested icons listed below; if this doesn't work, we can nix the icons): https://cashmere.healthcatalyst.net/components/navbar/usage

WHAT ITEMS SHOULD GO IN THE HELP MENU?
You may not have all these items available. However, include what you have in this order:

- [fa-book] **Read the docs** (link to the [docs site](https://www.healthcatalyst.com/docs/) or your help docs repository on HCC)
- [fa-lightbulb] **Request a feature** (link to your feature request page on HCC)
- [fa-users] **Ask the community** (link to your Q&A page on HCC)
- [fa-bullhorn] **Find out what's new** (link to your release notes on HCC)
- [fa-comments] **Send feedback** (see the [User Feedback Guide](https://cashmere.healthcatalyst.net/components/typeform-survey/examples))
- [fa-info-square] **About** (a modal containing app reference information - see the [associated style page](https://cashmere.healthcatalyst.net/styles/about) for guidelines)

**Comment by joeskeen** [comment]
![image](https://user-images.githubusercontent.com/12286274/64662328-463f7680-d405-11e9-8ef8-419f638bf509.png)

**Comment by joeskeen** [comment]
@andrew-frueh we have implemented the menu bits, but have we documented the standard help menu changes?  I don't think that we have (at least I can't find them on the Cashmere docs page).

**Comment by andrew-frueh** [comment]
Hey @joeskeen - I actually did make those updates that @aflanders requested here:
https://cashmere.healthcatalyst.net/components/navbar/usage

...and I also updated the examples to use these updates.  Is that what you're referring to or was it something else?

**Comment by andrew-frueh** [comment]
Just documenting that these changes have been made and are live on the demo site
https://cashmere.healthcatalyst.net/components/navbar/usage

<img width="1021" alt="Screen Shot 2019-11-21 at 5 09 50 PM" src="https://user-images.githubusercontent.com/22795893/69387062-db6eaf00-0c81-11ea-8e84-80c1c64090d1.png">

<img width="982" alt="Screen Shot 2019-11-21 at 5 09 29 PM" src="https://user-images.githubusercontent.com/22795893/69387066-e1649000-0c81-11ea-9181-d75ded8b6420.png">
