### ISSUE TITLE
Standard Template for Documentation

### ISSUE THREAD

**Issue by jtrujill** [HealthCatalyst/Fabric.Cashmere#97]
I would like to change the way that we do documentation so that we're using markdown instead of straight html. With css and html, there is too much freedom in the way to style the documentation, which makes writing it and maintaining it difficult.  Markdown is simpler to write and would allow us to have more uniform docs.

The other issue is that for a user to read about how to use our library they must have it running locally or go to http://cashmere.azurewebsites.net/. It would allow people to read on docs on github or read it locally without running a server.

It's still great that we have demo usage of the app but I'd like to separate the two.

**Comment by benjanderson** [comment]
I love this idea, doing it with a custom webpack build would be straight forward but I dont know how to do it with the angular cli as it abstracts the webpack build from us

**Comment by jtrujill** [comment]
This is a whole other issue but maybe this is an argument for moving towards a gulp build? It's a pain to setup initially but it does offer more than the cli. 

To go along with this, I'd also like to restructure the project so that the /docs contains our markdown and the lib and demo can be found under /src/lib and /src/demo. It's very standard to put your code under the src directory, besides that, the new structure is awesome

**Comment by jtrujill** [comment]
After thinking about this a little more. Do we really need webpack? All we need to do is run a node program to transform the markdown to html and put that html in the dist folder. Then we could reference the doc.index and we should be good

**Comment by andrew-frueh** [comment]
Brilliant.  I think this makes perfect sense, and it will help to standardize the style of our documentation - which only makes it more readable.  Let me know what I can do to help.

**Comment by benjanderson** [comment]
I like were you are going with this @jtrujill but I have a few implementation questions

1. Are we going to check-in the generated html files? If not, how is a new contributor going to be able to read documentation. If so, how do we keep the html and md in sink?

1. How are we going to keep our demos live implementations of the components when they are based off markdown? How do you reference the html from the component?

**Comment by jtrujill** [comment]
I wouldn't check the generated html files in. Github renders markdown files for you, so the user would be able to go through the /docs directory and view them through github. We would want to generate the html so that we could link the documentation to our demo app. The html would just be a part of the artifact that is generated for the demo app.

In our app we would just have an anchor which references the root of our markdown file, which would actually be html after being run through the converter, and we would just need to set the server up so that any requests for a file without an extension checks to see if an html file for that resource exists and if so serve that up.

This would unload the demo app and go to a regular html page and we could have a link back to the demo app. 

That's what I had in mind at least. I'm not great at setting up IIS rules, since I'm still new to Microsoft tech, but I'd imagine that's easy

**Comment by jtrujill** [comment]
Another thing, I imagine that other IDEs have markdown rendering plugins, but I'm able to view the rendered content through my IDE. These plugins are great for knowing what the final look is but for also viewing the documentation, without all that markdown noise

**Comment by andrew-frueh** [comment]
Changing the name of the issue because I think it pulls together a few things that I'll try and get a consensus from the group on next week:
- What information belongs on our "Documentation" pages for our components
- Can we create a documentation template to follow what is decided on above
- Can that content be automatically generated and then piped into that template
