### ISSUE TITLE
Optional tooltips for tabs

### ISSUE THREAD

**Issue by pheebner** [HealthCatalyst/Fabric.Cashmere#973]
We on Ops Console thought it would be nice to be able to optionally add a tooltip to an hc-tab component if desired.

We are using vertical tabs for a collapsible side navbar and want to be able to add a tooltip when the navbar is collapsed and only icons are showing (like in VSTS).

I've written a component that adds the tooltip to its parent in ngAfterViewChecked, but this seems like a hacky way to do things.

Here's an example of what we want to happen when our navbar tabs are "collapsed"
![image](https://user-images.githubusercontent.com/5783377/64787401-9a9a4180-d53e-11e9-84e6-3f919f0c9c5a.png)

**Comment by andrew-frueh** [comment]
This was closed in the following pull request:
https://github.com/HealthCatalyst/Fabric.Cashmere/pull/979
