### ISSUE TITLE
Right click context menu

### ISSUE THREAD

**Issue by corykon** [HealthCatalyst/Fabric.Cashmere#975]
**Describe your idea**
Would be awesome to include a right click context menu like this one:
![image](https://user-images.githubusercontent.com/12416432/64894116-1aef9e00-d636-11e9-8379-c45c701ecce0.png)

Found in user testing that people love these. Might be nice to encourage app across the suite to use this pattern as much as makes sense.

**Tell us what you wish Cashmere could do. The rest of this form is optional.**
Reuse our popover menu, set up a nice directive like `hc-pop` but for right click context menus.

**What problem are you trying to solve?**
Introduce a pattern that many users appreciate. Its a nice escape hatch when you're not sure where to go to accomplish a task.

**Comment by andrew-frueh** [comment]
It was discussed in the steering committee meeting that this should actually be an enhancement to `hc-pop` rather a new component.  Thinking it will be an additional placement option that allows the popover to be placed at the point of the mouse click.  And also an additional trigger for right-click.  We'll also update the examples too.
