### ISSUE TITLE
public_api

### ISSUE THREAD

**Issue by jtrujill** [HealthCatalyst/Fabric.Cashmere#98]
Shouldn't the public_api folder export the index file of each component and not just the module?

```javascript
export * from './src/app-switcher/app-switcher.module';
export * from './src/button/button.module';
export * from './src/checkbox/checkbox.module';
export * from './src/drawer/drawer.module';
export * from './src/icon/icon.module';
export * from './src/list/list.module';
export * from './src/navbar/navbar.module';
export * from './src/pipes/pipes.module';
export * from './src/popover/popover.module';
export * from './src/radio-button/radio-button.module';
export * from './src/select/select.module';
export * from './src/tabs/tabs.module';
```

**Comment by corytak** [comment]
@jtrujill I had the same question but @joeskeen assured me that ng-packagr when running `ngc` exports all of the declarations in a module. I tried importing the tarball this morning based on his changes and it was able to successfully identify the components despite not being exported.

**Comment by joeskeen** [comment]
If you run `node lib/build.js` from the root of the project, you will see in `lib/dist/cashmere.d.ts` that all exported components are exports of the package.  A reason I went with this route was to prevent things from accidentally being referenced by the index (demo components, etc.), and I also had some issues with the TS barrel files (the index.d.ts files that just exported everything).  If you are having specific issues with this, I'd be happy to talk about it, though.

**Comment by jtrujill** [comment]
Maybe I shouldn't have marked it as a bug but a question instead. What issues we're you running into with the barrel files? I prefer to be explicit with the exports.

**Comment by benjanderson** [comment]
@joeskeen is correct, the module does export all the needed files. That is unless you have an interface or other helper classes that aren't being referenced in the dependency tree.

Many people have not kept the `index.ts` barrel files up to date, so an upcoming pull request removes them as most are out of date. I like sticking mostly with the modules unless you have something else that isn't being exported (see above)
