### ISSUE TITLE
Date type validation not firing when text entered into DatePicker input.

### ISSUE THREAD

**Issue by jaysonolson** [HealthCatalyst/Fabric.Cashmere#982]
**Summary**

We have several reactive forms in our Care Management Angular application that contain DatePicker input fields (using the Cashmere DatePicker component).  For fields that are not required and have no default date set, the user can enter text and either tab or submit with no date-type validation firing.

If you do set a default date on initial render and then enter text, the date-type validation will work as expected.

Link to demonstration video created by Joe Skeen: 
https://slack-files.com/T04807US5-FLE31V17H-99129ea2fc

**Reproduction**

Stackblitz forked example:
https://angular-tmcxwy.stackblitz.io

**Additional context**

Link to conversation in Cashmere Slack channel (originally posted by Chad Rockwell on 07/11/2019):
https://healthcatalyst.slack.com/archives/C75LHAV9S/p1562880691016500

**Comment by jaysonolson** [comment]
As a work-around, we implemented the following:

    <hc-form-field>
        <hc-label>Some Date</hc-label>
        <input hcInput [hcDatepicker]="picker1" formControlName="someDate" class="cursor-pointer" (change)="onSomeDateChange()" />
        <hc-datepicker-toggle hcSuffix [for]="picker1"></hc-datepicker-toggle>
        <hc-datepicker #picker1></hc-datepicker>
        <hc-error>Please enter a valid date</hc-error>
    </hc-form-field>

`
public onSomeDateChange(): void {
    this.someForm.get("someDate").updateValueAndValidity();
}
`

**Comment by andrew-frueh** [comment]
Ah - this is really helpful.  I tried to reproduce #750 on our example page but couldn't recreate the error.  It looks like this is speaking to the same issue, but the additional details help clear it up.  I'll plan on submitting a PR to fix this by the end of this week.  I'll make sure and have @Techgeekster review to make sure the fix addresses the issue in CM.  Thanks for all the documentation on this issue @jaysonolson

**Comment by andrew-frueh** [comment]
@joeskeen @benjanderson - I started digging into this tonight and I think I'm seeing why this is happening.  If `[(ngModel)]` is not defined on the input element for the datePicker then the `validate()` function on the input directive will never be called.  So it seems we need to somehow initialize the FormControl elements so validation is called even in the absence of ngModel being defined.  I'll continue to research, but if either of you or @jaysonolson have any suggestions please let me know.
