### ISSUE TITLE
Typeform survey component issue binding appVersion to a variable that changes

### ISSUE THREAD

**Issue by braydengramse** [HealthCatalyst/Fabric.Cashmere#984]
I was having some trouble adding the typeform survey component to our app. I originally tried to add it like so thinking it would work just fine:
``` html
<hc-typeform-survey [surveyUri]="surveyUri" [appVersion]="navbarService.assemblyVersion"></hc-typeform-survey>
```

What actually happens with `navbarService.assemblyVersion` is that it starts out as `undefined` and then updates to the correct value once we get the value back from the server. The typeform survey component was initialized before the correct value was populated and so the app_version wasn't being set in the typeform survey URI. The typeform survey URI is only updated once when the component is initialized (using `ngOnInit()`) and doesn't update itself if the input values change. @corykon was able to help me with a work-around (shown below) in the meantime but I think this should be something that the typeform survey component handles.

``` html
<hc-typeform-survey *ngIf="navbarService.assemblyVersion" [surveyUri]="surveyUri" [appVersion]="navbarService.assemblyVersion"></hc-typeform-survey>
```

**Comment by andrew-frueh** [comment]
@corykon - since you were able to come up with the work-around on this one, would you be willing to submit a PR for this fix?  @joeskeen has identified it as being a high-priority bug to get fixed.
