### ISSUE TITLE
StackBlitz for examples with multiple components don't work

### ISSUE THREAD

**Issue by joeskeen** [HealthCatalyst/Fabric.Cashmere#997]
**Summary**

The StackBlitz for examples with multiple components declares a module file for the example, but doesn't export the components from that module, so the example doesn't work in StackBlitz.

**Reproduction**

Click "Edit On StackBlitz" button on the Modals example.  You'll get this confusing error:

![image](https://user-images.githubusercontent.com/12286274/65525929-7bd86b00-dead-11e9-8193-b5f4efd8ae1e.png)

We just need to make sure that not only are the components declared, but also exported in the examples using a module file.

**Comment by andrew-frueh** [comment]
Fixed in #1274
